### ISSUE TITLE
Check occupancy database of Singapore

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1074]
Singapore schedules of occupancy should not follow seasonal patterns.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I checked that. There is no seasonality in occupancy in Singapore. It's always 100%.
I guess you saw my graphs for testing of the cooling technologies. They where done with location=CH and weather=Singapore. That's why they have seasonal occupancy.

**Comment by JIMENOFONSECA** [comment]
Ok got it. Thanks. Lets close this issue then

On 1 Mar 2018, 10:24 +0800, Gabriel Happle <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> I checked that. There is no seasonality in occupancy in Singapore. It's always 100%.
I guess you saw my graphs for testing of the cooling technologies. They where done with location=CH and weather=Singapore. That's why they have seasonal occupancy.
