### ISSUE TITLE
Multiprocessing for thermal network

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1090]
Multiprocessing to speed up the thermal_network_matrix.py script. 

There are two primary for loops in the file, each over 8760 time steps. Each time step is independent of the other time steps.  

1st loop: Calculation of edge mass flows (lines 800 to 831 )
2nd loop: Calculation of thermal network properties (lines 146 to 222 )

@daren-thomas could you have a look at this? Or, if you don't have the time to implement it, do you have any advice on how to implement multiprocessing in a case like this?

**Comment by roglen** [comment]
Line numbers refer to the code which is currently still in the branch i1031. Since the pull request has been accepted, it should be merged soon.

**Comment by daren-thomas** [comment]
Sure! I'll have a look! What's the priority? When is it due? (what Milestone do you need this to be in?)

**Comment by roglen** [comment]
@daren-thomas I just added them in. Basically, the sooner the better since we will be starting to run optimization with results from this script and run time is quite high.

**Comment by shanshanhsieh** [comment]
Hi @daren-thomas , perhaps you can tell us what is the estimate of this issue first?
after that, we can divide the work once you show us how to get it done on our own (if possible)

this is a must for lenny's thesis, and it's blocking the progress now. However, it is not a *must must* for super-final milestone, so it should not block other issues of yours for too long as well.

**Comment by daren-thomas** [comment]
@shanshanhsieh, @roglen I'm looking at the source right now. of course it's confusing  - there are a lot of variables. multiprocessing will be able to halve the time. maybe a third - how long does it currently take?

The code isn't factored nicely - that is, the first step would be to make the body of the for loops you want to multiprocess each a separate function... This is quite easy to do, but as I see it right now, there are a lot of parameters being passed around. Where do they come from?

My thinking was... depending on how long this takes in singe process... maybe moving this kind of computation to the euler cluster could be an idea? It depends a bit on how the whole data flows through the application. Do you have an overview schematic of what is happening here?

Which variables hold data relevant to the whole year? which variables only hold data for a single timestep? Is each timestep independant of the previous timestep?

I think this could take a few days. First, I'd need to be able to run it. On `master`, I get the following error:

```
AttributeError: 'GlobalVariables' object has no attribute 'Cpw'
```

**Comment by roglen** [comment]
Hi @daren-thomas, I'm getting the same error in the master right now. basically a merge today changed the globalvar file so gv.Cpw needs to be renamed to gv.cp and divided by 1000. And gv.Pwater is now gv.rho_60. I'm not sure where exactly this change came from or why it was made, I will discuss with @JIMENOFONSECA  tomorrow. 

Current run time of the script is very dependent on the network complexity. The open case takes around 50 minutes. 

Moving the loops into their own functions shouldn't be a problem. Most of the parameters are being moved around within the script, but there are some links with csv files and the substation_matrix.py. 

Concerning a schematic - something of the sort is in progress. For my master thesis I am documenting the main parts of the script and made diagrams of the iteration loops. It's far from everything, that is happening in the scripts but it might be a start - I can send them to you on slack if that helps. 

I can set up a list of parameters storing full year data and hourly data tomorrow and pass it to you. Every time step is independent of the previous timestep.

**Comment by daren-thomas** [comment]
great! looking forward!

**Comment by daren-thomas** [comment]
OK. Great. Now's a good time to start working on the interface: Parameters in and out of your functions. I'd _love_ to get rid of the `gv` parameter, so let's make sure this script doesn't rely on it. I'm looking into adding a module `cea.constants` to replace it and will update the branch accordingly.

**Comment by daren-thomas** [comment]
@roglen did you wait for the whole code to run through? because PyCharm thinks `hourly_thermal_calculation` can't work - there are variables (such as `T_supply_nodes_list`) that are not initialized. At least not inside `hourly_thermal_calculation`. What I think is happening is that you want to append to your lists _after_ the loop.

This is made a lot harder in that a lot of the functions return tuples - and have a ton of parameters. This makes it really hard to work with. I wonder if we can group some of them together a bit?

**Comment by roglen** [comment]
Strange, i ran it all the way through! In any case, the problem should be solved now:

I've moved the lists for data storage into a dictionary, so this already reduces the amount of inputs significantly and actually eliminates all outputs of the hourly_thermal_calculation function. Since all these variables are data storages I think grouping them makes sense. 
I also grouped some of the other input variables into a dictionary to try and clear things up a bit. 

For the gv it really is used everywhere! Not sure what we can do about it though.

**Comment by daren-thomas** [comment]
Alright! That's two steps forward! ...and one step backward: for multiprocessing, we need to be careful how we modify mutable variables (like dicts and dataframes).

I would like to spend today refactoring this code a bit. I'll need to create some unit-tests first - to make sure I'm not breaking anything. Do you have any way to check if the output of the whole thing is still the same after making changes?

**Comment by daren-thomas** [comment]
OK. So. slowly i'm working through the code. @shanshanhsieh I was just working on the substation HEX thing and noticed that the other place it get's called (in substation) was broken - I fixed the call to the function as I was changing the signature anyways, but I think you need to test the substation code again. It probably hasn't been tested since your commit 3ecbbeb7baeca4da0855d8130f61b88b6b800c35

**Comment by daren-thomas** [comment]
I have to finish for today, so, @roglen, if you want to take over: step by step reducing complexity. check out my latest commit: `substation_HEX_design_main` was returning a tuple, but actually, it was two functions in one...

A logical next step would be to look into making `buildings_demands` a dictionary of data frames instead of a list - that would mean we only need to pass `buildings_demands` to various functions, as the building names can easily be found with `buildings_demands.keys()`...

**Comment by shanshanhsieh** [comment]
@daren-thomas , i checked the results from `substation_HEX_design_main`, it is still giving the same results as in the master scripts. 
And maybe we could make a list of functions that we should write tests for, but probably not in super final cea tho...

**Comment by shanshanhsieh** [comment]
Functions require testings: (pls add more)

- substations_HEX_design_main
- get_thermal_network_from_shapefile
- calc_supply_temperatures
- calc_return_termperatures
- calc_aggregated_heat_conduction_coefficient

**Comment by daren-thomas** [comment]
Here's an overview of the module:

![image](https://user-images.githubusercontent.com/2969564/37293881-dbee27d0-2614-11e8-9ac1-b9c94577f9ec.png)

(yes, that took a while to create. but now i kind of understand a bit better what is going on. it's still hard to understand because i can never exactly remember the shapes of the dataframes being passed around...)
