### ISSUE TITLE
As a practitioner I need a robust and easy installation for CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1092]
@daren-thomas It would be good to take the next step and get a simple and robust way to install CEA. I am willing to put some extra resources if necessary. So let's think about how we achieve this. We can even ask the GUI guys to give us a hand.

The way I imagine it this to work is like this:

Installation of the latest stable version (2.7):
1. do pip install cea or pip install cea --arcgis to include arcgis support

Installation of bleeding version (master)
1. clone repository and point to repository.
2. do pip install cea .[dev] do pip install cea .[dev] --arcgis to include arcgis support

I think the part of creating an environment automatically as today should be changed. It is a good practice but the user should be able to create an environment with the name he/she likes. Or maybe not creating an environment at all. I, an intensive user of the tool :-), does not care about creating an environment as the only thing I use is CEA.

We can include the idea of creating an environment a recommendation but up to the user to do.

@daren-thomas let me know your thoughts.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the reason we use conda and create an environment is because `pip install` can't install all our dependencies. We rely on libraries that can't be pip installed. The conda system provides a way to install pre-built binary versions of tools, including stuff that isn't python. We need this for the GDAL stuff.

As for the name of the environment: That can be changed by the user - `conda env create --name whatever-you-want`.

Have you seen the installer for CEA? If it is an "easy" way of installing the CEA you're after, why don't we go down that route instead? The planner's edition installer actually just downloads and installs Miniconda in the background, creates the environment and then pip install's the latest version from PyPI. I think this could be expanded on - including installing a nice console (`cmd.exe` or the `Anaconda Prompt` are not nearly as nice as for instance the `Console Emulator` which I use), adding an environment for interactive exploration (I'm thinking of something like [JupyterLab](http://jupyterlab.readthedocs.io/en/latest/) along with a `cea.api.demand(scenario=r"c:\reference-case-open\baseline")` style high-level api to the scripts).

As for robustness: The current installation method is tested on every merge to master and every time a pull request is created / modified - so I'm not quite sure what you mean with your title: It seems to be suggesting the current installation method isn't robust? I'm surprised.

So. My thoughts: What is it you actually want to solve here? Who do you want to solve it for? This issue seems to have multiple audiences. What exactly is the problem you're trying to solve?

**Comment by JIMENOFONSECA** [comment]
Great explanation! Here are my thoughts.

As for the installer idea. Brilliant! This could give access to the stable version. A really ‘easy’ solution we are after. Maybe we can connect the installer link to the docs?

As for the version in master. Right, we could then stick to the current process if there is not another alternative. But what about doing something like conda install cea .[dev]? Forgetting about pip install then? Would that work?

Regarding the dependencies. Maybe it would be good to check what are the libraries that depend on conda. I see pip install versions for gdal as well as geopandas. Maybe it could be something to check? Maybe the conda install part will already do the trick.

As for the conda environment. It seems every time we do pip install cea . It creates an automatic environment. Should not this be up to the user to decide?

As for robustness. The installation seems to be failing on master (i just created an issue about this). Some times it misses the dependencies to run all cea. And well it seems it is a repetitive case where the installation has bugs here and there. I just wonder how can i minimize the time of installing while maximizing that of using the tool.

My motivation. I just see how many libraries out-here are super easy to install, even tensorflow staring from v1.5 (with tons of other binaries and dependencies. And I just wonder how can we get there? What are we missing?

Do not get me wrong. I think we have substantially improved the way we install cea. It took literally years and lots of effort and I am glad of what we have achieved so far. However I sincerely think we could brush things a little bit up.

On 2 Mar 2018, 17:06 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> the reason we use conda and create an environment is because pip install can't install all our dependencies. We rely on libraries that can't be pip installed. The conda system provides a way to install pre-built binary versions of tools, including stuff that isn't python. We need this for the GDAL stuff.

As for the name of the environment: That can be changed by the user - conda env create --name whatever-you-want.

Have you seen the installer for CEA? If it is an "easy" way of installing the CEA you're after, why don't we go down that route instead? The planner's edition installer actually just downloads and installs Miniconda in the background, creates the environment and then pip install's the latest version from PyPI. I think this could be expanded on - including installing a nice console (cmd.exe or the Anaconda Prompt are not nearly as nice as for instance the Console Emulator which I use), adding an environment for interactive exploration (I'm thinking of something like JupyterLab<http://jupyterlab.readthedocs.io/en/latest/> along with a cea.api.demand(scenario=r"c:\reference-case-open\baseline") style high-level api to the scripts).

As for robustness: The current installation method is tested on every merge to master and every time a pull request is created / modified - so I'm not quite sure what you mean with your title: It seems to be suggesting the current installation method isn't robust? I'm surprised.

So. My thoughts: What is it you actually want to solve here? Who do you want to solve it for? This issue seems to have multiple audiences. What exactly is the problem you're trying to solve?

**Comment by daren-thomas** [comment]
hm... ok. some thoughts:

- `conda install cea .[dev]` is not really how conda works. i think we might be able to provide a conda package (like on conda-forge or have our own channel) but that's a lot of work and a learning curve that i don't think is really necessary - but yes. we could look into doing that. basically, we would end up with `conda install cityenergyanalyst` - and then make sure we have up-to-date packages online.
  - note that this would be for users of the software - developers will still need to `pip install -e .`, because you need to tell the environment to also look through the repository for scripts (like the `cea` script - that is pip magic working there)...
- `pip install cea .` is not something we ever do. i'm sorry, i don't really understand what you're trying to say here... 
  - *unless* you mean `conda env create` - yes, that does create a new environment. the user could use `conda env update` to update the `cea` environment - OR `conda env update --name your-own-env` to update their preferred environment
- as for the robustness question: personally, i think it's good to reinstall every now and then - even if it is annoying. this tests the installation process and makes sure, that we *aren't* missing dependencies that other scripts use. thats a good thing!! but yes. it's annoying that you sometimes have to wait when all you want to do is fix a small bug. it helps to create different environments sometimes (`conda env create --name 2018.03.05` will create a new environment with a specific name that you can use for temporary purposes...). 
- yes. i agree totally: if we can move from conda to pip, then maybe we should do that. this will require some research. this is a bit of a timing issue: i expect this will take up to two weeks of my time to sort out properly. and might result in: nope, won't work. it depends on having all of our dependencies pip installable on windows without a compiler. OR we require a python compiler suit installed on the user computer - but that makes installing the software take (way!) longer and is hardly an improvement as it opens a whole other can of worms.

so. to conclude: this issue needs to be addressed! but my question is _when_? i don't see this being relevant for the executive course?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas Great discussion. 

I see this not going for the executive course. I would keep it in the parallel milestone 3.

I agree on creating conda install cityenergyanalyst and add flags. --arcgis to install the toolbox or not. and keep pip install -e for developers. 

As you said, making all pip will take too much effort.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas how far are we of creating an .exe file that does all the magic including downloading the repository and activating the development version? everything I mean

**Comment by JIMENOFONSECA** [comment]
After some discussion with @daren-thomas , I believe we should go the executable route. At the best we develop a Cross-platform installer of CEA. The installer should prompt to the user the next options.

1. Indicate where CEA will be installed.
2. Repair existing installation of CEA
3. Do a fresh installation of CEA.
4. Install the latest version of CEA.
5. Install the Developer version of CEA.

Deliverables:
Installer of CEA for Windows.
Installer of CEA for Mac OX
Source code of both installers.
