### ISSUE TITLE
CEA cannot run case studies where heating and cooling seasons overlap

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1176]
The CEA `systems_controls` database includes the dates when the heating season starts and ends, and the dates when the cooling season starts and ends. However, it is *not* possible to run CEA if the heating and cooling seasons overlap (see `calc_heating_cooling_loads`).

Does this make sense? Couldn't there be buildings that might need cooling even during the nominal heating season (e.g. highly insulated buildings with lots of internal gains)?

And if it does make sense, shouldn't it be enough to define a heating season *or* a cooling season rather than both (instead of defining them separately and then needing to check that the entire year is covered)? @gabriel-happle @JIMENOFONSECA

**Comment by martin-mosteiro** [comment]
@gabriel-happle Another interesting outcome of having cooling in the "heating season"... The heat pump code (`HP_air_air`) breaks down because the temperature difference in the evaporator and condenser approaches 0 and thus the COP approaches infinity...
Seems like the issue might be that such buildings with high gains need an appropriate ventilation system (i.e., the one assigned by the archetypes might be inadequate).

**Comment by gabriel-happle** [comment]
Hi @martin-mosteiro, I did some quick research about heating and cooling seasons. I.e., times of the year when heating is allowed in Europe.
It seems this only applies for residential buildings, I.e., MULTI_RES and SINGLE_RES. Or do you know any information that says otherwise?

I guess one way to move forward is to apply heating and cooling seasons only to residential buildings.
For the other buildings we can modify that the algorithm decides what to do.
Of course this requires some testing, because we want to avoid a situation where heating and cooling happens intermittently.

What do you think?
