### ISSUE TITLE
Prepare Testrun invitation document

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1214]
Hello @JIMENOFONSECA and @martin-mosteiro ,

I'd like to ask for your feedback on the test run invitation document, focusing on the following points:
- Can you check the document and add your comments and suggestions?
- What case study do you think we should present? Singapore or Zurich? (Personally I would choose Singapore so we can check the case studies we developed)
- Could you please recommend 2 images instead of the ones at the end of the document, and upload them here?

Here is the document:
[20180524-25_Testrun.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1903443/20180524-25_Testrun.docx)

**Comment by JIMENOFONSECA** [comment]
I think, they should use the Singaporean cases. For graphs I would suggest to add the new plots of CEA. I created some for Amr a while ago, so I Imagine we can use those as well (they are on slack)


________________________________

**Comment by amraladdin** [comment]
Here is the invitation final version. If you guys agree @JIMENOFONSECA @martin-mosteiro , I will begin distributing. Otherwise, please edit the word document and upload here again.
[20180524-25_Testrun_Final.pdf](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1939842/20180524-25_Testrun_Final.pdf)
[20180524-25_Testrun_Final.docx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1939843/20180524-25_Testrun_Final.docx)

**Comment by JIMENOFONSECA** [comment]
Looks good to me. Thanks for this.

Best,
Jimeno

On 24 Apr 2018, 04:15 +0800, Amr Elesawy <notifications@github.com>, wrote:

Here is the invitation final version. If you guys agree @JIMENOFONSECA<https://github.com/JIMENOFONSECA> @martin-mosteiro<https://github.com/martin-mosteiro> , I will begin distributing. Otherwise, please edit the word document and upload here again.
20180524-25_Testrun_Final.pdf<https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1939842/20180524-25_Testrun_Final.pdf>
20180524-25_Testrun_Final.docx<https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1939843/20180524-25_Testrun_Final.docx>

**Comment by martin-mosteiro** [comment]
Looks good to me!

**Comment by amraladdin** [comment]
Done, I sent an email to our Lehrstuhl and MBS students groups. Please circulate. Also find the post on my private LinkedIn page
https://www.linkedin.com/feed/update/urn:li:activity:6394449350478610433
