### ISSUE TITLE
Presentation template for executive course

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1230]
Hi @amraladdin,

would you mind creating a presentation template for the executive course. Ideally it should be a mix between the template for the tutorials and the official value lab presentation template of FCL.

Please not that the Value Lab has a huge screen that reaches down to the bottom of the room. So presentations should not contain any relevant information in the bottom quarter of the slides due to visibility issues.

here are some pictures of the room:
http://www.fcl.ethz.ch/research/collaboration/VLA.html

**Comment by gabriel-happle** [comment]
Here is the official FCL presentation template for the Value Lab.
The dotted lines on the slides mark the individual screens of the value lab.

[FCL_Presentation_template.pptx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1913844/FCL_Presentation_template.pptx)

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA @BhargavaKrishnaSreepathi @shanshanhsieh @shizhongming @martin-mosteiro you can follow this issue for updates on the lecture presentation.

**Comment by amraladdin** [comment]
[CEA_Presentation_template.pptx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1914496/CEA_Presentation_template.pptx)
Hello everyone, I like the FCL template you sent... I edited it a bit and I think it works well.

Please send me your feedback one more time before we close this issue @JIMENOFONSECA @gabriel-happle @shanshanhsieh @shizhongming @martin-mosteiro @BhargavaKrishnaSreepathi

**Comment by shanshanhsieh** [comment]
What is the official name of the executive course?
According to the poster, it's called *The 2018 executive course on Urban Energy Systems*
Just thinking that it should be coherent at every place.
https://cityenergyanalyst.com/executive

**Comment by amraladdin** [comment]
Totally agree! Please feel free to edit the document and upload it again in this thread.
Thanks Shanshan!

**Comment by JIMENOFONSECA** [comment]
Yes, the name of the poster should be the correct one

On 16 Apr 2018, 16:51 +0800, Shanshan Hsieh <notifications@github.com>, wrote:

What is the official name of the executive course?
According to the poster, it's called The 2018 executive course on Urban Energy Systems
Just thinking that it should be coherent at every place.
https://cityenergyanalyst.com/executive

**Comment by gabriel-happle** [comment]
at @amraladdin I don't think this template will work. It doesn't have a good slide master, no slide numbers, no header/footer and also no real space for content.
I saw the slides you sent me from Energy and Climate Systems have basically two columns. Text on the left side and images/illustrations on the right side. Why not do it like this?

**Comment by amraladdin** [comment]
Hey Gabriel,

What is nice about the template uploaded is that it accommodates a variety of slide layouts. So if you want to show text and image, then the two column layout is nice, yes, but what if you want to compare or show 4 different images of CEA results?

When you say, it doesn't have a good slide master. What do you mean? You don't like how it looks? Could you be more specific?
Regarding the numbering, header and footer, we could add those to the current template.

If there's a consensus to change the template altogether, we can do this, but we will need everyone's input here. @gabriel-happle @shanshanhsieh @JIMENOFONSECA @BhargavaKrishnaSreepathi @shizhongming @martin-mosteiro Please send your feedback here, and if you are suggesting edits, then please do them and then resend the edited PPT here.

**Comment by gabriel-happle** [comment]
Hi @amraladdin, @JIMENOFONSECA, @BhargavaKrishnaSreepathi and @martin-mosteiro 
Someone has to create a good power point master.
That's why @shanshanhsieh, @shizhongming and I sat together and created this suggestion directly on the Value Lab screen.
[CEA_Presentation_template-master.pptx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1938175/CEA_Presentation_template-master.pptx)
We propose to use the lower screens for logos and sources/bibliography.
I create two master slides so far:
- tow columns with two subtitles
- one column with subtitle on the left and one larger space on the right.

Let me know ASAP what other designs are needed.

**Comment by amraladdin** [comment]
Hi everyone @gabriel-happle @shizhongming @shanshanhsieh @BhargavaKrishnaSreepathi @JIMENOFONSECA @martin-mosteiro 
Thanks guys for your efforts. Here are my additions:
- I created sub-guides between the screens, so that text and images would have a margin between them. Fixed all master slides and added others accordingly.
- Increased font size of the Title to 16 pt.
- Reduced the logo sizes and centered them within the screen margins.
- Made an alternative with 4 images compared. We can use the same template for 3 images I guess.
[AMR_CEA_Presentation_template-master.pptx](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/1939065/AMR_CEA_Presentation_template-master.pptx)

I would like to ask you guys to:
- Check the edited template on the Value Lab screen and see if it works well.
- Edit and/or give feedback on the current template and upload accordingly.

**Comment by gabriel-happle** [comment]
Thanks @amraladdin I suggest we work with your template for now. The font sizes were actually taken from the official FCL template. Where everything is 14 pt.
The margins are a good idea I guess, but usually text boxes have "internal" margins, so it's kind of optional.

**Comment by amraladdin** [comment]
It's your template actually :) I just edited it a bit.

**Comment by amraladdin** [comment]
Should we close this issue?

**Comment by amraladdin** [comment]
UPDATE
--------
@JIMENOFONSECA @gabriel-happle @BhargavaKrishnaSreepathi @shanshanhsieh @shizhongming @martin-mosteiro For your PPT template presentation, please modify the master slide as follows:
- Reduce font size for the reference area (at the lower part of the slide) to 8pt instead of 9pt. Otherwise, some references take a big space and overlap with the below logos.
- In case of having one picture on the side (Check the image below), then align the reference in the middle of the image, as in the following image:

![image](https://user-images.githubusercontent.com/16256867/39585589-7accaf1c-4ef5-11e8-931d-1fb7c3304bdb.png)

**Comment by martin-mosteiro** [comment]
May I suggest another minor change?
I find all the footnotes a bit distracting as they are. So in my presentation I changed their color to gray (*) as in the picture below. I find it a bit less distracting/cluttered that way. Any opinions?

(*) I used the same shade of gray as in the "The 2018 executive course on Urban Energy Systems", based on @amraladdin's feedback on slide design every time I present slides!

**Comment by JIMENOFONSECA** [comment]
@amraladdin do you think you can present next Thursday from 3pm - 5-pm Singapore time. The idea is that you wakk us through your slides. no need to prepare a speech. The team will be there to give feedback.

**Comment by amraladdin** [comment]
@Martin, I definitely agree. Could you specify which greay color you're using from the PowerPoint color template? Maybe take a screenshot and post it here?

@Jimeno, of course! So that would be from 9-11 Zurich time. It's a holiday, so ill probably connect from home from my personal Skype account if that's ok.

**Comment by martin-mosteiro** [comment]
The HEX code is 898989. It's not one of the standard colors in my version of Powerpoint, but it's the one used in the text above in the slide.

**Comment by amraladdin** [comment]
You mean the RGB value? I used the following color... Let me know if this is what you meant or not.
R = 89
G = 89
B = 89
