### ISSUE TITLE
ArcGIS interface: Opening CEA toolbox takes a long time

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1319]
This is a minor issue and I'm not sure if anything can be done.
On my machine opening the ArcGIS toolbox (clicking on the `plus` symbol) takes 65 seconds.

I'm assigning this to you @daren-thomas with low priority and milestone M3

**Comment by daren-thomas** [comment]
@gabriel-happle yes, this is super annoying. i ran a profiler against it last week and pin-pointed the code to arcgis code, so... it seems our stuff runs fast.

I think we could speed it up a bit by dividing and conquering... instead of just one pyt, have multiple. but i'd rather not change something like that just before the course...

**Comment by gabriel-happle** [comment]
can this be closed @daren-thomas ?
