### ISSUE TITLE
ArcGIS interface: plotting of scenario comparison not interactive

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1321]
![image](https://user-images.githubusercontent.com/17002288/40051091-177f748c-586c-11e8-8097-a9eeac38f1bf.png)

Hi @daren-thomas 
In the current ArcGIS plotting interface I can only tick or untick scenario paths for comparison plots.
That means I have to follow that exact folder location and naming structure if I ever want to compare.
In this way it is not really useful/interactive.

**Comment by martin-mosteiro** [comment]
Just noticed the same issue: there is no way to "Add Value" in the first two "optional" sections, and the lists shown there do *not* depend on the scenario path given above.
![screen shot 2018-05-15 at 13 44 04](https://user-images.githubusercontent.com/18548065/40054784-4cf3f168-5846-11e8-933a-2e245034b694.png)

**Comment by daren-thomas** [comment]
@gabriel-happle, @JIMENOFONSECA  yes, it seems the wrong parameter type was used here. (ListParameter, instead of SubFoldersParameter like used in the scenario-plots).

Since the way the plots script is written (using a scenario instead of a project) I think SubFoldersParameter doesn't really work either. I'm testing to see if I can make the list editable.

**Comment by daren-thomas** [comment]
I ended up fixing it with a generalization of how the SubfoldersParameter works (the parent is now a folder with references substituted, instead of a link to a property itself). To test: 

- `cea install-toolbox` 
- run the plots tool
- changing the scenario folder will change the list of scenarios to choose from for comparison

NOTE: `cea install-toolbox --debug true` will install a `test.pyt` as well, that contains just the plots tool. a bit quicker to open. BUT: check with the `CityEnergyAnalyst.pyt`, as that is the one we need to test.
