### ISSUE TITLE
Plot tool doesn't work on ArcScene

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1346]
I tried to run the plot tool from ArcScene, and couldn't run the tool, as you can see in the following image:
![image](https://user-images.githubusercontent.com/16256867/40178234-37b2fcb2-59e1-11e8-9436-2ce9a7e82c20.png)

I'm using the latest CEA master edition, which was updated this morning.

I'm sorry @JIMENOFONSECA that I assigned you directly, but I believe this is an important and urgent issue. Can we fix this before the Test Run?

**Comment by martin-mosteiro** [comment]
Same thing happens on my computer.

**Comment by JIMENOFONSECA** [comment]
Hi guys, i am out of office. So no chance to help now. I suggest to ask daren who is fixing anywise the plotting tool.

On 17 May 2018, 20:56 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Same thing happens on my computer.

**Comment by amraladdin** [comment]
Hi @daren-thomas , could you please take a look at this issue and give us your feedback?

**Comment by ongbolie** [comment]
I have the same error as well.

**Comment by daren-thomas** [comment]
The reason seems to be, that the plotting tool is trying to show a list of building names in the scenario (as defined in the configuration file) and that that scenario doesn't exist on @amraladdin's computer. I will create a pull request that fixes this - e.g. just shows an empty building list when an invalid scenario is chosen. stay tuned.
