### ISSUE TITLE
Final Cooling demand = 0 | singapore case study testing for the test run

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1352]
After simulating one case study (i.e. RES_Low Density and CBD_Low Density)
Final demand results = 0 although the breakdown of the cooling demand results show differently. Please check the attached CSV file for the whole district and for one building.
@martin-mosteiro also has the same issue. Here's his analysis:
* Qcs is more than 0, while Qcsf = 0. Qcsf_ahu = 0, Qcsf_sru is much lower than 0, Qcsf_lat is more than 0.*

PS. Sorry for assigning you directly @gabriel-happle , but this is kind of an emergency.

[RES_LowDensity_demand.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2016944/RES_LowDensity_demand.zip)

![image](https://user-images.githubusercontent.com/16256867/40235631-27511348-5aab-11e8-8b37-a6e0faa4d919.png)

**Comment by martin-mosteiro** [comment]
Actually, git blame says it was @JIMENOFONSECA who made this change:
![screen shot 2018-05-18 at 18 27 05](https://user-images.githubusercontent.com/18548065/40246470-2660e08a-5ac9-11e8-8c28-cc33ade40cb6.png)

**Comment by JIMENOFONSECA** [comment]
This behavior is ok. Qcsf is zero when the supply systems in the building are chillers inside the building. Basically all qcsf converts into electricity due to the chiller inside the building.

If you want to see qcsf, you need to change the supply systems to a type like district cooling.

We did this to keep an scenario consistent with what is final cooling (at the exit of the building) and end use cooling (at the room level)

On 19 May 2018, 00:41 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Assigned #1352<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1352> to @JIMENOFONSECA<https://github.com/JIMENOFONSECA>.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Thanks for the answer, I figured that was the reason why.

However this change is inconsistent, because then only the cooling has been lumped with the rest of the electricity demands. Hot water is also provided by electrical boilers in the case study (supply system T4) but it's shown separately. So in reality the graph should then only show the demand for electricity for each building.

Secondly it seems kind of arbitrary to only do this for cooling. Most buildings usually get heating and hot water from the same source of final energy, so how should we handle this? Say, a Swiss building with an oil boiler for heating and hot water will then only have a demand for oil, since heating and hot water are produced in the building. How would this case be displayed in this graph?

I understand the reason for wanting to change that, but then this graph seems a lot less informative to me. Perhaps we should display end use energy demands in this graph (for analyzing the building demands) and final energy in a similar one (for analyzing supply systems).

**Comment by JIMENOFONSECA** [comment]
Good point. I agree that the the best is to show one diagram for final loads and another one for end-use demand.

We also need to upgrade the code to account for heating and hot water cases.

On 19 May 2018, 18:59 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Thanks for the answer, I figured that was the reason why.

However this change is inconsistent, because then only the cooling has been lumped with the rest of the electricity demands. Hot water is also provided by electrical boilers in the case study (supply system T4) but it's shown separately. So in reality the graph should then only show the demand for electricity for each building.

Secondly it seems kind of arbitrary to only do this for cooling. Most buildings usually get heating and hot water from the same source of final energy, so how should we handle this? Say, a Swiss building with an oil boiler for heating and hot water will then only have a demand for oil, since heating and hot water are produced in the building. How would this case be displayed in this graph?

I understand the reason for wanting to change that, but then this graph seems a lot less informative to me. Perhaps we should display end use energy demands in this graph (for analyzing the building demands) and final energy in a similar one (for analyzing supply systems).

**Comment by gabriel-happle** [comment]
what's the action plan @JIMENOFONSECA ?
Are we doing additional plots?

**Comment by martin-mosteiro** [comment]
Please check out issue #1365 along with this one.

**Comment by gabriel-happle** [comment]
I believe this can be closed @JIMENOFONSECA
