### ISSUE TITLE
Submit solar technology potential results for test run

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1367]
In order to do @shanshanhsieh's exercise during the test run, we will need to run the solar technology potential plots tool. In order to run the plots tool we currently need the potential for **all solar technologies** to have been run in advance. This is an issue in itself (#1354) but it won't be solved before the test run this week.

Solution: we will have the students run the potential for PV technology **PV1 only** and we will provide the rest of the results to them so they can run the plots tool. So we need the results of the solar technology potential calculation for every one of the scenarios. Fortunately, you've all run them as part of the scenario testing! So @BhargavaKrishnaSreepathi, @JIMENOFONSECA, @gabriel-happle, @shizhongming, @shanshanhsieh, @ongbolie, @roglen and @amraladdin please submit all your solar technology potential results by the evening of Tuesday May 22nd so we can spend Wednesday May 23rd hectically preparing the materials for the students for Thursday May 24th!

**Comment by ongbolie** [comment]
Hey Martin, here are the results for mix-low density!
[Potentials_Mix_Low.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2022599/Potentials_Mix_Low.zip)

**Comment by gabriel-happle** [comment]
@shanshanhsieh please list the parameters to run the simulations, so that it is consistent.
Thanks

**Comment by BhargavaKrishnaSreepathi** [comment]
Here are the results for 01_CBD_medium_density
[01_CBD_medium_density potentials.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2024814/01_CBD_medium_density.potentials.zip)

**Comment by BhargavaKrishnaSreepathi** [comment]
CBD_high_density scenario (Zhongming's Scenario)
[CBD_high_density potentials.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2025161/CBD_high_density.potentials.zip)

01_CBD_medium_density (Bhargav's Scenario)
[01_CBD_medium_density potentials.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2025165/01_CBD_medium_density.potentials.zip)

Do note that the solar potentials in these cases are zero in (CBD_high_Density) and does not have any potential for walls (01_CBD_medium_density). This is because of the threshold values we have in the config file. If during the lecture, you are noticing these values, do drive the perspective saying that the radiation is not sufficient to operate the technologies

**Comment by shanshanhsieh** [comment]
@martin-mosteiro  @amraladdin 
in several case studies, the outputs of solar technologies are zero, this is because the threshold is too high, and none of the surfaces are selected to install panels.

to keep all the case studies consistent, we still simulate all cases with the same threshold.
however, the plots are buggy when the total output is zero. this has been addressed in #1369 , and the PR is in reviewed now.

**Comment by roglen** [comment]
Same, sent the results to @martin-mosteiro per email since it's about 50 MB

**Comment by martin-mosteiro** [comment]
@roglen Haven't received them yet but I guess they're on their way :)

**Comment by roglen** [comment]
@martin-mosteiro  i sent it on slack in the end, outlook is buggy...

**Comment by gabriel-happle** [comment]
I'm not sure if I can finish.
Wanted to create them from ArcGIS, but apparently it can get stuck in PVT calculation!
Trying to finish from PyCharm now.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , @BhargavaKrishnaSreepathi , @roglen , @ongbolie , @gabriel-happle , @amraladdin , @martin-mosteiro 
please upload the results once you finish step 1-3 so i can check the results, thanks!

this is the folder to collect the results:
https://drive.google.com/drive/folders/13K0l5Iv0kMnPgkKdKEoT48QlWUX_tqjg?usp=sharing

**Comment by amraladdin** [comment]
Done.
"RES_Low Density" case study, steps 1-3 is uploaded.

**Comment by BhargavaKrishnaSreepathi** [comment]
Done. For both '01_CBD_medium_density' and 'CBD_high_density'

**Comment by JIMENOFONSECA** [comment]
Done for scenario 02

**Comment by shanshanhsieh** [comment]
@martin-mosteiro , the solar technology potentials are simulated with all 9 cases, and I ran all of them with the plots without an error. This means that, the files are ready for Friday!

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Excellent! Thanks so much for doing the testing - I was about to get into it, now I can focus on @amraladdin's presentation instead.
