### ISSUE TITLE
ArcGIS interface should update the config file

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1390]
Each time you select a new tool, the default scenario path from the config file is pre-selected. This means that each and every time you want to run a tool for a scenario, you have to select your scenario again. The config file should be updated each time you change something on ArcGIS.

**Comment by daren-thomas** [comment]
ah, @JIMENOFONSECA remember the cascading configuration files? they solved this problem (by introducing other issues, if i remember correctly).

i'm not sure what the best way to address this is...

**Comment by daren-thomas** [comment]
one issue: how to restore defaults from the `default.config`? i think we could add a `cea restore-default-config` script? OR, we could maybe... hm... have a checkbox at the top for restoring to default values. and then only for *that* tool? let's see if i can pull this off. check out branch 1390...

**Comment by JIMENOFONSECA** [comment]
I think that the best option will be a tool under datamanagement that restores defaults.

________________________________

**Comment by daren-thomas** [comment]
so. i'm creating a pull request that i'll merge too, because it solves a big pain for the users: when running any tool that uses the CLI (the `cea <script>` program) - including the ArcGIS interface, the settings used are saved to the config file for the next time you open the dialog. i think this makes a lot of sense. we can add the "restore defaults" tool to the datamangement (or utilities?) later if still required - deleting the user config file would achieve the same anyway.

**Comment by daren-thomas** [comment]
fixed in PR #1398
