### ISSUE TITLE
Recalculate radiation files for all case studies and test cases

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1436]
Recalculate all radiation files for all test cases and case studies with bugfix of #1432 and new `config` settings of #1435 

- zip file test in cea --- cea/tests/radiation_data
- all case studies of cea-reference-case repository

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle Why do you need this? can you actually run it in your machine?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA this refers to the data in the reference case repository. According to my understanding there is old/wrong radiation data stored.
I don't need this now. But everyone who is using that repository needs it. E.g., @Khayatian for Ecocampus.
I assigned you, because you have a fast machine (especially to rerun Ecocampus radiation). I thought we discussed this once in person.

**Comment by JIMENOFONSECA** [comment]
Now it is more clear. Yes I can help.

Btw we bought 2 more powerful machines Assigned to Bhargava and Zhongming, but they are meant for all the group, so in case you need them, just ask them to use it. You can also use mine when I do not need it. Just ask, cheers.


On 30 Aug 2018, 10:51 AM +0800, Gabriel Happle <notifications@github.com>, wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> this refers to the data in the reference case repository. According to my understanding there is old/wrong radiation data stored.
I don't need this now. But everyone who is using that repository needs it. E.g., @Khayatian<https://github.com/Khayatian> for Ecocampus.
I assigned you, because you have a fast machine (especially to rerun Ecocampus radiation). I thought we discussed this once in person.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle so I have files of more than 100MB and Github does not allow to upload them. They just do not host them. So there are these options.

1. We erase all the radiation files of all case studies. This could be a good practice as it is good that whoever uses a case study for the first time makes sure he/she produces results with the latest version of CEA.

2. Compress all file and upload them. This could be OK, but then every time somebody changes the code we have to do it again (which is more frequent than people using all the case studies),

I am more for 1. @gabriel-happle what is your opinion?

**Comment by gabriel-happle** [comment]
I also think option 1. is better.
We just have to make sure @Khayatian or whoever is working on large case studies has a way to obtain those files.

**Comment by JIMENOFONSECA** [comment]
I do not think so…I have still the cea-reference case blocked because of heavy files I wanted to upload. if you have a bit of time, I appreciate if you can erase it once and for all :-)

Kind regards,
Jimeno

_______________________

Dr. Jimeno A. Fonseca
Senior researcher & Project coordinator
Multi-scale energy systems for low-carbon cities
Singapore ETH-Centre

Product owner & Scrum master
City Energy Anlayst (CEA)<http://www.cityenergyanalyst.com>

Prof.h.c in modeling and simulation
Universidad Central de Colombia


On 4 Oct 2018, 2:25 PM +0800, Gabriel Happle <notifications@github.com>, wrote:

can this be closed @JIMENOFONSECA<https://github.com/JIMENOFONSECA> ?
Are the old radiation files, e.g., for ecocampus removed from the case study repository?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I made a PR in the reference case repository.
Closing this issue here now.
