### ISSUE TITLE
Create Map of CEA

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1536]
On branch 1519-optimization-plots.

So we are looking to project one configuration of buildings, plant, storage and networks. Like this:

![image](https://user-images.githubusercontent.com/8973186/41838513-313d6414-7893-11e8-8a93-357674272917.png)

**Comment by JIMENOFONSECA** [comment]
So far we have a created a placeholder for the function to do this. it is located in cea.plots.supply_system.main.py

Lines 857 to 863 create the thermal network and simulate it.
Line 867 will provide the data which is a path to the location of (it is a place holder now) 
1. the shapefile with information about buildings (whcih one is centralized and which one is decentralized. (similar to zone.shp)
2. A shapefile with the information about the nodes of the network and saying which one is the plant. (similar to netowrks/DC/nodes.shp)
3. A shapefile with the information about the edges of the network (their diameters) (similar to netowrks/DC/edges.shp)

![image](https://user-images.githubusercontent.com/8973186/41838552-4ddb9c12-7893-11e8-99fe-845f2bbdfad9.png)

**Comment by daren-thomas** [comment]
OK. so... I need to know:

- names of these Shapefiles
- what columns to use etc.

**Comment by JIMENOFONSECA** [comment]
For now, we need to use dummy files. we will create them and assign a locator later.

For now use the inputs of CEA:

1. use the file attached, paste it in building-geometry/. use column [Type]. to differentiate between centralized, decentralized and surrounding buildings.
2. Use networks/DC/nodes.shp and column [Type]. These will show where the plant/storage is.
3. Use networks/DC/edges.shp and column [Pipe_DN]. These will show the size of the network.

[district.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2132531/district.zip)

**Comment by JIMENOFONSECA** [comment]
[edges & nodes.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2132537/edges.nodes.zip)

**Comment by daren-thomas** [comment]
I have implemented a demo in 7c3fac19eacd4032a8c9b1d21b98f02ee172b040 (pushed to this branch)
The file `cea/plots/supply_system/demo_maps.py` creates an html file called `outputs/plots/demo/demo_maps.html` with three maps, one of the buildings, one of the nodes/edges and one of all three layers super-imposed.

Attached: a zip containing the output.

[demo_maps.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2133758/demo_maps.zip)

There is room for improvement here, but the mechanics are done - the rest is styling the html page. The file `cea/plots/supply_system/demo_maps.html` is a jinja2 template that gets rendered with the GeoJSON versions of the dataframes into javascript variables that can then be used with leaflet.js.

This way, we don't require any new libraries for the cea.

Next step would be for @JIMENOFONSECA to implement this into the calling interface (`cea.plots.supply_system.main.Plots#map_location_size_customers_energy_system`, `cea.plots.supply_system.map_chart.map_chart`) and add any other data necessary.

Plotly plots can be added as well if necessary by setting the output type to `div` instead of the default `html` and passing that into the template.
