### ISSUE TITLE
Correct documentation on LCA infrastructure

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1567]
A lot of information on the LCA infrastructure database is currently referenced as "from CEA". What does this mean? Because it sounds a bit like saying "I got the water in my bottle from my bottle of water". What is the actual source of the data?

![screen shot 2018-07-05 at 14 26 32](https://user-images.githubusercontent.com/18548065/42305858-793d771c-805f-11e8-8856-c79559d844a0.png)

**Comment by JIMENOFONSECA** [comment]
@ongbolie @gabriel-happle could we add the reference to the databases?

**Comment by ongbolie** [comment]
Hi all, I just double-checked and can update the reference now if everyone's okay with these:

1. References "from CEA" refer to the cost because they are not available on the Ecoinvent and KBOB database hence are calculated by CEA. 

2. Reference for **Electricity** PEN and CO2 supposed to be from

> ecoinvent 3.4 database - market for electricity, medium voltage - SG

3. Numbers of PEN and CO2 for **Solar** was discussed in one of our previous meetings, in which we agreed that solar is considered renewables hence should contribute 0 PEN and 0 CO2. @BhargavaKrishnaSreepathi suggested putting a very very small value equivalent to zero, hence 0.0001. Any ideas what reference should I put down?

On a side note, I noticed the reference KBOB 2019 is not correct, because the newest version of KBOB Ökobilanzdaten is 2009/1:2006 and the one that @JIMENOFONSECA used in CEA is KBOB 2009/1. They both have slightly different values. Should this also be corrected or is there actually a version of KBOB 2019 that i'm not aware of/available publicly?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle that would be a most welcome solution to the problem.

**Comment by JIMENOFONSECA** [comment]
@ongbolie yes, let's fix it to the latest version please.
