### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by SJ20** [architecture-building-systems/CityEnergyAnalyst#1610]
while running this program, 
(my_root) D:\CityEnergyAnalyst-master\CityEnergyAnalyst-master>cea install-toolbox

ran into this error (ref to screenshot attached)
![screenshot](https://user-images.githubusercontent.com/42861444/44901325-a8b55f80-ad39-11e8-9f10-643a46ac173c.jpg)

**Comment by daren-thomas** [comment]
Hello @SJ20,

This seems to be an issue that we just fixed in #1603. Can you please `git pull` and re-run the environment.yml?

Also, by the look of your screenshot, it looks like you might not be following the installation guide closely: https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html#installation

(try to create the `cea` conda environment following each step. if that doesn't help, we can do some more debugging for you)
