### ISSUE TITLE
Zurich Executive Course

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1612]

**Comment by JIMENOFONSECA** [comment]
Dear CEA developers:
@shanshanhsieh @martin-mosteiro @Khayatian @BhargavaKrishnaSreepathi @shizhongming @gabriel-happle @daren-thomas 

We have received 4 serious e-mails about people interested to attend to the CEA executive course in Zurich. I feel we need to start defining this.

Since the executive course is a necessary Milestone to drive the development of CEA, and our still only direct way to get 1-1 feedback about the use of CEA. I will opt to continue this practice irrespectively of the CEA Blog and the CEA interface.

I am planning to do a smaller version this time and take a higher load myself on teaching. I will nonetheless require one more person to come/or join me in/from Zurich (besides Daren for the software support part)

Do let me know who could volunteer by Monday next week to include your name into the program.

Do also let me know if you have any observation to make. The idea will be to start sending invitations by the end of next week.


1. DATES:
9th - 12th of September (Right after Cisbat conference)

2. ATTENDANCE:
15 maximum

3. PROGRAM
Day 1: Introductory lessons (building Systems and District systems).
Day 2: Parameterisation, solar radiation and demand calculation.
Day 3: Supply systems and optimisation. 
Day 4: Optional (half/full day) project day. We will ask people if they want it when they subscribe.

4. INSTRUCTORS
Jimeno A. Fonseca
To be defined
Daren Thomas

5. COSTS
the usual + discounts for academics and multiple applications.

@daren-thomas I appreciate if you can confirm availability of one computer room at ETH Zurich during those dates.

**Comment by JIMENOFONSECA** [comment]
Update:
@Khayatian is in :-)
@daren-thomas booked the room :-)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA actually, it was too far in advance. i did some calculations and it seems i might be able to book it today. so: still trying.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the room is booked!

**Comment by JIMENOFONSECA** [comment]
The course was cancelled
