### ISSUE TITLE
As a researcher, I want to calibrate my model using genetic algorithms

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1657]
The current calibration scripts in CEA are very time consuming. In order to do a quick(er) and simple(r) calibration, @JIMENOFONSECA suggested using a genetic algorithm. So I will be working on this with @BhargavaKrishnaSreepathi's coaching.

**Comment by JIMENOFONSECA** [comment]
Good idea, let’s however check some pervious work in the field. I have seen some research on urban simulation and calibration using optimization.

The important thing of using GA to keep in mind is that when eliminating individuals, make sure that they are created following the minimum, maximum posible variable for each variable.

I guess you can even create a strategy to calibrate multiple buildings at the same time.

____________


Dr. Jimeno A. Fonseca
Senior Researcher and Project Coordinator
Multi-Scale Energy Systems for Low-Carbon Cities (MuSES)
Future Cities Laboratory
Singapore ETH-Centre

Chair of Architecture and Building Systems
Institute of Technology in Architecture
ETH Zurich

Scientific Advisory Committee
Energy and Sustainability 2017
On 9 Oct 2018, 12:57 +0200, Martín Mosteiro-Romero <notifications@github.com>, wrote:

The current calibration scripts in CEA are very time consuming. In order to do a quick(er) and simple(r) calibration, @JIMENOFONSECA<https://github.com/JIMENOFONSECA> suggested using a genetic algorithm. So I will be working on this with @BhargavaKrishnaSreepathi<https://github.com/BhargavaKrishnaSreepathi>'s coaching.

**Comment by martin-mosteiro** [comment]
TODO: look at error domain falsification as potential alternative to Bayesian inference
