### ISSUE TITLE
As a Practitioner I would like to model the effect of trees on solar radiation

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1719]
Is it possible to take existing trees into account for the solar radiation analysis? If so, how should they be modeled?

**Comment by JIMENOFONSECA** [comment]
CAE is not specifically designed for this. However there are two ways to do it.

1. Create dummy buildings with Hs=0 that represente the trees. (Quite approximate).
2. Create a raster of the terrain that includes already the trees. (Highly computationally expensive).

I close the issue since, this is something we will not have in the near future.
