### ISSUE TITLE
As a researcher I want to connect shapefiles of thermal and electrical networks

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1745]
@BhargavaKrishnaSreepathi would you mind adding a description to the problem here, so also the files I will need to fix it? thanks!

**Comment by BhargavaKrishnaSreepathi** [comment]
In branch `i1600-electric-and-thermal-network-planning`, if you run `cea\concept_project\thermal_network_calculations.py` file, with the default settings, everything will run smoothly. What happens here is that the `streets.shp` file created by Zhongming is used by `cea\concept_project\network_layout_main.py` script. Now if you uncomment the line 31 and comment line 29 in the script, the `cea\concept_project\thermal_network_calculations.py` does not work. What is happening in this line is a `streets.shp` file created by `cea\concept_project\process_results.py` is being used instead of the file created by zhongming. This needs to be fixed

**Comment by BhargavaKrishnaSreepathi** [comment]
This issue turned out to be a non-issue, as I was looking at the wrong shape files and once the correct shape files were used, the problem automatically got fixed.
