### ISSUE TITLE
Buildings with COOLROOM usage should follow the temperature set point of the other uses

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1794]
This issue was discovered when creating a new mixed-use reference case for testing #1790 

While the COOLROOM is not actually part of the thermal model (`Hs=0` according to the archetypes) it _is_ setting the setpoint for the thermal zone. That is not desired behavior.

I wonder if it makes sense to include the COOLROOMS in single-thermal zone simulation at all, because they have set point temperatures for cooling but they don't _actually_ have a space cooling demand in CEA - their cooling is entirely assigned to refrigeration loads.

**Comment by daren-thomas** [comment]
@gabriel-happle, you have labeled this as "Should have". What do you think the priority of this is? Would removing COOLROOM as a building function help?

**Comment by gabriel-happle** [comment]
Hi @daren-thomas, I think @martin-mosteiro actually know more about this issue. It's his comment that I pasted as the description of the issue.
As I understand at the moment this is not very high priority, since we don't know anyone that is simulating a case with COOLROOM.
However, it should be easy to fix if someone has a bit of spare capacity.

**Comment by daren-thomas** [comment]
Could we add a test to schedules to make sure COOLROOM usage < 50%? Or treat similar to PARKING?

**Comment by gabriel-happle** [comment]
I don't think this is fixed @JIMENOFONSECA. I'm reopening it again to not forget about it.

**Comment by gabriel-happle** [comment]
The behavior that is not desired is, that the `COOLROOM` is deciding the set point temperature of -5­ deg for mixed-use buildings. This happens when `COOLROOM` is the `mainuse` of the building.

I'm assuming that the `COOLROOM` set point temperatures are kind of hypothetical and that the refrigeration load is met with the `Qcre_Wm2 = 8` internal loads. (see issue description).

I think an easy way to avoid the undesired behavior is, to treat `COOLROOM` in the same way as `PARKING` in the `data-helper` script, where the `mainuse` is determined.

**Comment by JIMENOFONSECA** [comment]
Yes and no.

On one hand the coolroom and server should not play a role in the schedules and internal loads of the building.

They should be considered as separate things from the building. Like if they had an adiabatic interface with the building. Which i sol to asume.

In the case the user creates a building that has only servers or only coolrooms, the building physics model should not run.

The internal temperature will be that of the server and the coolrooms combined.

Coolrooms and servers should be considered like process heat (but without affecting schedules and internal loads).

This could be a first step before someone makes a detail model to simulate these processes... what do you guys think?



_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 6 May 2019, 11:28 +0800, Gabriel Happle <notifications@github.com>, wrote:

The behavior that is not desired is, that the COOLROOM is deciding the set point temperature of -5­ deg for mixed-use buildings. This happens when COOLROOM is the mainuse of the building.

I'm assuming that the COOLROOM set point temperatures are kind of hypothetical and that the refrigeration load is met with the Qcre_Wm2 = 8 internal loads. (see issue description).

I think an easy way to avoid the undesired behavior is, to treat COOLROOM in the same way as PARKING in the data-helper script, where the mainuse is determined.

**Comment by gabriel-happle** [comment]
Treating COOLROOM like PARKING in determining `mainuse` in data-helper.
Discovered that refrigeration loads are not calculated due to missing schedule in COOLROOM occupancy database.
created #1932. This has to be fixed first to continue.

**Comment by gabriel-happle** [comment]
@daren-thomas I didn't find time to do this.
I will be back in July. Please move to next or next-next milestone.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle status? anyway I can help?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA that would be great if you have time!
There were other things that had to be done first, and the issue was not very high priority.
This issue is the following: 
- Coolroom setpoint temperatures in the construction properties are very low.
- set-point temperatures are determined by the `mainuse`
- if a building happens to be mixed with `mainuse` COOLROOM it gets conditioned to those low temperatures, however, the cooling load of coolrooms is already supplied by the internal load `Qcre_Wm2`
--> there should be a behavior similar to the `mainuse` determination like in `PARKING` where the `mainuse` is actually the second-ranking use.

I think the easiest way is just to modify the `mainuse` function in the `data-helper`.

Let me know if I should do it, or you are taking over.
