### ISSUE TITLE
Debug and Document Heating Coil temperature calculation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1797]
the `heating.coil.calc_heating_coil()` code is buggy and not documented.
Either the function has to be debugged and documented or a new function has to be created from scratch.

This issue is related to PR #1790

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you help @martin-mosteiro with this?

**Comment by martin-mosteiro** [comment]
I implemented the same code as for the cooling coil as suggested by Shanshan and it works - but I don't think that solves this issue, since the cooling coil calculation is not documented either!

@shanshanhsieh I presume the cooling coil calculation previously used the NTU method as in the heating coil case and was subsequently replaced by the current method. What is the advantage of the current method? And what’s the source? Thanks!

**Comment by martin-mosteiro** [comment]
@shanshanhsieh There is a constant declaration in `calc_cooling_coil`:
```
U_COOL = 450.0  # W/m2K for air cooled heat exchanger
```
Doesn't this belong in the corresponding `constants.py`? In fact, looking for such a constant I found the following in `technologies.constants`:
```
# Heat Exchangers
U_COOL = 2500.0  # W/m2K
U_HEAT = 2500.0  # W/m2K
```
I suppose these values are for a water-based heat exchanger? Shouldn't these constants have a more intuitive name, though (e.g. `U_COOL_HEX_WATER = 2500.0` and `U_COOL_HEX_AIR = 450.0` or something along those lines)?

**Comment by martin-mosteiro** [comment]
As discussed at the meeting today, I implemented the same calculation as for the cooling coil, since the same calculation should be applicable for the heating case as well (just inverting the "hot" and "cold" side in the calculation).

I assumed `U_HEAT = 450.0` is still valid as it appears to be a reasonable number.

I added these changes in #1769 since the issue was discovered there due to the new case study.
