### ISSUE TITLE
Commercial / Residential Reference Load Profiles (Electrical + Thermal) Europe

### ISSUE THREAD

**Issue by petkovevan** [architecture-building-systems/CityEnergyAnalyst#1815]
I am a PhD researcher at the Group for Sustainability & Technology at ETH Zurich working on a project regarding seasonal storage in different climate zones and district types. In the project, I am constructing synthetic district electrical + thermal load profiles (8760 hours) from commercial and residential profiles.

Using data from CEA would be highly beneficial to me, as it has a European focus using SIA norms (https://cityenergyanalyst.com/dynamic-demand-forcasting/). My question regards finding a database of reference buildings which you use in the EnergyPlus simulations. 

I would be keen to create a database of these (exported) reference building energy profiles (electrical + thermal, in a few different climate zones) to use for my project, and for others to do the same!  Does something like this exist from your end? Would be super cool and helpful.

**Background info on reference building profiles:** 

One of the best repositories for such reference building profiles is the US Commercial + Residential TMY3 profile databases ([described here](https://www.energy.gov/eere/buildings/commercial-reference-buildings) | [data here](https://openei.org/datasets/files/961/pub/)) which are CSV outputs from EnergyPlus. The US Department of Energy conducted this survey of reference building load profiles in 2005 (TMY3) which are geo-located to a climate zone ([climate zones described here](https://www.homerenergy.com/products/pro/docs/3.12/openei_load_profiles.html)).

**Comment by JIMENOFONSECA** [comment]
@petkovevan thanks for your quesiton. Just to clarify, we do not use any outputs from Energy Plus in our simulations. We have fully developed our own demand forecasting tool based on ISO standards.

You can definitely use the demand forecasting tool of CEA to forecast the load (8760 hours) of single or multiple buildings in a neighborhood.

Creating a database of prototypical load profiles will be indeed a great thing to do. This is something that we have never tried yet. Since the results you can obtained from CEA are geolocated, It might be interesting for you to create load profiles even in a city-by-city basis.

let us know how it goes!
