### ISSUE TITLE
Geometry generator does not generate courtyards!

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1831]
The geometry generator appears unable to process buildings with courtyards! Basically, these buildings seem to be imported as solid blocks with no empty space in the middle. See images below (the extruded shapefile is shown in pink on the left, the visualization from `geometry_generator.py` is in white on the right):
![oopsie](https://user-images.githubusercontent.com/18548065/54697416-d0311580-4b2d-11e9-9aad-ff1b8a3d5595.png)

@JIMENOFONSECA Has this always been the case? Do you have any idea what might be going on?

Thanks @prakharmehta95 & @DanielleGriego for pointing out the issue.

**Comment by JIMENOFONSECA** [comment]
This has to do with the level of simplification used in the Daysim engine. It might be too high for this case.

In order to change it, do the next, in the Daysim radiation configuration use:

zone-geometry = 1

and check the results, if it does not work try:

zone-geometry = 0

Check the results, if does not work, let me know.

Jimeno
On 20 Mar 2019, 11:39 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

The geometry generator appears unable to process buildings with courtyards! Basically, these buildings seem to be imported as solid blocks with no empty space in the middle. See images below (the extruded shapefile is shown in pink on the left, the visualization from geometry_generator.py is in white on the right):
[oopsie]<https://user-images.githubusercontent.com/18548065/54697416-d0311580-4b2d-11e9-9aad-ff1b8a3d5595.png>

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Has this always been the case? Do you have any idea what might be going on?

Thanks @prakharmehta95<https://github.com/prakharmehta95> for pointing out the issue.

**Comment by martin-mosteiro** [comment]
Thanks for the quick suggestion. The results with `zone_geometry = 1` are the same as before:
<img width="677" alt="Screen Shot 2019-03-21 at 07 58 08" src="https://user-images.githubusercontent.com/18548065/54737204-27c39580-4baf-11e9-8e8a-17f7b3915a07.png">

`zone_geometry = 0` leads to the following:
```
[...]
Generating geometry for building MPB8A
Generating geometry for building MPB8B
Generating geometry for building MPB1L

Process finished with exit code -1073741819 (0xC0000005)
```
(no geometry generated)

**Comment by martin-mosteiro** [comment]
This error message seems to be a problem with my installation, not with CEA, so I'll try to fix that next...

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro what happens if you comment the line in the code that does the simplification to the geometry of the zone? do you get the same results?

**Comment by martin-mosteiro** [comment]
```
Process finished with exit code -1073741819 (0xC0000005)
```
(as before)

**Comment by JIMENOFONSECA** [comment]
On the other hand, there is a way around to this, which we made for the cases of the WTP (see reference cases.

**Comment by JIMENOFONSECA** [comment]
but wait, I am asking Kianwee for help , who developed this in this issue: https://github.com/chenkianwee/py4design/issues/16

**Comment by martin-mosteiro** [comment]
Yeah, I figured that would be an option. Not ideal, but workable.

**Comment by JIMENOFONSECA** [comment]
If it is not urgent let’s wait for a week. maybe kianwee can help us to solve it

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 21 Mar 2019, 17:07 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Yeah, I figured that would be an option. Not ideal, but workable.

**Comment by martin-mosteiro** [comment]
Not urgent, I can use the workaround for the next round of results to be delivered and this issue does not seem to affect @prakharmehta95's project.

**Comment by prakharmehta95** [comment]
Actually it does affect my project as the output data becomes incorrect, but I am fine with waiting a week or two. Else I try the workaround.

**Comment by gabriel-happle** [comment]
Dear @prakharmehta95  ,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team

**Comment by JIMENOFONSECA** [comment]
@prakharmehta95 so we did not get any answers from the developers of this library used in CEA to create the geometries. We will have to do the workaround for now (see my comment above)

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA I agree we should work with the workaround for now, but I disagree that this issue should be closed. The issue persists, we just have to live with it for now. However this should be either (a) kept as an issue for future development, or (b) properly documented as a limitation of CEA (may become part of the geometry tutorial or something?) and then closed. However I don't think the issue being "known" solves the issue.

**Comment by JIMENOFONSECA** [comment]
Sure, we can keep it open. I was just taking a top decision of not investigating it further, since there are other more pressing things at the moment (especially in preparation for the Zurich executive course).

Unless somebody has the time and skills to solve this kind of problem, in the next six months, I would close it and leave it in the list of known issues (There is a link in our website to all known issues, including this). Known issues =: limitations.


On 5 Apr 2019, 5:35 AM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I agree we should work with the workaround for now, but I disagree that this issue should be closed. The issue persists, we just have to live with it for now. However this should be either (a) kept as an issue for future development, or (b) properly documented as a limitation of CEA (may become part of the geometry tutorial or something?) and then closed. However I don't think the issue being "known" solves the issue.

**Comment by martin-mosteiro** [comment]
Okay then, if it’s already in the limitations part we can close it.
