### ISSUE TITLE
CEA can only process case studies above sea level

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1853]
The `geometry_generator` includes the following in line 359:
```
 (y_index, x_index) = np.nonzero(a >= 0)
```
This means that only the values in the terrain file that are greater than 0 are considered. However, it's possible to have case studies below sea level, as @FionaCollins showed in the Almere case study.

Setting the minimum to some arbitrary value (e.g., the altitude of Jericho, the lowest city in the world at -258 m) unfortunately won't work, as the rest of the code depends on the values all being positive. So I see two solutions:
1. Make the code look for the lowest point in the terrain file and if it is lower than zero lift the entire terrain file by that amount (what @FionaCollins did for her project). PRO: easy fix. CON: it's a hack.
2. Rewrite the entire `geometry_generator` code to allow it to read in terrain files below sea level. PRO: it's the most consistent solution. CON: it'll require time and careful study to figure out if there even is an appropriate solution.

@JIMENOFONSECA Do you have an idea about this issue already?

**Comment by JIMENOFONSECA** [comment]
Fiona’s solution is the best since the behavior of daysim might me unpredictible in that regard....

Any chance of you /Fiona helping us to automate this in CEA?

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 1 Apr 2019, 20:47 +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Assigned #1853<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1853> to @JIMENOFONSECA<https://github.com/JIMENOFONSECA>.

**Comment by martin-mosteiro** [comment]
Can!

**Comment by martin-mosteiro** [comment]
Interestingly, I cannot replicate @FionaCollins's issue. When I run the `geometry_generator`, I simply get all buildings lying on a flat surface (i.e., the elevation appears to be simply ignored due to this `a >= 0` line).

![Screen Shot 2019-04-02 at 13 46 02](https://user-images.githubusercontent.com/18548065/55400352-f0a99880-554d-11e9-8227-f4983345fc7b.png)

**Comment by FionaCollins** [comment]
@martin-mosteiro, I tried that same again and you are right it also works for me the same way now. I am not exactly sure what happened there. I was stuck with this error message for quite some time:

![image](https://user-images.githubusercontent.com/46419981/55430415-5584e300-558e-11e9-8c55-a443eaebd924.png)

with this from the debugging 
![image](https://user-images.githubusercontent.com/46419981/55430490-8b29cc00-558e-11e9-99d8-8ddcbe67cc44.png)

After shifting to attempt to move the raster in ArcMap to directly implement a shift in CEA it seems to work. It might be an issue that the vertical shifting in ArcMap somehow also induced a horizontal shift and thus the zone and the terrain were in different locations..

But anyway, even better, right? :) 

However I think we should still consider implementing the automation of this shift because a flat surface as you describe it would not really be justified for a terrain that looks like this:

![image](https://user-images.githubusercontent.com/46419981/55430639-f1165380-558e-11e9-9221-5abb88ad0034.png)

**Comment by FionaCollins** [comment]
As I can't push my branch to the Git at the moment I will post a screenshot of the relevant code modifications here:
![image](https://user-images.githubusercontent.com/46419981/55431620-523f2680-5591-11e9-8fb2-3d45269c7eb5.png)

Just one line was added to shift the terrain up.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @FionaCollins this could be in principle one implementation. However, it would be good to include an if-else loop that does not move the elevation up all the time.

maybe you can do this by first calculating in the raster if there are negative values, between -150 and 0. and then moving the entire raster up as required.

It is important to not calculate this for neither all negative values nor all datasets. Raster sometimes use -9999 as a convention for Nodata.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA That was the plan. The question is whether lifting the entire case study is a better solution than just ignoring the altitude of all buildings that are below sea level. I will test both cases... soon.

**Comment by JIMENOFONSECA** [comment]
lifting all will be the best. The minimum elevation point should be 1 in the raster. Otherwise daysim will not work. It doe s not work with 0 elevation. We have another issue about that.
On 5 Apr 2019, 5:42 AM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> That was the plan. The question is whether lifting the entire case study is a better solution than just ignoring the altitude of all buildings that are below sea level. I will test both cases... soon.

**Comment by martin-mosteiro** [comment]
Great, I’ll lift the entire thing so the lowest point is at 1 m elevation then
