### ISSUE TITLE
add http://climate.onebuilding.org to documentation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1863]
http://climate.onebuilding.org is a repository of epw weather files for locations all over the world.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA @martin-mosteiro @shanshanhsieh @shizhongming 
Here are some updates about weather files that are of interest to all simulators/researchers:

When simulating radiation in Singapore, Malaysia, and Myanmar with weather files from the above-mentioned repository, I noticed too high yearly global horizontal irradiation (GHI) values. GHI was unrealistically high compared to measured and GHI, GHI on the energyplus.net weather files, and GHI shown on solar atlases, like e.g., https://globalsolaratlas.info/

I contacted the maintainers of this repository to make them aware of my findings. In the follow-up email conversation I learned the following things:

- Data on https://energyplus.net/weather is outdated. Files are 20 years old and based on data from 1982-1999. "Commercialization of sites since then does change cloud cover and solar availability"

-  http://climate.onebuilding.org previously used "a heuristic to come up with cloud cover based on relative humidity", leading to the files with too high radiation values

-  http://climate.onebuilding.org now "uses the cloud cover values included in the ISD data that we use for surface data", leading to files with quite low radiation values

- probably the modes of http://climate.onebuilding.org are not really appropriate for the tropics due to measured data availability issues that should be incorporated into the models

--------------------------------------------------------

This is how the data looked previously on http://climate.onebuilding.org:
 - GHI  2204 kWh/m²-yr
 - Direct Normal Solar Radiation (DNI)  1667 kWh/m²-yr
 - Diffuse Horizontal Solar Radiation (DHI)  971 kWh/m²-yr

This is how the data looks with the new model for cloud cover from  http://climate.onebuilding.org:
 - GHI 1488 kWh/m²-yr
 - DNI   452 kWh/m²-yr
 - DHI 1142 kWh/m²-yr

This is https://globalsolaratlas.info/ data:
- GHI 1692 kWh/m²-yr
- DNI 1002 kWh/m²-yr
- DHI 928 kWh/m²-yr

This is the 20 year old https://energyplus.net/weather file:
- GHI 1671 kWh/m²-yr
- DNI 688 kWh/m²-yr
- DHI 1146 kWh/m²-yr

This is measured data from the Changi weather station:
![image](https://user-images.githubusercontent.com/17002288/57348518-ed2ab200-7188-11e9-9699-5c86d8d5ed58.png)

--------------------------------------------------------

So, what's the conclusion?
I don't know.

**Comment by JIMENOFONSECA** [comment]
I am for trusting the guys of mete test in this matter….

Jimeno
On 8 May 2019, 12:06 PM +0800, Gabriel Happle <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> @martin-mosteiro<https://github.com/martin-mosteiro> @shanshanhsieh<https://github.com/shanshanhsieh> @shizhongming<https://github.com/shizhongming>
Here are some updates about weather files that are of interest to all simulators/researchers:

When simulating radiation in Singapore, Malaysia, and Myanmar with weather files from the above-mentioned repository, I noticed too high yearly global horizontal irradiation (GHI) values. GHI was unrealistically high compared to measured and GHI, GHI on the energyplus.net weather files, and GHI shown on solar atlases, like e.g., https://globalsolaratlas.info/

I contacted the maintainers of this repository to make them aware of my findings. In the follow-up email conversation I learned the following things:

  *   Data on https://energyplus.net/weather is outdated. Files are 20 years old and based on data from 1982-1999. "Commercialization of sites since then does change cloud cover and solar availability"

  *   http://climate.onebuilding.org previously used "a heuristic to come up with cloud cover based on relative humidity", leading to the files with too high radiation values

  *   http://climate.onebuilding.org now "uses the cloud cover values included in the ISD data that we use for surface data", leading to files with quite low radiation values

  *   probably the modes of http://climate.onebuilding.org are not really appropriate for the tropics due to measured data availability issues that should be incorporated into the models

________________________________

This is how the data looked previously on http://climate.onebuilding.org:

  *   GHI 2204 kWh/m²-yr
  *   Direct Normal Solar Radiation (DNI) 1667 kWh/m²-yr
  *   Diffuse Horizontal Solar Radiation (DHI) 971 kWh/m²-yr

This is how the data looks with the new model for cloud cover from http://climate.onebuilding.org:

  *   GHI 1488 kWh/m²-yr
  *   DNI 452 kWh/m²-yr
  *   DHI 1142 kWh/m²-yr

This is https://globalsolaratlas.info/ data:

  *   GHI 1692 kWh/m²-yr
  *   DNI 1002 kWh/m²-yr
  *   DHI 928 kWh/m²-yr

This is the 20 year old https://energyplus.net/weather file:

  *   GHI 1671 kWh/m²-yr
  *   DNI 688 kWh/m²-yr
  *   DHI 1146 kWh/m²-yr

This is measured data from the Changi weather station:
[image]<https://user-images.githubusercontent.com/17002288/57348518-ed2ab200-7188-11e9-9699-5c86d8d5ed58.png>

________________________________

So, what's the conclusion?
I don't know.

**Comment by gabriel-happle** [comment]
I agree with @JIMENOFONSECA, Meteonorm should be reliable. Unfortunately, it is not free.
