### ISSUE TITLE
Reload list of scenario-names when project folder is changed in the Dashboard

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#1866]
As a User, when I change the selected folder in the "Projects" dialog on the Dashboard (http://localhost:5050/project/show), I want the list of scenario-names to be updated to valid entries for that project.

Currently, the list from the previous folder is left until the dialog is saved. This is a bug.

**Comment by daren-thomas** [comment]
I will check to see if still relevant after landing page changes

**Comment by daren-thomas** [comment]
@reyery do you think this is still relevant? I think, after the work you've done on the project management blueprint, that we can maybe just close this?

**Comment by reyery** [comment]
@daren-thomas currently "Projects" can be accessed using the gear icon in the bottom left. We can probably close this issue already since we can already switch scenarios without using this page. However, I am curious regarding what we can do with the remaining settings. Do we still need them? We could move them to project management, then we can remove the gear icon thing. 

At the same time, maybe we can just remove the bar in the bottom left if we have no plans to do anything with the icons, so we can close #1911. I might just put the glossary search bar that I have in the top left to that bar. What do you think?

![Screenshot_2019-05-22 City Energy Analyst Project settings(1)](https://user-images.githubusercontent.com/34395415/58153158-fb0c2700-7ca0-11e9-80b9-8f972c482061.png)

**Comment by daren-thomas** [comment]
@reyery oh, so you moved the project page down there... i thought you just removed it...

there is an [issue somewhere](https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1925) about these:

![image](https://user-images.githubusercontent.com/2969564/58155668-9d61e580-7c74-11e9-860f-ccd91ff7b818.png)

I'm actually fine with removing this page entirely. I think the tools that use these parameters are sufficient for setting them.

**Comment by reyery** [comment]
@daren-thomas I am guessing I can go ahead and remove this page entirely to close this issue? The only concern left is the weather setting, which I feel is a separate unrelated issue.

**Comment by daren-thomas** [comment]
@reyery did you make progress on this?

**Comment by reyery** [comment]
@daren-thomas not yet. I'm just planning to remove it anyway.
