### ISSUE TITLE
Region parameter should not be passed to all scripts

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1871]
The 'region' parameter should just be used by the 'data helper method'. The later should also create the default databases in a scenario basis.

In this way, CEA will refer only to the databases that are inside each scenario to do any calculation. This makes more sense than passing the region parameter throughout all CEA. It is becoming something like the global variable parameter (avoid at all costs!!)

**Comment by daren-thomas** [comment]
That's a good plan! This would mean that the databases created by the data-helper are not stored in subdirectories (CH, SG, custom) as they are now, but instead just in the databases subfolder of the scenario, so that the inputlocator can find them without the region parameter!

**Comment by JIMENOFONSECA** [comment]
Exactly!, @gabriel-happle will give me a hand tomorrow afternoon, so we have this refactoring ready as soon as possible. This should also help to have the 'settings' part of the plots more clean...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I willll locate the databases in this directory ......'scenario'/inputs/techno-economics/archetypes etc. would that work?

Would the name 'techno-economics' differentiate these types of databases from let's say the 'building-properties' databases or the 'building-geometry' databases?

**Comment by daren-thomas** [comment]
so... remove the `databases` folder from scenarios? fine by me. i'm not sure about the term `techno-economics`. Is that a real word? also, if you're going to move the files around, they don't really have to all end up in the same folder - say, because before the idea was "databases", maybe each of the files could belong somewhere else? hm... just checked. i don't know. we could also just call it `{scenario}/inputs/archetypes`, `{scenario}/inputs/lifecycle` etc...

**Comment by daren-thomas** [comment]
also, please add a script, maybe to the `bin` folder that can convert an existing scenario to the new format.

**Comment by daren-thomas** [comment]
(this will also mess with @Jack-Hawthorne 's work on the input data documentation)
