### ISSUE TITLE
Remove/move flags related to district heating and cooling and electricity prices

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#1925]
There are some flags that are being used in the GENERAL part of the config file. Since these flags only applied to some scripts eg., thermal network or optimzation. I believe we need to move those variables to those scripts in the config file. @shanshanhsieh would you mind making these changes?

![image](https://user-images.githubusercontent.com/8973186/57054836-a260f400-6cc9-11e9-8ab0-b9408f857887.png)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, @shanshanhsieh is the issue, that they show up in the "Project Data" page? (i.e., are part of the [general] section of the config file?

Or should they be set separately for each tool? Maybe we could move them to a more general `[network]` section and have all those tools use that?

@reyery and I are in a discussion here: #1866 regarding the "Project Data" page. maybe the whole page can be removed as the workflow for switching projects / scenarios is now different entirely.

So... if we just remove the project data page, then it doesn't really matter too much where these flags are - they will show up in the parameter list for the tools due to the way `scripts.yml` works.

**Comment by JIMENOFONSECA** [comment]
Hi,

My quick thoughts on this,

Every tool should have individual options that apply for that tool. No dependencies, no hidden properties, not interrelated properties.

These flags should belong to the scrip where they are used and nowhere else.

No general sections please. That leads to scripts like the Global Variables script….



On 22 May 2019, 3:38 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA>, @shanshanhsieh<https://github.com/shanshanhsieh> is the issue, that they show up in the "Project Data" page? (i.e., are part of the [general] section of the config file?

Or should they be set separately for each tool? Maybe we could move them to a more general [network] section and have all those tools use that?

@reyery<https://github.com/reyery> and I are in a discussion here: #1866<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/1866> regarding the "Project Data" page. maybe the whole page can be removed as the workflow for switching projects / scenarios is now different entirely.

So... if we just remove the project data page, then it doesn't really matter too much where these flags are - they will show up in the parameter list for the tools due to the way scripts.yml works.

**Comment by shanshanhsieh** [comment]
just did a quick search, these flags are only used in the supply system optimization related scripts
so the section `[optimization]` is more appropriate, and that will be my plan for this issue

and yes, it is not necessary to show this flags in the "Project Data" page

**Comment by daren-thomas** [comment]
@JIMENOFONSECA one reason for doing it this way was, because scripts _do_ have dependencies. It _matters_ that you run the demand with the same weather file as the radiation script. And this way, the last setting used is automatically shown. I always thought there would be some other parameters for which this is true too - like whether we're using cooling or heating (or both?).

so, you guys, as domain experts: was this assumption wrong?

**Comment by JIMENOFONSECA** [comment]
So for the weather, this should be a scenario variable and be shown into the ‘project overview’ along with each scenario, so we avoid the problems of running demand and radiation with a different file

For the others, as Shanshan said, they are only used in one script. so they should be moved.

On 22 May 2019, 4:20 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> one reason for doing it this way was, because scripts do have dependencies. It matters that you run the demand with the same weather file as the radiation script. And this way, the last setting used is automatically shown. I always thought there would be some other parameters for which this is true too - like whether we're using cooling or heating (or both?).

so, you guys, as domain experts: was this assumption wrong?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA when we removed the "cascading configuration files" feature (remember?), the concept of a "scenario variable" was removed. that's what the cascade was all about. we don't have a place to store scenario information anymore.

**Comment by JIMENOFONSECA** [comment]
Well you can store it in the cache…or in a text file fo the scenario? In fact the weather should be part of the inputs folder right? maybe we should add a weather helper tool?


_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 22 May 2019, 5:22 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> when we removed the "cascading configuration files" feature (remember?), the concept of a "scenario variable" was removed. that's what the cascade was all about. we don't have a place to store scenario information anymore.
