### ISSUE TITLE
Empty results for buildings including COOLROOM and SERVERROOM

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1930]
Running reference-case-open. 'B01' is 25% COOLROOM, 'B07' is 50% SERVERROOM.

In the yearly results for B01:
- Qcre_sys_MWhyr, Qcre_sys0_kW = 0
- Qcre_MWhyr, Qcre0_kW = NaN
For B07:
- Qcdata_sys_MWhyr = 9357.107
- Qcdata_sys0_kW = 1068.163
- Qcdata_MWhyr, Qcdata0_kW = NaN

In the hourly results for B01:
- Qcre_sys_kWh, Qcre_kWh = 0 at every hour of the year
And for B07:
- Qcdata_sys_kWh = 1068.163 at every hour of the year
- Qcdata_kWh = 0 at every hour of the year

So refrigeration loads are not really being calculated, while for server rooms the "systems" energy demand is calculated, but the end use energy demand is not.

**Comment by martin-mosteiro** [comment]
The refrigeration loads 'Qcre_sys' are now fixed. However 'Qcdata' and 'Qcre' are still missing... because there is actually no function that calculates them. I am actually not even sure why we would ever need these, @JIMENOFONSECA?

**Comment by martin-mosteiro** [comment]
`Qcdata_kWh` and `Qcre_kWh` are not used anywhere else in the code, so removing them will not have any impact on the other results.

**Comment by JIMENOFONSECA** [comment]
Hi martin, we need to fix this. Qcdata is supposed to be used in the optimzation and supply systems in swtizerland. It is one strong vector of energy demand that can be used as waste heat.

I suggest:
1. consider COOLROOMS and SERVERROOMS as separate vectors of demand from the buildings. They do not influence the internal loads at all. they have a separate HVAC system.
2. make static that when a building has coolrooms and serverrooms, there will be HVAC systems for these buildings, which we will consider fixed (that is always the case).
3. we create for coolroom and servers a simplidfied model of thermal losses. We just asume a percentage of losses and that is all. no dynamic calculation for now.

I could help with the implementation only until friday, maybe you give it a try?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Thanks for the reply. So Qcdata (as opposed to Qcdata_sys) is indeed used in the optimization scripts?

Would researching and assigning a percentage of losses be a better solution than calculating the losses in a manner analogous to normal cooling systems? Since they have a separate system, would it be fair to implement non-recoverable distribution losses? Do they need emission losses as well?

**Comment by JIMENOFONSECA** [comment]
yes, I believe we use only non-recoverable losses.


_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

Chair of Architecure and Building Systems
ETH Zurich

On 6 May 2019, 3:50 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Thanks for the reply. So Qcdata (as opposed to Qcdata_sys) is indeed used in the optimization scripts?

Would researching and assigning a percentage of losses be a better solution than calculating the losses in a manner analogous to normal cooling systems? Since they have a separate system, would it be fair to implement non-recoverable distribution losses? Do they need emission losses as well?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, @martin-mosteiro could you update the story points information for this issue please?
