### ISSUE TITLE
Image for scenarios in project overview to make them more identifiable

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#1961]
Along with a short description, an image that represents each scenario in the project overview would make it easier for users to identify and differentiate them.

**Comment by reyery** [comment]
@JIMENOFONSECA Do you think we still need this? Since the rest said that the images would look almost the same among the scenarios, so it would not add much value. Should we change it to labels instead?

**Comment by JIMENOFONSECA** [comment]
Actually, we need the images.

In Cooling Singapore for example we are running all Singapore.

Each scenario is a different area of Singapore, so it will be good to have the image, or something that helps to intuitively recognise the area.

On 22 May 2019, 2:57 PM +0800, Reynold Mok <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Do you think we still need this? Since the rest said that the images would look almost the same among the scenarios, so it would not add much value. Should we change it to labels instead?
