### ISSUE TITLE
Error running demand script - BUG: demand cannot process `REFERENCE` added by zone-helper.

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2011]
Hi all,

I am Luis and took the executive course on CEA and now I am working with Jimeno in the Cooling Singapore project. I am testing some case studies across Singapore and facing some issues, so @JIMENOFONSECA  asked to update them here.

This one is related to running the demand code. Apparently it tries to call the occupancy_schedules and finds a problem.
@daren-thomas, Jimeno said that you might be able to help.

Link for the files can be found here (expires in one week): https://we.tl/t-aFuSTqZnao

**Comment by gabriel-happle** [comment]
I also took a look at this @lguilhermers 
I think the error is caused by your `occupancy.dbf` having some `REFERENCE` column/row.
The demand script can not process this currently.
You could do a workaround and delete this column from your files, e.g. with the dbf to excel and excel to dbf tools in CEA, while we fix this bug.
I'm also renaming the issue.

**Comment by reyery** [comment]
@lguilhermers @gabriel-happle can confirm that the error is caused by the introduction of the `REFERENCE` column into the `occupancy.dbf` file. I have already came up with a solution and will be merging it to master soon.

**Comment by reyery** [comment]
Just a heads up on another issue. Was able to proceed with the demand script with the code change however it encountered another error. Not sure what that means. B1033 is the one in yellow
```
Exception: Temperature in RC-Model of building B1033 out of bounds! First occured at timestep = 8040. The results were Tint = -22.3970084954, theta_c = -25.0814449023, theta_m = -38.2145461105, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.25 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.
```

![Screenshot (3)](https://user-images.githubusercontent.com/34395415/58448652-1791de80-813b-11e9-9227-72f92157287a.png)

**Comment by lguilhermers** [comment]
Hi Reynold,
I have found this issue before and discussed with Jimeno. It was always happening because OpenStreet Maps selected some very small geometries as buildings (probably some infrastructure construction in real life). I bypassed it by setting Hs = 0 to those buildings.
This building in yellow seems big enough to not cause the error, but maybe its geometry contributes to it.

**Comment by reyery** [comment]
@lguilhermers thanks for the insight! Will create a new issue for this and look into it.

**Comment by lguilhermers** [comment]
@reyery  one aditional note to your comments. the building B1033 is actually this one (circled in red), which is consistent with the small geometries issues I was having before. Probably a filter to remove small areas would happen a lot. Open Street Maps has a lot of those.
Thanks for the fix!
![image](https://user-images.githubusercontent.com/50981039/58526364-55593a80-8201-11e9-981f-36dd8556c5cc.png)

**Comment by JIMENOFONSECA** [comment]
Hi guys,

We added this column as part of the inputs from data of Open street maps. It run on master before I left without a problem…maybe something changed?

Best,
Jimeno

On 27 May 2019, 12:57 PM +0200, Gabriel Happle <notifications@github.com>, wrote:

I also took a look at this @lguilhermers<https://github.com/lguilhermers>
I think the error is caused by your occupancy.dbf having some REFERENCE column/row.
The demand script can not process this currently.
You could do a workaround and delete this column from your files, e.g. with the dbf to excel and excel to dbf tools in CEA, while we fix this bug.
I'm also renaming the issue.
