### ISSUE TITLE
Error when running district helper

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2013]
For this case study I am not being able to run the District Helper. the  error message  when running the code in PyCharm indicates some float NaN cannot be converted to integer

Case study file can be found here (expires in one week): https://we.tl/t-MO6L8LFobl

**Comment by reyery** [comment]
@lguilhermers I have found out that this error happened because the default `buffer` parameter that was set for the tool was too small and that it could not find any buildings within the range, which resulted in an empty list. 

You could trying increasing the buffer for now so that it finds some buildings within the area. 

In the meantime, I will find a way to handle that error, and maybe a way to provide a graphical interface to select the buildings in the surroundings, since this 'number guessing' way provides a bad experience for the users.

**Comment by daren-thomas** [comment]
![image](https://user-images.githubusercontent.com/2969564/58475313-e5d64300-814d-11e9-86be-a44b37ab4caf.png)

@reyery It seems this is not fixed by #2018 as I don't see an error message to explain what is going on.

**Comment by daren-thomas** [comment]
@reyery nevermind: i pushed a fix for that - it was an unrelated race condition regarding reading the output of the script in the dashboard. The error message shows up now. Thank you.

**Comment by lguilhermers** [comment]
@reyery , @daren-thomas 
I am facing another error related to district helper. This time I made sure that buildings were included within the range given, so I put different ranges up to 400m.

This is the error presented:
City Energy Analyst version 2.15
Running `cea district-helper` with the following parameters:
- general:scenario = C:\CEA\LCZv2\LCZ3_BrightonAve
  (default: C:\reference-case-open\baseline)
- district-helper:buffer = 400.0
  (default: 50.0)
- district-helper:height-ag = None
  (default: None)
- district-helper:floors-ag = None
  (default: None)
Warning! you have not indicated a height or number of floors above ground for the buildings, we are reverting to data stored in Open Street Maps (It might not be accurate at all),if we do not find data in OSM for a particular building, we get the median in the surroundings, if we do not get any data we assume 4 floors per building
Process Process-18:
Traceback (most recent call last):
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\worker.py", line 19, in run_script
    script(**kwargs)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 28, in script_runner
    script_module.main(config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\district_geometry_helper.py", line 245, in main
    geometry_extractor_osm(locator, config)
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\district_geometry_helper.py", line 224, in geometry_extractor_osm
    result = clean_attributes(district, buildings_height, buildings_floors, key="CEA")
  File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\datamanagement\district_geometry_helper.py", line 147, in clean_attributes
    zip([float(x) for x in data_osm_floors1], [float(x) for x in data_osm_floors2])]
ValueError: invalid literal for float(): 1,2,3

here is the file which generated the error: https://we.tl/t-x8zHGc9XNU

Thanks!

**Comment by reyery** [comment]
@lguilhermers what was the error message when running with default parameters i.e. `buffer: 50.0` because I was able to run it successfully with defaults.

On the other hand, running it with `buffer: 400.0` did give me the same error. That error is due to the open street maps data where one of the `building:levels`, namely `Brighton View` is given as `1,2,3` when it should have been a single value. We should probably handle this type of exceptions.

@JIMENOFONSECA how do you want to handle this kind of data? set it to 1? I am not sure how often this kind of data would appear, but I am thinking of doing a catch exception on the float castings and just set it to 1 (and maybe print a warning to just let the user know??). This would also most likely affect the `zone_helper` script, since it uses `building:levels` too.

```
addr:street                                              Brighton Ave
amenity                                                           NaN
building                                                   apartments
building:levels                                                 1,2,3
denomination                                                      NaN
geometry            POLYGON ((103.8729704 1.360682, 103.8728352 1....
name                                                    Brighton View
nodes               [3868523630, 3868523631, 3868523632, 386852363...
religion                                                          NaN
shop                                                              NaN
source                                                            NaN
REFERENCE                                              OSM - as it is
roof:levels                                                         1
```

![Screenshot_2019-06-12 Query Features OpenStreetMap](https://user-images.githubusercontent.com/34395415/59340240-29c56c80-8d38-11e9-894a-bf9927427202.png)

**Comment by reyery** [comment]
Creating a separate issue for this.

**Comment by lguilhermers** [comment]
@reyery  just to update you, using 50 meter worked for me as well. Before I had started from 100m, that's why I always got the error.
