### ISSUE TITLE
Error when running the Solar Radiation component

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2014]
This case study was not able to run the solar radiation. This error is indicated for one of the buildings (CEA1004):
_ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case_
I ran the terrain helper before and didn't identify nothing special about the building geometry that can be causing this.

Case study file is attached here (expires in one week): https://we.tl/t-DQOCzi1jdc

**Comment by gabriel-happle** [comment]
Hi @lguilhermers |
I took a look at your files.
![image](https://user-images.githubusercontent.com/17002288/58415902-81b27100-80b2-11e9-8c74-7990e06d476a.png)
![image](https://user-images.githubusercontent.com/17002288/58415979-b8888700-80b2-11e9-9b55-1bd7320d6e7e.png)

**Comment by gabriel-happle** [comment]
When I'm looking at your building geometry files, I see two columns I don't know.
One is empty and called `descriptio`, the other one is called `category` and usually has the value of `yes`.
Maybe @daren-thomas, @reyery or @JIMENOFONSECA know more.

**Comment by lguilhermers** [comment]
Another case where Daysim presented an error: https://we.tl/t-6U4KPYD08d
"ValueError: ERROR: this usually happens when buildings do not overlap with the terrain, try to check if this is the case" (for building CEA1099)

**Comment by reyery** [comment]
Found out the the error is most likely caused by a "rounding" error in the `terrain_helper` script.

Casting floats to integers drops the decimal places and might cause the terrain boundary (usually either the bottom or right side) to be too close to buildings thus throwing the error.

https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/65b8285cfac9bbc17c3e8687d448c15de54af335/cea/datamanagement/terrain_helper.py#L102-L103

Will be creating a fix and merging with master soon.

**Comment by lguilhermers** [comment]
Nice, thanks @reyery !

**Comment by lguilhermers** [comment]
@daren-thomas @reyery 
I pulled the last merge and still got error running daysim in those files. Should I re-run terrain helper to fix this issue on my side?

**Comment by reyery** [comment]
@lguilhermers yes, please rerun `terrain_helper` as the bug was fixed there.
