### ISSUE TITLE
Negative Temperatures in thermal-network simulation

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2015]
I have ran the 'thermal-network' simulation for 4 different space cooling scenarios, in all of them you can observe negative temperature values. The temperatures get especially low in the Plant node as shown in this time series for one of the scenarios:
![Supply_Temp_Plant_2](https://user-images.githubusercontent.com/26175926/58430475-ce457e80-80a9-11e9-9467-07d909fb5a0c.png)

If we look closer we can determine that the low temperatures appear in conncetion with a low demand and therefore very low massflows during simulation-nighttime:
![temperature_bug](https://user-images.githubusercontent.com/26175926/58430824-59734400-80ab-11e9-9c84-dd200bcbaa58.png)
in this table, the 'demand' column is in MWh and taken from the Aggregated_Demand_DC__Wh file and summed up over the hour.
The 'Supply_Temp_Plant temperature' is shwoing the temperature in °C of the plant node from the 'DC__T_Supply_K' output.
'massflow_plant_supply' shows the massflow of the pipe leading away from the plant node form file 'DC__MassFlow_kgs'.

The supply temperature also reaches negative values in the consumer nodes, as shown in this graph: 
![Supply_Temp_ETH_HG_2](https://user-images.githubusercontent.com/26175926/58430775-13b67b80-80ab-11e9-8a94-108db0488e82.png)

**Comment by shanshanhsieh** [comment]
Currently, we have variable flow and variable temperature (VT&VF) control model in cea.
This can be solved by implementing constant temperature, variable flow control (CT&VF).
![image](https://user-images.githubusercontent.com/16998305/58474303-4f217a80-817d-11e9-9dac-1751c20a5910.png)
the iteration in the lower green box is the VT & VF control in the current cea model
in order to implement CT & VF control, step ix. and x. should be modified

**Comment by shanshanhsieh** [comment]
@martin-mosteiro @emanuel030 
in branch `i2015`, i did the initial implementation:
1. avoid too low plant temperature: switch the control to 'CT_VF' when `t_plant_sup` is lower than 2C 
2. simulate network with constant supply temperature:  `t_plant_sup_0` is fixed in line 2602 in the script

i added some hints for you to understand the implementation, look out for `TODO[SH]` in `thermal_network.py`

please try it out for a few timesteps in your case and let me know how it works!

**Comment by shanshanhsieh** [comment]
@martin-mosteiro , is there a branch i can link this issue to?

**Comment by martin-mosteiro** [comment]
No, these results were produced using the master branch.
