### ISSUE TITLE
windows 2.16 installation error

### ISSUE THREAD

**Issue by SyrinxS** [architecture-building-systems/CityEnergyAnalyst#2114]
Completed the base installation and click on the CEA dashboard, it poped up: python.exe- cannot find ordinal: Ordinal 242 could not be located in the dynamic link library libiomp5md.dll
![1](https://user-images.githubusercontent.com/52148503/60396374-7a7bf880-9b73-11e9-8830-bbb2a95f4e7d.JPG)
Similar problem occurred when I tried v2.14 before (reported as issue #2089)
Thanks in advance for your kind help.

**Comment by SyrinxS** [comment]
v2.17 reports the same error

**Comment by reyery** [comment]
@SyrinxS hmm. Sorry it took a while, not being able to recreate the problem on our end makes it hard to find the source of the problem. Fortunately, after looking around, I think this is caused by some other software that you have installed on your computer.
See https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed.

However since the python that our installer uses is a detached conda environment, solutions provided above might not be relevant since conda will not recognise it as an environment. We would have to see what we can do in our installer to try to prevent this.

But if you are comfortable with setting up conda and installing from source, you could check out https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows-manual.html. Running it in its own conda environment should avoid all these issues.

**Comment by reyery** [comment]
Hey @SyrinxS just wanted to know if this issue has been resolved?

**Comment by reyery** [comment]
stale issue. closing
