### ISSUE TITLE
Individual weather settings for each scenario in the dashboard

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2117]
Currently the `weather` setting is based on the `cea.config` file which applies to all the scenarios in a project. Users that need different `weather` settings for each scenario would have to change the `config` file when switching scenarios.

Maybe for now a `.yml` could be used to store such settings in each scenario folder that the dashboard could read and apply when users open a new scenario.

**Comment by daren-thomas** [comment]
@reyery have you started on this yet? I could also give it a shot, you know...

**Comment by reyery** [comment]
@daren-thomas not yet. I'm currently busy with #2140. Go ahead if you want to :)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @reyery can we put this in your top priorities now?

This is kind of crucial feature we need for the interface of CEA. 

I believe that the weather should be part of the input files of the scenario and perhaps be part of the new project tool as well as a separate tool that helps people to indicate their scenario.

So, in essence, the weather can become part of the input locator. What are your thoughts on that?

**Comment by JIMENOFONSECA** [comment]
The Weather helper tool can ask as input"

1. Select the location of the weather file or select one weather file from CEA databases.

The output:

1.  A weather file (weather.epw) in the folder:  project/scenario/inputs/weather/

**Comment by reyery** [comment]
@reyery is going to look into this

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @reyery maybe somebody can address this now? I am kind of waiting for this feature for quite a long time now..

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'll do this. Steps:

- add a tool `cea weather` that locates the weather and saves it to the inputs folder as `inputs/weather.epw`
- check all references of `config.weather` and remove them.
- update project creation dialog to include weather selection

The user will be able to re-create all simulations of a scenario with the same weather file as previously used, since the `weather.epw` is still the same. The user will be able to figure out which weather was used by inspecting the `weather.epw` file (see the LOCATION header).
