### ISSUE TITLE
proof and edit the default.config documentation

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2143]
Proof read the default.config for spelling errors/grammar mistakes (help text etc...) and compile a list of missing information.

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA going through the default config thoroughly i noticed these params: 

```
[scenario-plots]
project = {general:scenario}/..
project.type = PathParameter
project.help = Path to the folder containing the scenarios

[benchmark-graphs]
project = {general:scenario}/..
project.type = PathParameter
project.help = Path to the folder containing the scenarios
```

are they necessary? the folder containing the scenarios is just the project dir, no?

```
[general]
project = C:/reference-case-open
project.type = PathParameter
project.help = Select the path of the project you're working on.
```

**Comment by daren-thomas** [comment]
@Jack-Hawthorne the `scenario-plots:project` and `benchmark-graphs:project` parameters were created long before the concept of `general:project` came about. So, it's a historical artifact. #2165 - I created a separate issue to deal with that.

Regarding `extract-reference-case` - the extracted reference-case is actually a whole project folder. The default destination could also be set to `{general:project}/..` _theoretically_. But it works like this too. Also, this will extract reference cases to the same folder that the user is already using for storing their projects. Maybe updating the help text is all that really needs to be done here.

**Comment by Jack-Hawthorne** [comment]
I've completed the first run through and have come up with the following things i wasn't 100% on:
```
[demand]
**original** 
predefined setpoints for every hour of the year is provided, which is further used to calculate demand of the building

**new**
predefined-hourly-setpoints.help = True if deterministic temperature set points for each hour of the year are considered to calculate the system demands.
```

```
[emissions]
**original**
year-to-calculate.help = The year to base the calculations on for embodied emissions.
**new**
year-to-calculate.help = The end year considered for the the embodied emission calculations.
```

```
[solar]
**original**

solar-window-solstice = 4
solar-window-solstice.type = IntegerParameter
solar-window-solstice.help = Desired hours of solar window on the solstice.          <----- windows as in building element or time period?
solar-window-solstice.category = Advanced
solar-window solstice ---> check
```

```
[retrofit-potential]
**original**
retrofit-target-year.help = the year to base calculations on       <- eh? like end year?

**new**
retrofit-target-year. help = The end year to calculate energy differentials.

**all of the thresholds ----> what unit kWh/m2?**
e.g. 

eui-hot-water-threshold = 50
eui-hot-water-threshold.type = RealParameter
eui-hot-water-threshold.nullable = true
eui-hot-water-threshold.help = End use intensity (EUI) hot-water loads threshold (leave blank to ignore this criteria).
eui-hot-water-threshold.category = end use intensity
```

```
[thermal-network]    and     [thermal-network-optimization]

**original**
minimum-edge-mass-flow.help = Minimum network allowed in network without mass flow iteration attempting to raise values in kg per s     <---- whaaaa?
```

```
[lake]
size = 0
size.type = IntegerParameter
size.help = Size of the lake.     <----- units?
```

```
[mpc-building]     all documentation missing
[mpc-district]     all documentation missing
```

**Comment by Jack-Hawthorne** [comment]
there are also some double ups:
- thermal-network and thermal-network-optimization are very very similar. not sure what the differences are in terms of function.
- network-type is used for a great deal of scripts and might be worth putting as a global param (apart from plots).

**Comment by martin-mosteiro** [comment]
@Jack-Hawthorne I'll try to answer as best as I can!
> ```
> [demand]
> **original** 
> predefined setpoints for every hour of the year is provided, which is further used to calculate demand of the building
> 
> **new**
> predefined-hourly-setpoints.help = True if deterministic temperature set points for each hour of the year are considered to calculate the system demands.
> ```
Sounds good, but this parameter was originally included by @BhargavaKrishnaSreepathi I believe, so I'm not too familiar with it.
> ```
> [emissions]
> **original**
> year-to-calculate.help = The year to base the calculations on for embodied emissions.
> **new**
> year-to-calculate.help = The end year considered for the the embodied emission calculations.
> ```
"The end year considered for the ~the~ embodied emission calculations."
Also, I'm not sure "end year" is a better term. The point is, if `year_to_calculate - year_built <= 60`, then embodied emissions are considered (namely, 1/60 of the embodied emissions). Same for `year_to_calculate - year_renovation`. If `year_to_calculate - year_built > 60`, then the embodied emissions are zero.
> ```
> [solar]
> **original**
> 
> solar-window-solstice = 4
> solar-window-solstice.type = IntegerParameter
> solar-window-solstice.help = Desired hours of solar window on the solstice.          <----- windows as in building element or time period?
> solar-window-solstice.category = Advanced
> solar-window solstice ---> check
> ```
Window as in time period.
> ```
> [retrofit-potential]
> **original**
> retrofit-target-year.help = the year to base calculations on       <- eh? like end year?
> 
> **new**
> retrofit-target-year. help = The end year to calculate energy differentials.
> 
> **all of the thresholds ----> what unit kWh/m2?**
> e.g. 
> 
> eui-hot-water-threshold = 50
> eui-hot-water-threshold.type = RealParameter
> eui-hot-water-threshold.nullable = true
> eui-hot-water-threshold.help = End use intensity (EUI) hot-water loads threshold (leave blank to ignore this criteria).
> eui-hot-water-threshold.category = end use intensity
> ```
I don't know enough about the retrofit potential tool. Since it's EUI, I'd assume it's kWh/m2 too.
> ```
> [thermal-network]    and     [thermal-network-optimization]
> 
> **original**
> minimum-edge-mass-flow.help = Minimum network allowed in network without mass flow iteration attempting to raise values in kg per s     <---- whaaaa?
> ```
Poorly worded. This parameter sets what the minimum mass flow rate in the network should be in order to avoid extremely small flow rates (and therefore huge losses) due to poorly-sized networks. So the procedure is (1) size the network, (2) run the simulation, (3) make sure the mass flow rate in all edges at all time periods is at least as big as the minimum flow rate, (4) if the flow rate of an edge is too small, make the diameter smaller and repeat from step 2. So maybe you could rephrase that as "Minimum mass flow rate allowed in the network (in kg/s). If the mass flow rate in any edge is below this value at any time period, the thermal network will be resized accordingly". Or something like that?
> ```
> [lake]
> size = 0
> size.type = IntegerParameter
> size.help = Size of the lake.     <----- units?
> ```
See issue #1574 ;) I haven't been working on this at all, so if you figure out which units should be used based on the lake potential script, then you'd be helping out doubly!
> ```
> [mpc-building]     all documentation missing
> [mpc-district]     all documentation missing
> ```
No idea about this.
> there are also some double ups:
> - thermal-network and thermal-network-optimization are very very similar. not sure what the differences are in terms of function.
> - network-type is used for a great deal of scripts and might be worth putting as a global param (apart from plots).
The double ups can become confusing (see #2041), I think there should be a way for these to be merged into one section.

**Comment by Jack-Hawthorne** [comment]
cheers @martin-mosteiro! 

i will make some issues for the [mpc-building] and [mpc-district] missing documentation.

otherwise, you know the difference between [solar] and [radiation-daysim]?

also the lake thing is completely lost on me. it just has a constant size which is divided by the number of hours in a year. it then writes the same result for each time step. odd.
