### ISSUE TITLE
Keep plots in their slots in map dashboard when deleting / adding plots

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#2163]
When deleting the plot next to the map (by clicking the X top-right), I expected that plot slot to be free again. instead, the plots all "moved up". I then went and tested adding a plot to an empty map dashboard, by selecting the last slot (lower-right position) and there the same behavior. 

Also, changing the order of the plots doesn't seem to be possible. Could this be added?

**Comment by reyery** [comment]
Yeah I did notice that too. But because the `Dashboard` class stores plots in an array, we can't insert a `Plot` into a specific index, unless we have other "dummy/empty" `Plot` objects to fill the array.

We could try storing an index/id property to `Plot` then have the `layout` property in `Dashboard` to also store the order of the plots e.g. `[None, None, 'PlotID1', None]`. Frontend will go through the array and render accordingly.

**Comment by JIMENOFONSECA** [comment]
@reyery any updates?
