### ISSUE TITLE
Demand Tool error: Temperature in RC-Model of building Z0434 out of bounds!

### ISSUE THREAD

**Issue by prakharmehta95** [architecture-building-systems/CityEnergyAnalyst#2221]
Hi, 

@martin-mosteiro 
@daren-thomas 
@JIMENOFONSECA 
While running the demand tool for my case study on Wiedikon Zurich, I receive an error like this one:

`Traceback (most recent call last):
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 222, in <module>
    main(cea.config.Configuration())
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 197, in main
    demand_calculation(locator=locator, config=config)
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 120, in demand_calculation
    format_output, config, write_detailed_output, debug)
  File "C:/Users/iA/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 174, in calc_demand_multiprocessing
    job.get(240)
  File "C:\Users\iA\Anaconda2\envs\cea2\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
Exception: Temperature in RC-Model of building Z0434 out of bounds! First occured at timestep = 6401. The results were Tint = 50.0576764318, theta_c = 49.9863734908, theta_m = 49.6409311139, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 0.9 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.
`

I received no such error for this building when I last ran this case study in January 2019. Other than updating CEA codes and formats of folders I have not changed anything.

Building Z0434 geometry:
floors_ag: 4
floors_bg: 2
height_ag: 18
height_bg: 9
Hs = 0.9

Building areas from demand tool output from earlier runs:
Af_m2 : 50448.46 
Aroof_m2 : 9330.859 
GFA_m2 : 56053.85

Building Z0434 internal loads:
Qs_Wp | 70.000000000000000
X_ghp | 90.000000000000000
Ea_Wm2 | 2.000000000000000 
El_Wm2 | 33.299999999999900
Epro_Wm2 | 0.000000000000000
Qcre_Wm2 | 0
Ed_Wm2 | 0.000000000000000
Vww_lpd | 2.000000000000000
Vw_lpd | 4.000000000000000 
Qhpro_Wm2 | 0.000000000000000

Here is the link to the folder so this error is reproducible: [https://drive.google.com/drive/folders/1mZqd1OI5rk6f_tYO8MHIKxkiBo_f-mg4?usp=sharing](url)
(made a section of the case study, and the radiation tool is already run for it. Kept parent files and databases as is)

Thanks for the help! :)

**Comment by gabriel-happle** [comment]
Since I wrote this error message, I will assign myself to this issue.
>  Other than updating CEA codes and formats of folders I have not changed anything.
That might already be the explanation of this error.

**Comment by prakharmehta95** [comment]
Hmmm...there are many other buildings in the scenario with similar size and Hs values - why do I get an error on this one only? What can I change to avoid the error? 
Hoping to run the demand tool soon as I need the results - worst case, how can I exclude this building from the calculation?

**Comment by gabriel-happle** [comment]
Actually, this warning was added in October 2018. It seems a bit strange that you haven't seen it before.
Maybe the archetypes database changed?
I will try to reproduce your error.
What you can do to exclude this building from the calculation is to pass a list containing all other building names to the config file: `[demand] buildings =B001, B002, etc,...`

**Comment by gabriel-happle** [comment]
Hi @prakharmehta95 I am able to reproduce this behavior.
This is not a bug. Your building has very high internal loads (more than 1.6 MW peak from lighting systems alone) and is probably very well insulated.
@martin-mosteiro encountered many similar issues with very new buildings in his case study.

Basically, this building does not require a heating system because of its construction properties.
What happens is this: The calculation starts at the end of the cooling season and your building's temperature stays between 25 - 30°C all the time. It can only "loose" energy via its ventilation systems, that are not always running. As soon as the heating season starts, a heat exchanger is activated to recover "heat losses" from the ventilation system. However, because your building is too hot anyway, this leads to overheating very quickly. Hence the message.

What you can try is to reduce the internal loads. Especially from the lights.
I tested a value of `El_Wm2 | 20.0` an the code runs through.

When you set `write-detailed-output = true` in the config, the tool will generate you an excel file with all the hourly outputs. incl. the indoor and building mass temperatures.
This is how your temperature looks with  `El_Wm2 | 20.0`. Still a bit high in autumn and spring.
![image](https://user-images.githubusercontent.com/17002288/62508500-71e5a480-b83a-11e9-9665-d0c7701fa8d4.png)

**Comment by martin-mosteiro** [comment]
Indeed, I have encountered similar issues in the past. In this particular case, the lighting density (33.3 W/m2) looks quite high – is that a retail building, I guess?
