### ISSUE TITLE
introduce supply systems map plot

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2237]
this is a map presenting the district heating, and cooling networks after optimization

**Comment by JIMENOFONSECA** [comment]
@reyery the first steps (data processing) are ready in branch i2237

**Comment by reyery** [comment]
@JIMENOFONSECA I have pushed some code for you to test before i proceed further. Right now it is able to toggle between layers (i.e. connected/disconnected buildings and network). Could you help me test if it also works when there is DC and DH since I do not have any example that has both networks. I do the 3d implementation of after this.
