### ISSUE TITLE
Optimization district cooling

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2249]
This issue aims to verify the contents of the routine for the optimization of cooling systems.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , here's a summary of the commits i made today:
1. change method in `calc_VCC` from using empirical operation curve to carnot efficiencies
2. refactor `calc_VCC` so the input is directly the cooling load (Qc) instead of flowrate (mdot)
3. solve #2227 by updating Cooling Tower calculation with minimum partload constraint
4. remove the max/min sizes for VCC and CT, only ACHs need these values for operation

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA , i've updated the power consumption of absorption chiller in this branch according to a manufacturer's catalog. changes can be found in branch `i2249`

**Comment by JIMENOFONSECA** [comment]
Thanks shanshan I merged that branch into my new branch (optimization-cooling) I should be able to send a PR. soon

**Comment by daren-thomas** [comment]
So... can we close this issue? @JIMENOFONSECA?

**Comment by JIMENOFONSECA** [comment]
yes
On 9 Oct 2019, 7:54 PM +0800, Daren Thomas <notifications@github.com>, wrote:

So... can we close this issue? @JIMENOFONSECA<https://github.com/JIMENOFONSECA>?
