### ISSUE TITLE
Documentation of code usage within construction_properties.xlsx

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2262]
construction_properties.xlsx:SUPPLY    vs.    construction_properties.xlsx:HVAC

Two questions:

1. What is the difference here between the codes here (e.g. 'type_hs') in the separate sheets
2. What is the source of the codes (e.g. 'T1') specific to each sheet (SUPPLY and HVAC) especially the `type_el` attribute (note: `type_el` is not defined in emissions_systems.xls). Are the sources different? If not why do we have a double up here.

Thanks!

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne sorry but I do not fully understand the question. Mind a few words more?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I don't understand it fully either, but I just checked the file and it _is_ a bit confusing:

We have a table "SUPPLY" and a table "HVAC" and both specify "type_hs", "type_cs" and "type_dhw". What is the difference between the two?

Also... maybe we can rename the types, so that they're easier to trace back: We use "TX" for all our types, when a "SUPPLY_hs_X" would add more clarity, no?

**Comment by Jack-Hawthorne** [comment]
> @JIMENOFONSECA I don't understand it fully either, but I just checked the file and it _is_ a bit confusing:
> 
> We have a table "SUPPLY" and a table "HVAC" and both specify "type_hs", "type_cs" and "type_dhw". What is the difference between the two?
> 
> Also... maybe we can rename the types, so that they're easier to trace back: We use "TX" for all our types, when a "SUPPLY_hs_X" would add more clarity, no?

Apologies, this is indeed the question! 
l also ask where are the codes (e.g. 'T1', 'T2' ... ) defined? I can find some in emissions_systems.xlsx (e.g. 'type_hs', 'type_cs' ...) , however, 'type_el' is not here. 

I also ask if the sources for the "SUPPLY" table and the "HVAC" table are different (i.e. not emissions_systems.xlsx)
