### ISSUE TITLE
Update of electrical_networks, thermal_networks and supply_systems (sheet: Piping) databases

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2331]
When reviewing the databases, I noticed that all these are databases are related, being "transmission systems". They are conduits for the transmission of thermal and electrical energy and could potentially be merged.

------------------------------------------
`electrical_networks.xlsx` issues

- According to jimeno, a great deal of the attributes in the `electrical_networks.xlsx` are not actually required currently:

https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2153#issuecomment-527283620

------------------------------------------
`thermal_networks.xlsx` issues

- this file contains some constants (sheet: MATERIAL PROPERTIES) which could be moved to the `constants.py` or centralised in a `materials.xlsx` database, which could contain other relevant materials (e.g. those pertaining to construction materials).

![image.png](https://images.zenhubusercontent.com/5ac64fc24b5806bc2bcdce4d/8c0448d6-38df-4081-a145-bc176f3dea4a)

------------------------------------------

`supply_systems.xlsx (sheet: Piping)` issues

- this database contains costing information for all the DN's in the `thermal_networks.xlsx` (why not merge?)

------------------------------------------

Proposed solution (feel free to comment):

- drop the unnecessary attributes in `electrical_networks.xlsx`
- move the `MATERIALS` from `thermal_networks.xlsx` to a centralised database named `materials.xlsx` or something similar
- hard code the bins (attributes: Diameter min & Diameter max) within the `supply_systems.xlsx (sheet: Piping)`. These could be easily ripped from the DN numbers themselves and may not have to be specified.
- merge the three databases into one named `transmission_systems.xlsx` containing the following:

NOTE: the primary keys are denoted by a grey fill colour.

![image.png](https://images.zenhubusercontent.com/5ac64fc24b5806bc2bcdce4d/873ea68d-1a48-430a-9f7f-17aab6c52581)

![image.png](https://images.zenhubusercontent.com/5ac64fc24b5806bc2bcdce4d/4a8fe0f7-be62-4a14-9db6-1e6d42c4243b)

@JIMENOFONSECA @daren-thomas  as always, feedback welcome!

**Comment by JIMENOFONSECA** [comment]
Hi @Jack-Hawthorne I think you did a very good job describing this issue. I know understand the critical problem you pointed out. thumbs up for that.

As for the solution:
1. Let's keep the electrical network parameters for now. Looking at which ones are used or not used, should be another issue, because it can take several days to figure it out and test that we d onot break the code.
2. The materials database is rather too small to become one on its own. It is strictly necessary only for the thermal network materials, so it would be good to keep ti close together
3. merging thermal and electrical networks, and materials properties tabs sounds good. probably the file can be called "distribution-technology-properties.xls" or "network-properties.xls"
4. this change will require to refactor several parts of the code "mainly everywhere the thermal_netoworks and electrical_netowork files are called"

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne we might be fixing all these issues (at least most of them) in the PR #2439

**Comment by Jack-Hawthorne** [comment]
@JIMENOFONSECA @daren-thomas this is great news! sorry i have been absent for most of the semester, i ended up having to take more credits than anticipated. it will be great to review the pr once merged
