### ISSUE TITLE
Update of emission_systems, supply_systems and LCA_infrastructure databases

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#2332]
Going through the databases, I noticed the emission_systems, supply_systems and LCA_infrastructure databases are all somehow related. Working with a CEA user, it was very confusing to pinpoint which parameters would impact which outcomes and how to modify these to suit their scenarios and research topics.

-----------------------------------

`emission_systems.xlsx` issues:

- the name of the file is misleading, as emission is highly associated with CO2.
- the `dhw`, `heating` and `cooling` sheets all have similar attributes (some redundancy)
- the attributes are difficult to read due to all the slight variations and multitude (e.g. the differences between dTcs_C	Tscs0_ahu_C	dTcs0_ahu_C	Tc_sup_air_ahu_C	Tscs0_aru_C	dTcs0_aru_C	Tc_sup_air_aru_C	Tscs0_scu_C	dTcs0_scu_C - for most sheets!)

------------------------------------

`supply_systems.xlsx` issues:

- little key errors (e.g. the attribute 'unit' is accidentally 'unit ' (in the 'TES' sheet) and 'assumption' becomes 'Assumptions' (in the 'FC' sheet)
- most of these contain the same attributes repeated throughout which relate to life cycle costs (there is some redundancy here)
- the tree data structure is not used well here - readability is limited due to number of sheets (this doesn't scale well)
- to understand some attributes you have to go into the documentation of the external methods, these probably don't have to be explicitly defined here by the user but can rather be inside the python modules (e.g. in the `PV` sheet: PV_a1, PV_a2 etc...)
- `Pricing` sheet is not very well defined and does not fit within the context of the `supply_systems.xlsx`

--------------------------------------------------------

`LCA_infrastructure.xlsx` issues:

- the `LCA_infrastructure.xlsx` contains `type_hs` and `type_cs` which differ from those defined by the `emission_systems.xlsx` which is super confusing.
- the file operates under very basic and separate assumptions which are not integrated with the systems information (e.g. what are the embodied emissions for various system components, how efficiently do the components operate, what is the primary energy source of the system etc...) 

-----------------------------------------------------------

Proposed solution (open for comments):

- merge all systems information into ONE file: `subsystems.xlsx` with the following sheets:
    - `supply_subsystems`
    - `exchange_subsystems`
    - `distribution subsystems`
    - `emission_subsystems`
    - `storage_subsystems`
    - `subsystems_costs`
- create a meta file, called `systems.xlsx`, which stitches together all the subsystem into the `type_hs` or `type_cs` which is used for `technical_systems.dbf`

I will in a later comment show some snips from the new excel for attribute details and how we can avoid some of the extra attributes by using `subcategories` (e.g. "AMOR" for amorphous silicon PVs).

@JIMENOFONSECA @daren-thomas @gabriel-happle  As always, open to feedback. Give me a bit more time until I can show you the attributes for each proposed sheet.

**Comment by JIMENOFONSECA** [comment]
@Jack-Hawthorne once again, thums up for the great description.

I see the issue is challenging, since some of the databases are used for only optimization while others are used for the technical_systems.dbf I suggest you meet with @gabriel-happle and @daren-thomas who are in Zurich until the end of this month and together devise a plan on how to put all these databases into the right shape.


1. As for the subsystems, If this is the way to go I would suggest to keep the supply_systems.xls name but arrange the tabs in the next way:
- GENERATION(this will be anything generating energy, from boilers to PV panels to chillers)
- STORAGE(this will be storage tanks )
- DISTRIBUTION(this will be the thermal and electrical network properties)
- EXCHANGE (HX heat exchanger and borehole?)
- ONE

Each tab should show technical properties, CO2 emission factors and cost properties>

2. I would change the name of emission_systems.xls to HVAC_systems.xls, that is what is inside there (Heating, ventilation and air-conditioning systems). 

That file can have the next tabs:
- HOTWATER (former dhw)
- HEATING (former heating)
- COOLING (former cooling)
- VENTILATION(former ventilation)
- CONTROLS (former controller)

3. i would change the name of LCA_infrastructure for all_in_one_supply_systems.xls. Basically this presents properties for combinations of generation, storage, distribution and exchange
