### ISSUE TITLE
Definitions for windows properties

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2347]
In inputs > technology > systems > envelope_systems.xls, it is not clear to me what F_F stands for. It is also missing in the glossary. Can someone please clarify (and probably add in the glossary as well)

On an additional note, G_win seems not straightforward to me that it refers to SHGC. In there a specific reason that "SHGC_win" is not used instead?
I guess using the most common terms in the variables can help to bring a more smooth experience to the users and avoid additional referencing to the glossary.

**Comment by JIMENOFONSECA** [comment]
So basically, the name G-win has to do with the European definition of the SHGC. here is a description of how both terms are the same. Since the engine of CEA for demand calculation is based on the ISO standard, we aim to maintain that nomenclature as much as possible.

I have implemented the explanation to both terms in the master branch and the glossary. It should work now.

F_F refers to the fraction of the window covered by the window's frame. It is used to calculate the effective solar radiation entering the space. It is part of the ISO standard 13790.
