### ISSUE TITLE
CEA 2.23 Radiation-Daysim Error

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2370]
![Radiation1](https://user-images.githubusercontent.com/29708612/66384057-b6bac280-e9c6-11e9-9ddb-cfaec098caca.jpg)
![Radiation2](https://user-images.githubusercontent.com/29708612/66384066-bb7f7680-e9c6-11e9-9eba-e787cdee0c71.jpg)
![Radiation3](https://user-images.githubusercontent.com/29708612/66384079-bfab9400-e9c6-11e9-81e9-28943ab12cbe.jpg)
![Python Viewer](https://user-images.githubusercontent.com/29708612/66384085-c33f1b00-e9c6-11e9-83f5-34f7b3ce17fb.jpg)

**Comment by daren-thomas** [comment]
@kerembeygo this is actually expected behavior - to avoid seeing visual representations of all the buildings in the Solar Radiation simulation, set the `debug` option to `False`. Otherwise, closing this window will open up the next one and so forth until all have been shown and the simulation will proceed as usual.
