### ISSUE TITLE
http://localhost:5050/tools/weather-helper ERROR

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2381]
![WH](https://user-images.githubusercontent.com/29708612/66715652-6bd9ea00-edce-11e9-9a2d-8e176990f8e9.jpg)

**Comment by JIMENOFONSECA** [comment]
@kerembeygo mind writing the steps you did to reproduce the error? incl. the CEA version you are using. thanks!

**Comment by kerembeygo** [comment]
I ran data helper tools in order.
![3](https://user-images.githubusercontent.com/29708612/66813574-ab731400-ef3d-11e9-9486-b95d609be191.jpg)

**Comment by kerembeygo** [comment]
![1](https://user-images.githubusercontent.com/29708612/66813640-ca71a600-ef3d-11e9-9c76-e605ed04be90.jpg)

**Comment by kerembeygo** [comment]
Error for weather-helper.
![2](https://user-images.githubusercontent.com/29708612/66813732-f5f49080-ef3d-11e9-97f4-5e94f0340710.jpg)

**Comment by kerembeygo** [comment]
CEA 2.23. I wanted to change epw file for PV analysis. How can I do that? By using weather-helper? There is no option in input editor.

**Comment by JIMENOFONSECA** [comment]
Alright..the problem is that we changed the weather files in the new branch.

To solve this problem:

1. Open the cea.config file (you should be able to find it in your desktop)
2. erase the "xxxxxxxxxxxxxxxx" contents of the next line

[weather-helper]
weather = "xxxxxxxxxxxxxxxx"

so ti should look like this:

[weather-helper]
weather =

3. restart CEA. It should work fine.

**Comment by kerembeygo** [comment]
Contents of my config file is already like this. I haven't made any changes.
![1](https://user-images.githubusercontent.com/29708612/66902580-906dd600-f009-11e9-9268-b6577f8438b1.jpg)

**Comment by kerembeygo** [comment]
When I run weather-helper command. 
![2](https://user-images.githubusercontent.com/29708612/66902772-e9d60500-f009-11e9-82e8-7756eebefb69.jpg)

**Comment by JIMENOFONSECA** [comment]
Hi Kerem,

We unfortunately cannot replicate the error.  One way to fix your problem is to:

1. Change the name of the weather file you want to use to “weather.epw”
2. Store this new file in the weather folder ….YOURPROJECT/YOURSCENARIO/inputs/weather/.

Let us know if this works.
We have launched a new version of CEA today. It might be that you do not find that error in there anymore.

We heard your suggestion and ordered all the tools as they should be used from now on.
On 16 Oct 2019, 4:42 PM +0800, kerembeygo <notifications@github.com>, wrote:

When I run weather-helper command.
[2]<https://user-images.githubusercontent.com/29708612/66902772-e9d60500-f009-11e9-82e8-7756eebefb69.jpg>
