### ISSUE TITLE
Shutting down does not kill all python processes

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2408]
1. run cea-GUI
2. run demand tool.
3. close cea after the tool starts
4. try to relaunch cea

It does not work. Some processes remain in the background of CEA and CEA cannot open again.

![image](https://user-images.githubusercontent.com/8973186/67478081-f56e9f00-f68d-11e9-8467-211d9ec07f8e.png)

**Comment by daren-thomas** [comment]
I'm able to reproduce this. A quick googling shows some ideas here: https://stackoverflow.com/questions/23434842/python-how-to-kill-child-processes-when-parent-dies/23587108

Since we know _when_ the process is shutting down (`/server/shutdown`) I think it could be as easy as collecting those `POpen` objects and `terminate()`ing them. I'll give it a shot.
