### ISSUE TITLE
Failure on starting from my own files

### ISSUE THREAD

**Issue by dowbh** [architecture-building-systems/CityEnergyAnalyst#2413]
I tried to do simulation on CEA for the buildings that are still under the design process. Therefore, I used ArcScene to build all the required data structures, i.e. all the data in the "input" folder in your example (reference-case-open). After I uploaded the data onto the CEA browser interface, an error popped up on my screen, shown below. I wonder is there any suggestions about how it might be resolved?

![Capture](https://user-images.githubusercontent.com/56314722/67530473-01e5fe00-f674-11e9-864b-e84025143fbd.JPG)

```
Traceback (most recent call last): 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app 
    response = self.full_dispatch_request() 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request 
    rv = self.handle_user_exception(e) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router 
    return original_handler(e) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router 
    return original_handler(e) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception 
    reraise(exc_type, exc_value, tb) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request     return self.view_functions[rule.endpoint](**req.view_args) 
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\inputs\routes.py", line 95, in route_get_building_properties 
    lat, lon = get_lat_lon_projected_shapefile(table_df) 
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\standardize_coordinates.py", line 64, in get_lat_lon_projected_shapefile 
    data = data.to_crs(get_geographic_coordinate_system()) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geodataframe.py", line 443, in to_crs 
    geom = df.geometry.to_crs(crs=crs, epsg=epsg) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\geopandas\geoseries.py", line 304, in to_crs 
    proj_in = pyproj.Proj(self.crs, preserve_units=True) 
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pyproj\__init__.py", line 358, in __new__ 
    return _proj.Proj.__new__(self, projstring) 
File "_proj.pyx", line 84, in _proj.Proj.__cinit__ (_proj.c:1170) 
    RuntimeError: no arguments in initialization list
```

**Comment by dowbh** [comment]
Step A.
Since the buildings are not existing buildings yet, I used the "zone helper" on CEA and cropped the extract same site where the buildings will be located, and then I used the "District helper", "Street helper", and "Data Helper" to generate some of the required data.    

Step B.
I drew the building footprints (in dwg.), put them into ArcScene (version 10.7), and created the data for the footprint (age, occupancy, height, etc.) in the format that CEA requests. I created a new scenario and copied the data generated in Step A (because the district and street are the same), and replaced the zone shapefile with the one I drew.

When I uploaded them onto CEA, I got the error. I am not quite sure what is "CEA project selection method" that you mentioned. I am also wondering if I am using ArcScene 10.7 instead of 10.6, would that be a problem (as the instruction requests below)?

![Capture](https://user-images.githubusercontent.com/56314722/67787881-8c40b000-fa2e-11e9-99a0-c312fb3697bd.JPG)

**Comment by dowbh** [comment]
Hey Daren,

Thanks for your reply!
I assigned the coordinate system of the zone shapefile as you suggested, and I put it at the same location where district, terrain, and street shapefiles are in ArcScene. 
It worked!

However, I am now getting a new error as below.
------------------------------------------------------------------------------------------------------

City Energy Analyst version 2.23
Running `cea demand` with the following parameters:
- general:scenario = C:\Your\Favorite\Folder\TEST\1029\outputs\1029\1029
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- demand:buildings = []
  (default: [])
- demand:loads-output = []
  (default: [])
- demand:massflows-output = []
  (default: [])
- demand:temperatures-output = []
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:format-output = csv
  (default: csv)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:use-stochastic-occupancy = False
  (default: False)
- demand:override-variables = False
  (default: False)
- demand:write-detailed-output = False
  (default: False)
- demand:predefined-hourly-setpoints = False
  (default: False)
- general:debug = False
  (default: False)
Running demand calculation for scenario C:\Your\Favorite\Folder\TEST\1029\outputs\1029\1029
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation with stochastic occupancy=False
read input files
done
Running demand calculation for all buildings in the zone
Using 7 CPU's
Traceback (most recent call last):
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 196, in main
    demand_calculation(locator=locator, config=config)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 120, in demand_calculation
    format_output, config, write_detailed_output, debug)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 174, in calc_demand_multiprocessing
    job.get(240)
  File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
Exception: Temperature in RC-Model of building B001 out of bounds! First occured at timestep = 8119. The results were Tint = inf, theta_c = inf, theta_m = inf, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 1.0 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0
-----------------------------------------------------------------------------------------------------------

Originally, the parameter "Hs" was set to 0.82 when I got the error saying that the value was too small. After I changed it into Hs = 1.0, the error keeps saying that the value is too small. Even if I tried to run simulations for another building, the errors I got are all the same. Other than that, the building geometry is what is it; settings of internal loads are attached below. Do you have any suggestions on how to deal with this problem?

![Capture0](https://user-images.githubusercontent.com/56314722/67991101-5568c680-fbf5-11e9-940e-450cba4425ad.JPG)

**Comment by JIMENOFONSECA** [comment]
Since we do not support ArcScene anymore, it is difficult to know how this performs. Does the case study show in our CEA GUI/Dashboard? That is a good indicator that the files are in the right coordinate system.

Maybe you can zip and pass your case study to us? that could help to check what the problem may be.


On 1 Nov 2019, 6:46 AM +0800, dowbh <notifications@github.com>, wrote:

Hey Daren,

Thanks for your reply!
I assigned the coordinate system of the zone shapefile as you suggested, and I put it at the same location where district, terrain, and street shapefiles are in ArcScene.
It worked!

However, I am now getting a new error as below.

City Energy Analyst version 2.23
Running cea demand with the following parameters:

  *   general:scenario = C:\Your\Favorite\Folder\TEST\1029\outputs\1029\1029
(default: {general:project}{general:scenario-name})
  *   general:multiprocessing = True
(default: True)
  *   general:number-of-cpus-to-keep-free = 1
(default: 1)
  *   demand:buildings = []
(default: [])
  *   demand:loads-output = []
(default: [])
  *   demand:massflows-output = []
(default: [])
  *   demand:temperatures-output = []
(default: [])
  *   demand:resolution-output = hourly
(default: hourly)
  *   demand:format-output = csv
(default: csv)
  *   demand:use-dynamic-infiltration-calculation = False
(default: False)
  *   demand:use-stochastic-occupancy = False
(default: False)
  *   demand:override-variables = False
(default: False)
  *   demand:write-detailed-output = False
(default: False)
  *   demand:predefined-hourly-setpoints = False
(default: False)
  *   general:debug = False
(default: False)
Running demand calculation for scenario C:\Your\Favorite\Folder\TEST\1029\outputs\1029\1029
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
Running demand calculation with stochastic occupancy=False
read input files
done
Running demand calculation for all buildings in the zone
Using 7 CPU's
Traceback (most recent call last):
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
run_job(config, job, server)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
script(config=config, **parameters)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in call
self._runner.call(*args, **kwargs)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
script_module.main(config)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 196, in main
demand_calculation(locator=locator, config=config)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 120, in demand_calculation
format_output, config, write_detailed_output, debug)
File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 174, in calc_demand_multiprocessing
job.get(240)
File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
raise self._value
Exception: Temperature in RC-Model of building B001 out of bounds! First occured at timestep = 8119. The results were Tint = inf, theta_c = inf, theta_m = inf, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs = 1.0 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0

________________________________

Originally, the parameter "Hs" was set to 0.82 when I got the error saying that the value was too small. After I changed it into Hs = 1.0, the error keeps saying that the value is too small. Even if I tried to run simulations for another building, the errors I got are all the same. Other than that, the building geometry is what is it; settings of internal loads are attached below. Do you have any suggestions on how to deal with this problem?

[Capture0]<https://user-images.githubusercontent.com/56314722/67991101-5568c680-fbf5-11e9-940e-450cba4425ad.JPG>

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it looks like @dowbh _is_ running this in the CEA GUI (see screenshot above). The error he is running into is the `Exception: Temperature in RC-Model of building B001 out of bounds! ` error. Do you maybe have some advice on how to deal with this?

**Comment by JIMENOFONSECA** [comment]
I think this has to do with the coordinate system. It may be happening that the files are in lat and lon coordinates, what would make the dimensions of the buildings extremely small.

I advise to do the next checks:
1. use QGIS or arcgis and see if the zone and district file map correctly
2. use QGIS or arcgis and see if th zone file (properties) has the coordinate system of UTM.

If some of the above is not working then the problem is with the input files.
Again, it is too hard to know without the data. I advise to send it for us to help.

best
On 4 Nov 2019, 8:22 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> it looks like @dowbh<https://github.com/dowbh> is running this in the CEA GUI (see screenshot above). The error he is running into is the Exception: Temperature in RC-Model of building B001 out of bounds! error. Do you maybe have some advice on how to deal with this?

**Comment by dowbh** [comment]
Attached please find the file we have been discussing on.

[inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3810591/inputs.zip)

**Comment by JIMENOFONSECA** [comment]
Alright we fixed it!.

Here is your scenario. We found a problem in your streets file and fixed it by rerunning the tool.
We also found a problem form our end and fixed it in the development environment.

To be able to run your work do the next:

1. Download the latest version of CEA and install the developer's version (tick the box of developer version).
2. Run the solar radiation, building schedules and demand forecasting tool.

[scenario (3).zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3834573/scenario.3.zip)

**Comment by dowbh** [comment]
I really appreciate your help. It works!
Now I am trying to assign the program types to the building geometry, and I have some questions on that.
 
First, on the "occupancy" tag, as shown in the attached image, I wonder what the numbers mean? Are they the number of floors of a certain program? Or are they occupancy density? 

![occupancy](https://user-images.githubusercontent.com/56314722/68706104-1ff0a100-0544-11ea-9621-2f2b4a5474a7.JPG)

Second, how do those numbers reflect on the multiple programs within a geometry? For example, if a geometry has 2-story retail on the ground floor and a 1-story office above it, how should I build the data of occupancy?

Third, for now, I assumed that the numbers I am asking represent the number of floors of a certain program, which makes the building distinguished from each other. And I ran "Building Schedules" after the occupancy was made. However, on the "Schedules" tag, all the schedules among different buildings look exactly the same. It is kind of weird to me. Does that mean that the occupancy data is not effecting on the schedule? For instance, I assumed that hotels may consume more water than office, but now they consume the same amount of water.

**Comment by JIMENOFONSECA** [comment]
Hi, so the numbers in the occupancy database are from 0.0 to 1.0 and represent ratios of gross floor area per type occupancy. The sum of every row should be equal to 1.0.

After changing the occupancy. You need to rerun the data helper, which will adapt the other databases accordingly.

This is to avoid that the changes you do building by building become overwritten sporadically once you chance the occupancy.

I hope this helps. Btw. The search button should be able to show what any variable means. Let us know if it does not work.
On 13 Nov 2019, 04:11 +0800, dowbh <notifications@github.com>, wrote:

I really appreciate your help. It works!
Now I am trying to assign the program types to the building geometry, and I have some questions on that.

First, on the "occupancy" tag, as shown in the attached image, I wonder what the numbers mean? Are they the number of floors of a certain program? Or are they occupancy density?

[occupancy]<https://user-images.githubusercontent.com/56314722/68706104-1ff0a100-0544-11ea-9621-2f2b4a5474a7.JPG>

Second, how do those numbers reflect on the multiple programs within a geometry? For example, if a geometry has 2-story retail on the ground floor and a 1-story office above it, how should I build the data of occupancy?

Third, for now, I assumed that the numbers I am asking represent the number of floors of a certain program, which makes the building distinguished from each other. And I ran "Building Schedules" after the occupancy was made. However, on the "Schedules" tag, all the schedules among different buildings look exactly the same. It is kind of weird to me. Does that mean that the occupancy data is not effecting on the schedule? For instance, I assumed that hotels may consume more water than office, but now they consume the same amount of water.

**Comment by dowbh** [comment]
I noticed that there is an overlay between the podium and the tower. Because when I built the building's footprint (in AutoCad and ArcScene), there was no parameter that allows me to control at what z-axis level the tower will stand. Is there a way to make the tower stand "on" the podium?

![Volume overlay](https://user-images.githubusercontent.com/56314722/68788669-b4b4d680-05f8-11ea-8f99-b14f11743d07.png)

**Comment by JIMENOFONSECA** [comment]
Not for the moment. CEA considers volumes attached to the terrain for now. What you can do is to change the height and number of floors of the podium tower so it goes until the desired height.

I hope this helps.
On 14 Nov 2019, 1:41 AM +0800, dowbh <notifications@github.com>, wrote:

I noticed that there is an overlay between the podium and the tower. Because when I built the building's footprint (in AutoCad and ArcScene), there was no parameter that allows me to control at what z-axis level the tower will stand. Is there a way to make the tower stand "on" the podium?

[Volume overlay]<https://user-images.githubusercontent.com/56314722/68788669-b4b4d680-05f8-11ea-8f99-b14f11743d07.png>

**Comment by dowbh** [comment]
So, based on what you suggest, the podium and the tower will have some portion overlapping with each other. Will that cause any problem?

**Comment by dowbh** [comment]
I successfully ran the simulation with the occupancy I want and with everything else set in default. But I got the "temperature out of bounds" error again after I changed the roof type from T4 to T6. I couldn't think of what might cause the problem because the simulation ran well before I changed the roof type. Can you take a look again for my input file? I attach it below.

Also, I am still wondering about the overlapping issue between the volumes of tower and podium. Do you have any suggestions?

![image](https://user-images.githubusercontent.com/56314722/69263782-da068f00-0b7a-11ea-9a7d-fc9a44f05dcf.png)

[inputs.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3870574/inputs.zip)

**Comment by JIMENOFONSECA** [comment]
Is there a T6 in the database of technology/systems/envelopesystems/roof ?
On 21 Nov 2019, 02:06 +0800, dowbh <notifications@github.com>, wrote:

I successfully ran the simulation with the occupancy I want and with everything else set in default. But I got the "temperature out of bounds" error again after I changed the roof type from T4 to T6. I couldn't think of what might cause the problem because the simulation ran well before I changed the roof type. Can you take a look again for my input file? I attach it below.

Also, I am still wondering about the overlapping issue between the volumes of tower and podium. Do you have any suggestions?

[image]<https://user-images.githubusercontent.com/56314722/69263782-da068f00-0b7a-11ea-9a7d-fc9a44f05dcf.png>

inputs.zip<https://github.com/architecture-building-systems/CityEnergyAnalyst/files/3870574/inputs.zip>

**Comment by dowbh** [comment]
I think T6 is "dark paint over plaster over concrete", if I was looking for a correct excel sheet.

![InkedSpread sheet_LI](https://user-images.githubusercontent.com/56314722/69359587-b7897a00-0c3d-11ea-82ea-08afad54b22c.jpg)

**Comment by JIMENOFONSECA** [comment]
@dowbh mind posting the error messagge you get?
@reyery this could be a cell validation error in the interface, mind checking after @dowbh puts the error message in? thanks

**Comment by dowbh** [comment]
Hello Jimeno and @reyery 

Here is the error message.

Clarifying the situation again, after I set the desired occupancy rate for all buildings, I ran the data helper -> solar radiation -> building schedules -> building energy demand. And then I changed the type_roof in the _architecture_ tag into my desired type T6, and I ran solar radiation ->building schedules -> building energy demand, after which I got the error attached below.

---------------------------------------------------------------------------------------------------------
City Energy Analyst version 2.25.1
Running `cea demand` with the following parameters:
- general:scenario = C:\Your\Favorite\Folder\TEST\1112\1112\Baseline WWR Roof
  (default: {general:project}\{general:scenario-name})
- general:multiprocessing = True
  (default: True)
- general:number-of-cpus-to-keep-free = 1
  (default: 1)
- general:debug = False
  (default: False)
- demand:buildings = []
  (default: [])
- demand:loads-output = []
  (default: [])
- demand:massflows-output = []
  (default: [])
- demand:temperatures-output = []
  (default: [])
- demand:resolution-output = hourly
  (default: hourly)
- demand:use-dynamic-infiltration-calculation = False
  (default: False)
- demand:override-variables = False
  (default: False)
- demand:predefined-hourly-setpoints = False
  (default: False)
Running demand calculation for scenario C:\Your\Favorite\Folder\TEST\1112\1112\Baseline WWR Roof
Running demand calculation with dynamic infiltration=False
Running demand calculation with multiprocessing=True
read input files
done
Running demand calculation for all buildings in the zone
Using 7 CPU's
Building No. 1 completed out of 16: B001
Building No. 2 completed out of 16: B002
Traceback (most recent call last):
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 146, in worker
    run_job(config, job, server)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\worker.py", line 108, in run_job
    script(config=config, **parameters)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 158, in main
    demand_calculation(locator=locator, config=config)
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\demand\demand_main.py", line 129, in demand_calculation
    repeat(debug, n))
  File "c:\users\dowbh\documents\cityenergyanalyst\cityenergyanalyst\cea\utilities\parallel.py", line 97, in wrapper
    result = map_result.get()
  File "C:\Users\dowbh\Documents\CityEnergyAnalyst\Dependencies\Python\lib\multiprocessing\pool.py", line 572, in get
    raise self._value
Exception: Temperature in RC-Model of building B004 out of bounds! First occured at timestep = 2895. The results were Tint = 50.0865286469, theta_c = 50.0521520514, theta_m = 49.8411126296, Check building geometry and internal loads! Building might be too small in size or architecture parameter Hs_ag = 0.9 might be too small for this geometry. Current bounds of range for RC-model temperatures are between -30.0 and 50.0.

**Comment by JIMENOFONSECA** [comment]
@dowbh I wonder if you are having still the same problem in the latest version of CEA? we attempted to fix this issue in later december.
