### ISSUE TITLE
error when opening CEA dashboard (related to solar radiation)

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2519]
Hi,

I am trying to open CEA after the latest merge but I get an error.
![image](https://user-images.githubusercontent.com/50981039/72234880-1bab3780-360a-11ea-933c-7f85f5b46c16.png)

**Comment by reyery** [comment]
@lguilhermers I think this problem might hae something to do with `.pyc` files. Do you have **PyCharm**? If you do, you could try to open `CityEnergyAnalyst` folder in **PyCharm** and right click **Clean Python Complied Files**

![image](https://user-images.githubusercontent.com/34395415/72237419-5b2b5100-3615-11ea-99b9-506f2a9eb443.png)

**Comment by lguilhermers** [comment]
@reyery thanks for the quick reply. I have PyCharms, tested your solution and it worked here. 
Any idea what might have caused this?

**Comment by reyery** [comment]
It happens because of how we list plot modules and how PyCharm compiles `.py` scripts to `.pyc`. Every time we add/remove new plot classes, sometimes `cea` still loads the old `.pyc` files as modules even though we might have edited/removed the associated `.py` file. 

Right now the only way to solve this issue is to do **Clean Python Complied Files** manually but we are currently working on a solution to prevent this issue from happening. https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2472

**Comment by lguilhermers** [comment]
I see... thanks for the additional information :)
