### ISSUE TITLE
Error using "Building Solar Radiation"

### ISSUE THREAD

**Issue by Loufafu** [architecture-building-systems/CityEnergyAnalyst#2555]
Hello,

I encountered a problem using the CEA tool. I don't manage to run "Building Solar Radiation". I put in the attached document the screenshot of the error.
Could you help us solving this problem?

Furthermore, is it possible to work with another person on the same case study? If yes, how?

Thank you in advance.

![Capture error radiation CEA](https://user-images.githubusercontent.com/60456091/74126235-62447f80-4c12-11ea-8051-fec9ffc47f23.JPG)

**Comment by JIMENOFONSECA** [comment]
@Loufafu check #1890 #1873 if any of those solutions work for you. @daren-thomas once again, a pontetial similar error taking place due to the location of the daysim binaries...

**Comment by reyery** [comment]
Hi @Loufafu, I am trying to fix this error and hope you can help me check something. Currently the known issues with is error message is that either the path of the daysim binaries/temp path has a whitespace i.e. `C:\User Name\Daysim` (which I do not think it is in your case) or that the `epw2wea` command has encountered an error, maybe due to an invalid `.epw` file.

Could you open __CEA Console__ and try to run it manually using this command with the path of the wea file:
`epw2wea {PATH_OF_WEA_FILE} test.wea`

It would greatly help with my debugging. Thanks!

**Comment by JIMENOFONSECA** [comment]
@Loufafu the new release includes some fixes to this. Maybe this works now.
