### ISSUE TITLE
Add migration script for users using older input databases

### ISSUE THREAD

**Issue by reyery** [architecture-building-systems/CityEnergyAnalyst#2584]

**Comment by daren-thomas** [comment]
@JIMENOFONSECA how far should we go with this?

One solution would be to:

- use database exported with database editor (or CH/SG)
- merge `age.dbf` and `occupancy.dbf` into a `typology.dbf`
- let the user select STANDARD (edit the database to include the STANDARD?)
- run archetypes-mapper

Problem: This undoes any manual changes the user made to the input tables. So:

- update the other `building-properties` tables
- this requires updating the database with new entries (for assemblies / feedstocks etc.)
- (archetypes would not need to be updated by the migration, as the user isn't expected to run archetypes-mapper again).

Anyway. I'm exploring this stuff currently in a branch (`2584-migration-script`) in a notebook. I'm unsure how much effort we should put into this. What do you think?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can we just assume that databases in v2.29.0 were left untouched? That way the migration script could map T0 -> HVAC_COOLING_AS0 etc. That would make so much stuff so much easier, but if a user had already changed the databases... well... then things would get really tricky to migrate. 

Unless they just have to select a standard and then run the `archetypes-mapper`. I kind of like that idea... (i managed to migrate to the `typology.dbf`)

**Comment by JIMENOFONSECA** [comment]
I think we can leave it to that point you mentioned.but the steps could be something like this. Mind the order.

1. We: The database is reinizialized to the new one
2. We: Occupancy and age file are transformed to typology. While at it, the standard is automatically selected based on the built age (check zone helper for how to do this) and the newly initialized database/archetypes/construction/standardefinition
3. The user: will have to run archetypes mapper.

I think that is what we should offer right now. We cannot offer more because there is not antmore a straight mapping between standards and the archetypes. We redid this completely.


On 4 Mar 2020, 22:57 +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> can we just assume that databases in v2.29.0 were left untouched? That way the migration script could map T0 -> HVAC_COOLING_AS0 etc. That would make so much stuff so much easier, but if a user had already changed the databases... well... then things would get really tricky to migrate.

Unless they just have to select a standard and then run the archetypes-mapper. I kind of like that idea... (i managed to migrate to the typology.dbf)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA that's about as far as I got yesterday - had to leave before creating a pull request. I'll get it ready by the end of today - after the SCRUM meeting.

**Comment by daren-thomas** [comment]
@reyery the GUI falsely states that the typology folder can be created with the `archetype-mapper` tool. It should actually be the `database-migrator` or the `zone-helper`, no?

Also, the PR for this feature (#2623) has a comment on a GUI integration idea - would you please check that out?
