### ISSUE TITLE
Setup Failure pip (ImportError:  cannot import name 'PackageFinder')

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2596]
![1](https://user-images.githubusercontent.com/29708612/75047791-72911000-54d8-11ea-8ef5-47ab2ad7a627.jpg)

**Comment by kerembeygo** [comment]
![1](https://user-images.githubusercontent.com/29708612/75047722-4f666080-54d8-11ea-938b-465c4d5ff871.jpg)

**Comment by reyery** [comment]
@daren-thomas I think this has something to do with pip version 20.0 https://github.com/pypa/pip/issues/7620 that is breaking installs. I remember you saying something about not updating pip in the installer for this version of CEA. Maybe we could update pip to version 20.0.2 in the installer, since its said to be fixed there.

**Comment by daren-thomas** [comment]
yes, let's check to see if that solves the problem. else, @kerembeygo I suggest uninstalling and re-installing CEA: That should leave you with the older, working pip version.

**Comment by daren-thomas** [comment]
@kerembeygo: I just checked. It really doesn't install either. I've recreated the setup and am testing it right now. I'm sorry for any inconvenience.

**Comment by daren-thomas** [comment]
@kerembeygo: I just tested. Uninstalling and reinstalling works. It seems that an earlier update to pip (if you're overwriting it) is the culprit for this error. Once it's broken, I'm not too sure how it could be fixed as the method to update pip requires running pip itself. So I'm afraid you'll have to uninstall and reinstall.
