### ISSUE TITLE
As a User, I would like to be able to create my envelope assemblies from components (materials)

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2636]
**Describe the feature you would like to have**
I would like to create my own envelope assemblies from materials. There can be a materials section in components tab. 

**Describe the end purpose of this feature**
So I can make a database for local materials and make my own assemblies (constructions).

**Describe the end-user of this feature**
A Researcher and a Practitioner.

**Provide Aditional information if possible**
![1](https://user-images.githubusercontent.com/29708612/76557692-13a63180-64ad-11ea-8679-81b56abcf755.jpg)
![2](https://user-images.githubusercontent.com/29708612/76518961-1f740280-6471-11ea-9a98-832010326eeb.jpg)
![3](https://user-images.githubusercontent.com/29708612/76518970-23a02000-6471-11ea-8360-ad9a4a0aedd7.jpg)

**Comment by JIMENOFONSECA** [comment]
@kerembeygo thanks for the feature idea. We have considered this possibility since the beginning of CEA, and resolved that the level of U-values and GHG factors per component makes a good compromise between detail, user-experience and accurracy. A higher level of detail (that of materials) could be interesting, yet time consuming to implement and maintain. Especially in regards to the data at the material level we will have to create.

This is definitely a good candidate for a research project, and a Pull-request with the databases and the code needed for this will be much appreciated. closing for now, feel free to reopen if anybody will like to engage and develop it.
