### ISSUE TITLE
As a Developer I would like a single point of reference for variables in CEA including unit tests

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2637]
**Describe the bug**
In repetitive occasions, the Glossary.csv and names.csv files have been found to contain either
1. the same information.
2. outdated information.
3. incomplete information.
This issue is becoming a quite RISKY technical debt of CEA, acknowledging that as of 31st of March we will have important changes in the team and a potential leak of knowledge aboout the variables in CEA.

Should this issue not be solved soon, nobody will be able to make sense about the more than 1000 variables inside CEA. This compromises the QUALITY of the software as a whole. Users cannot rely on the information that is presented. Users will not be able to 

**To Reproduce**
1. Go to the glossary bar which points to Glossary.csv. Practically half out of all results are either repetitive or the information is incomplete
2. Go and compare Glossary.csv with names.csv. So much of al the information is repetitive. Names.csv is the most important file (it contains all the information showed in the plots.

**Expected behaviour**
1. Database
One single file should be a reference to all variables names in CEA.
There should be only one variable (no repetitions).
It should be a csv file or yml file.
2. Unittest
The unitest should check that the unique variables file (merge of Glossary and Names) does not contain A. any repetition in the variable name. B. no TODOs or incomplete information.

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: Windows 10.0
 - Version of CEA v. 2.31.1

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I assign this to you so we tackle it right away.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I was planning on moving `glossary.csv` to `schemas.yml` today and adding unittests to test for "TODO" stuff and missing documentation in `schemas.yml`.

Regarding the `naming.csv` file: yes. some of the information _is_ duplicated but in a very subtle way: I tried to harmonize those two files a few sprints ago and failed. Mainly, because they are serving a different purpose:

- `glossary.csv` documents the fields in input and output files
- `naming.csv` documents the fields shown in the plots - which are not identical to the output files themselves, as they can be aggregations etc.

I'll try and come up with a good plan, but I admit I'm a bit stumped - do you have any good ideas?

**Comment by daren-thomas** [comment]
Also, note that some fields in the output files have the same names, but their context is different, so the description changes slightly.

**Comment by daren-thomas** [comment]
Here's an idea: move everything to schemas.yml, including the stuff in names.csv, but change how the plots look up those values (well, duh, if we remove naming.csv, they _have_ to use another method) to explicitly state the output file (locator method) as well as the field to look up. There might be some edge cases, I'll find them and figure something out. All the plots will be needed to be adjusted a bit and re-tested.

**Comment by JIMENOFONSECA** [comment]
Sounds good. Let’s merge everyting into one single schemas file. As long as we have only one source of information for the variables names, all should work.
On 13 Mar 2020, 16:58 +0800, Daren Thomas <notifications@github.com>, wrote:

Here's an idea: move everything to schemas.yml, including the stuff in names.csv, but change how the plots look up those values (well, duh, if we remove naming.csv, they have to use another method) to explicitly state the output file (locator method) as well as the field to look up. There might be some edge cases, I'll find them and figure something out. All the plots will be needed to be adjusted a bit and re-tested.

**Comment by daren-thomas** [comment]
Status update: I'm working on a branch (`2637-single-point-of-reference-for-variables`) that will address this. 

*Current progress:*

- started a set of unit tests for testing `schemas.yml`
  - go through `InputLocator` methds to make sure all are defined in `schemas.yml`
  - (this led to a lot of old code being found / removed / cleaned up)
  - (found some bugs and created issues for them)
  - needed to create `cea-doc schema --locator-method get_zone_geometry` to produce "stubs" for missing keys in `schemas.yml` - side effect is some stats for columns (`pd.Series.describe()`)
- added a test for `cea test --workflow slow` (on merge to master) to create all the plots. found some bugs doing so.

*Next steps* (after I can continue, see issue #2649):

- copy descriptions and other data from `glossary.csv` to `schemas.yml`
- add to unit tests: make sure each field is described
- (what to do with "Unnamed: 0" columns? can we not just remove them?)
- add to unit tests: no "TODO" in description
- remove `glossary.csv` and replace that with `schemas.yml` data
- update plots to use `schemas.yml` (add `plot_label` property?) instead of naming.csv
  - this could maybe be done by adding a `plots` field to a column with `label` and `color`. idk.
