### ISSUE TITLE
differences in outputs after migration

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2665]
**Describe the bug**
I have ran the same case study with v2.29 and 2.32 to understand the differences in the migration. I will need to translate several old cases to new ones at some point and would like their demand to match given the same inputs. @JIMENOFONSECA helped me to go through the database and we spotted some differences (in void-decks, walls and shading). He addressed those in the branch 'issues-migration', but I still see differences.

There are differences in solar radiation, but even if I just copy the old solar radiation and run demand, it gives a difference. Would be great if someone could provide insights on what else could be causing those issues. 

**To Reproduce**
You can find the files from a small test case attached (similar differences were caused in another test as well): https://we.tl/t-pOOBI5jPoo 

**Expected behaviour**
I expect that v2.29 and v2.32 are able to give same solar radiation and demand results. If there are changes in the input, ideally I would like to know which ones and be able to revert them to the same as v2.29.

**Screenshots**
![image](https://user-images.githubusercontent.com/50981039/77495974-e1b9a580-6e84-11ea-8b4d-92151a37c623.png)

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA you are using [2.29 and 2.32]

**Comment by lguilhermers** [comment]
update: I checked occupancy and config files and they are the same. My guess is that there is something in the internal calculations (for both solar radiation and demand) that generate those differences. Due to that, the versions aren't really compatible (meaning results from v2.29 won't be reproduced by v2.32 even if the same inputs are applied). Would be great to have a confirmation about that before I proceed with additional simulations.

**Comment by reyery** [comment]
It's interesting that radiation results are now different since we did not change anything regarding calculations. From what I understand radiation script depends on the **zone and surrounding geometries, weather, terrain and building architecture (mainly envelope)**. 
 
Looking at `envelope_systems` from v2.29 and `ENVELOPE` from v2.32 which are used to map the building architecture, there seems to be some minor difference in the `WINDOW` sheet on my side.

`F_F` seem to be different in both versions, **0.1** for v2.29 and **0.2** for v2.32

![image](https://user-images.githubusercontent.com/34395415/77814647-e92fb780-70ed-11ea-8a97-7e1574f2e279.png)

As for differences in demand, if radiation results are the same, it still depends on, **ENVELOPE(database), HVAC(database), building supply, comfort, internal loads, schedules and occupancy**.  I have checked HVAC and there does not seem to be any difference. I have not really looked at the differences of the other files since I am going the assume that they should be the same, so unless there are changes in calculation that I am not aware, I'm still not too sure why there is any difference for demand and will investigate further.

**Comment by lguilhermers** [comment]
Hi Ray,

Thank you for spotting this. I will try to change those window as per the old version and see if the results match at this time.
For the demand case, would be good to know if it is a change in the database (that I can revert to original version if needed) or change in calculations (and why/how they happen if that is the case).
If you want to replicate the demand difference yourself, I may suggest you run any study on v.29 (or take the one I sent here) and try to run on 2.32 keeping the results from radiation and running the tools required only for demand. This is what I did for the case  _v2.32 (with solar radiation from v.29)_.
