### ISSUE TITLE
0 temperature in time-series should be presented differently

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#267]
Now we represent a system in 'off' with a temperature equal to 0. this is convenient as we do not mix text with float or integer in a same vector. However, there is not such a thing as zero temperature in the system so we should think on a better way to represent it in general.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, I kind of have to guess what you mean here... So here is what I assume:

- you have found a case where a state variable in the simulation is not known and that is currently represented by a zero `0`
- might have been from an `np.zeros(HOURS_IN_YEAR)` initialization
- you would prefer to have a value outside of the domain of possible values for temperatures (in this case)

Since I am also assuming that the variable is a real of some sorts (`float`, `double`, whatever) then the value to use should probably be `NaN`, "Not A Number".

If you specify where this happened, we can fix it. Do we need to update all the initializers?

**Comment by JIMENOFONSECA** [comment]
NaN i believe would not be an alternative as ArcGIS will fail to read it when we want to represent it in a temporal scale. We will also have trouble on summing up vectors with NAN right?

**Comment by daren-thomas** [comment]
We could just test that and see. We really need to specify where this is happening. What variables are we talking about? Why do they not have a value? What does not having a value mean? Only then can we actually have a meaningful discussion.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle @daren-thomas i suggest to close this issue if it is not as important as other issues

**Comment by daren-thomas** [comment]
@gabriel-happle what do you think?

**Comment by gabriel-happle** [comment]
I still think it's important. we should just come up with a strategy or guideline and start working according to it from now on. But in general I still think we should avoid zero in cases where we actually mean "no data".

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle it has been a year. I suggest we close the issue if there is no strategy and things work across the full stack of tools.
