### ISSUE TITLE
Fix to network layout known error

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#2786]
**Describe the bug**
in connection to #2782 and #2785 it would be good to implement a solution to the known issue of the streets file.

the problem is that the network layout will fail for some files for other not. 

we know this has to do with the parameter of SHAPEFILE_PRECISION.
what we do not know is what the value of that parameter is.
We know it can be from 6 to 15.

My suggestion is to make the script try again to run the network layout if it finds an error when precision is 6. then do it again for precision = 7 and so on.

**To Reproduce**
1. extract streets file
2. run network layout

**Expected behaviour**
I would have expected that the script worked

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA: CEA 3.0

**Comment by daren-thomas** [comment]
@emanuel030 @JIMENOFONSECA can you please provide a link to the inputs that don't work for reproducing the error :)

**Comment by emanuel030** [comment]
@daren-thomas here you go https://we.tl/t-wQXQMjMBHc.
in inputs/networks I have stored the street files created by the street-helper as well as modified street shapes which are working and called 'streets_working'.

@jimenofonseca I am not sure about the adjustment of SHAPEFILE_PRECISION being the solution to this problem since I always had to change the streets.shp manually as well. So after the increase of SHAPEFILE_PRECISION to 15, I still got the error message for ~30% of my case studies. For those case studies I went into ArcMap and used the 'Feature to Line' tool and had to use a tolerance of 30 meters. Maybe some part of the code can replace this manual 'simplification'?
