### ISSUE TITLE
Reduce the number of buildings per chunk in DAYSIM

### ISSUE THREAD

**Issue by eap23** [architecture-building-systems/CityEnergyAnalyst#2787]
**Describe the bug**
When running the _Building Solar radiation_ simulation on my model I receive the error:
```
File "c:\users\<user name>\documents\cityenergyanalyst\cityenergyanalyst\cea\resources\radiation_daysim\daysim_main.py", line 194, in isolation_daysim
    raise ValueError('You are sending more than 50000 sensors at the same time, this '
ValueError: You are sending more than 50000 sensors at the same time, this will eventually crash a daysim instance. To solve it, please reconfigure the radiation tool. Just reduce the number of buildings per chunk and try again

Traceback (most recent call last):
  File "hblib_85c9f079_0d3b_4581_bda4_c5e9ea2d4893", line 160, in SolveInstance
  File "cea_scripts", line 45, in radiation
  File "cea_runner", line 74, in run
Exception: Tool did not run successfully
```

**To Reproduce**
1. Create a `zone.shp` file with 98 buildings where the largest building is about 9.000 sqm and the smallest around 500 sqm. The site area is some 180.000 sqm.
2. Create a `surroundings.shp` file with 1 building with about 1.500 sqm
3. Run the _Building Solar radiation_ simulation
4. Check for the error message described above

**Expected behaviour**
The _Building Solar radiation_ simulation runs through successfully managing the

> buildings per chunk

automatically regarding the size of the zone and surroundings model.

**Screenshots**
n/a

**Hardware (please complete the following information):**
 - Windows 10 Enterprise 64-Bit
 - Version of CEA is from `Setup_CityEnergyAnalyst_3.4.0.exe`
 - Intel i7 9750H 2.60GHz
 - 32 GB RAM

**Comment by eap23** [comment]
Where am I supposed to
> Just reduce the number of buildings per chunk and try again
with CEA?

**Comment by reyery** [comment]
Hi @eap23, thanks for reporting this issue. To reduce the number of buildings per chuck, you could change it under the **Advanced** settings of the radiation script if you are using the GUI. Let me know if that works for you.

![image](https://user-images.githubusercontent.com/34395415/85983269-c7f6a400-ba19-11ea-838d-742ff87af947.png)

**Comment by shanshanhsieh** [comment]
this issue could be fixed with #2794, please check again when this PR is merged

**Comment by eap23** [comment]
Hi @reyery,

thanks for your suggestion! It worked setting parameter `n-buildings-in-chunk` to 30 in my case.

Is there a way of determining an appropriate value for this parameter other than trial and error?
Or put it different - what is the numeric relationship between the parameter `n-buildings-in-chunk` and the number of sensors in _DAYSIM_?

Thanks!

**Comment by reyery** [comment]
Right now we have not found an exact way to determine the right value for `n-buildings-in-chunk` based on the user inputs since we were not able to accurately pinpoint the factors that might affect it, so we put a **50000** boundary for the number of sensors, which has been rather effective. 

This is mainly due to a bug/limitation of the current release of Daysim, where we found out that high number of senors, and sometimes a large scene geometry with many vertices, could result in `oconv` of Daysim throwing an error. (something related to memory, not a hardware issue since it would still happen even if the computer has more than enough system memory)

However, as mentioned above, we are currently working on https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2794 where we try to compile Daysim manually from their master branch, as that memory issue is supposedly fixed there. 

Unfortunately as of now, trial and error is the only way to get around this.

**Comment by eap23** [comment]
Thanks, @reyery for clarification!
