### ISSUE TITLE
High energy potential for PVT panels

### ISSUE THREAD

**Issue by AlexJew** [architecture-building-systems/CityEnergyAnalyst#2791]
**Describe the bug**
Hello, I was wondering if it was really possible to obtain such high values for energy generation with PVT panels compared to other solar technologies? 

These are the results I have obtained from my case when comparing the potential for the building stock. "Existing" and "Future" refer to existing buildings and future buildings in the neighbourhood (they'll occupy an empty space in the centre of the neighbourhood), while "Electricity" and "Heat" refer to the supplied energy vector type. 

![image](https://user-images.githubusercontent.com/32110882/85792970-3858a900-b72c-11ea-9bc0-3081a23c94f5.png)

Maybe it would be good to compared with other test cases to check if the same phenomenon happens?

**Hardware (please complete the following information):**
 - OS and version: Windows 10
 - Version of CEA: 3.4

**Comment by daren-thomas** [comment]
@shanshanhsieh would you mind checking this issue please?

**Comment by shanshanhsieh** [comment]
Hi @AlexJew,

The quick answer is that the input temperature of PVT is very different from SC.
Therefore, it is possible to have higher thermal output from PVT.
You might want to check if the thermal outputs (temperature level) from PVT is a useful resource in your case, otherwise, don't include it in your report.

In the CEA supply system optimization, we use these outputs from different solar technologies to evaluate which technology to install. 
The thermal output from PVT are used to (a) supply domestic hot water (b) feed to DH networks (c) send to seasonal storage. If the option of using PVT as an energy supply technology does not outperform other technologies (e.g. SC), it will not be installed. 

Another possible use of this thermal output is to supply floor heating, unfortunately, we have not yet established that option in the CEA supply system optimization.

We also encourage you to develop your customized functionality by developing your own [plug-ins for CEA](https://daren-thomas.github.io/cea-plugins-part-1/) : )
