### ISSUE TITLE
no sensor data (.json) to run photovoltaic.py

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2804]
When running the photovoltaic module, the following error appears: 
![photovoltaic need json](https://user-images.githubusercontent.com/26175926/87583264-4471ce00-c70e-11ea-8389-2ba3d8361df5.png)

Looking into the error, the script is reading a path to a json file. However, as I see it, with the option in the radiation script to turn the 'write-sensor-data' option off, the json files are no longer output.
![json path photovoltaic](https://user-images.githubusercontent.com/26175926/87583403-797e2080-c70e-11ea-9505-bc85cb9cc66f.png)
Is it therefore necessary to run radiation with 'write-sensor-data = true' ?

**Comment by reyery** [comment]
@emanuel030 yes unfortunately setting `write-sensor-data` to **true** in radiation is needed for photovoltaic script to run.

However, this is set as **true** by default, and only to be set to **false** if you want to save disk space as the sensor data **and** not run PV potentials, since it is relative large compared to the aggregated radiation results for each building.
```
write-sensor-data = true
write-sensor-data.type = BooleanParameter
write-sensor-data.help =  Write also data per point in the grid. (Only needed to run solar technologies). False saves space in disk
write-sensor-data.category = Advanced
```

Currently, while not ideal since it causes issues such as this, it is the easiest solution to prevent radiation outputs to take up too much space as it adds up with larger number of buildings.

However, I do personally feel that finding a way to compress the size of sensor data (since it contains sparse data i.e. lots or zeroes) would be a better solution, since rerunning radiation is not exactly a wonderful experience. But that is a discussion for another time.

**Comment by emanuel030** [comment]
thanks for the explanation @reyery
