### ISSUE TITLE
Weather File error  creating a new scenario

### ISSUE THREAD

**Issue by AWillmann** [architecture-building-systems/CityEnergyAnalyst#2898]
while creating a new scenario, the weather file tool can´t be used - instead of the menu for choosing the weather file there is an error message without any details.

**Comment by nasty-bos** [comment]
Hi @AWillmann . To see more information about the occurred error, first you should start the backend of the CEA Dashboard by typing `cea dashboard` in the CEA Console. Then, open the CEA Dashboard application. Please repeat the actions in the Dashboard that led to the error, and send us the information from the CEA Console. In this way, we will be able to see what is causing the error. Please note, that you should have a developer version of CEA installed to be able to use CEA Console. Let us know if you have questions.

@lguilhermers is this the same issue that was happening to you?

**Comment by lguilhermers** [comment]
Yes, quite possibly is the same bug that I observed.

**Comment by lguilhermers** [comment]
@AWillmann seems that the bug is caused by a non existent weather folder/ file. 
You can fix it by opening the cea.config file in your installed folder and changing [weather-helper] - weather =
to a working path with an .epw file (Users\Documents\CityEnergyAnalyst\CityEnergyAnalyst\cea\databases\weather already contains some weather files stored that you can use). You can then run the weather helper in the dashboard so this weather is stored in your project folder.

Meanwhile we will work on fixing two related issues:
1 - Make the default weather path to CEA's weather files
2 - Display the proper error message (that seems a GUI issue that @reyery might be able to help)

**Comment by AWillmann** [comment]
@lguilhermers writing the weather file location into the cea.config didn´t solve the problem. I unistalled and re-installed CEA - now the weather menu is working again. Before, there was no possibility to choose a weather file (see screen shot)
![CEA weather error](https://user-images.githubusercontent.com/33447712/103178665-12e85b80-4885-11eb-826e-04ba0044df2a.JPG)
