### ISSUE TITLE
editing schedule files outside CEA

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2982]
**Describe the bug**
Maybe this is not a bug or maybe is a known issue, but I am seeing a strange behavior. 
Whenever I edit the csv file that corresponds to schedules (inputs\building-properties\schedules\... csv) outside of CEA and save, this file can't be read back by CEA. The corresponding field on the dashboard is then shown empty (see below).

![image](https://user-images.githubusercontent.com/50981039/119457220-056cca00-bd6e-11eb-9a7a-4fa7b6e30c04.png)

I wanted to make all fields constant at peak capacity, therefore set all values to 1, so far I could only do it manually one by one using the dashboard. Since I have a single building is ok, but still editing the csv would be easier.

**To Reproduce**
1. Go to any scenario where schedules is already defined
2. Edit the .csv file (inputs\building-properties\schedules\... csv) and save
3. Open the the dashboard and go to inputs-schedules and select the building you edited.

**Comment by lguilhermers** [comment]
Another related point that I would like to add is that the schedules I have seen are all under 1, peaking at 0.9 or 0.95. Is there a reason for that?

For me it seems a bit counter intuitive, because the peak is not really the true peak for those cases (e.g., 5 W/m2 is set as the peak but this value is never reached. Instead 5 * 0.9 is the true peak.). Wouldn't it make more sense to have all the schedules reaching the value of 1 at least for one hour for either weekend or weekday?

**Comment by shanshanhsieh** [comment]
hi @lguilhermers ,

- i haven't tried it myself and also don't see why it wouldn't work. but i would suggest to try modify the file using a script and save it back the same way as in this function `save_cea_schedule`
- as for the peak values, i think they were taken from standards. it is kept that way just to maintain consistency between our database and the source. feel free to send a PR to update those standards if there are new sources that make more sense : )

**Comment by martin-mosteiro** [comment]
@lguilhermers I recently had this issue myself as I was trying to recursively run simulations while changing the input schedules. The problem lies in the fact that the input csv files has a different number of columns in different rows, so there is no easy way to edit those (that I know of) with either Excel or pandas:
- If the file is read on pandas, it'll either have the wrong column format or you'll need to `skiprows` in which case you'll lose information (I am not sure if there's a pythonic way to import a csv file like this and save it again correctly):
<img width="1006" alt="Screen Shot 2021-05-26 at 16 36 19" src="https://user-images.githubusercontent.com/18548065/119629721-db380c80-be40-11eb-9954-42c236e02161.png">
- If you try to edit them in Excel you'll have extra columns in the csv file after editing:
*Before:*
<img width="888" alt="Screen Shot 2021-05-26 at 16 25 08" src="https://user-images.githubusercontent.com/18548065/119627817-1df8e500-be3f-11eb-995a-cfb5f1da0de9.png">
*After:*
<img width="731" alt="Screen Shot 2021-05-26 at 16 25 34" src="https://user-images.githubusercontent.com/18548065/119627853-23eec600-be3f-11eb-94fb-f8e58d38b060.png">
- You can use a text editor, but that is usually cumbersome when trying to edit schedules.

There's a workaround: you can edit the file on Excel, then manually remove the extra commas on a text editor. The second workaround is to just not edit the input files at all, but edit the _output_ files instead. Those are easy to edit on pandas (or Excel if you prefer). That's what I did for my simulations, since that even saved me the time to run the schedule maker on each run of my simulation.

**Comment by lguilhermers** [comment]
Got it @martin-mosteiro , thanks for the detailed explanation and efficient workaround :D
I will keep in mind if I ever face this for larger cases.

Another solution would be to change the structure of the monthly multiplier, since it doesn't seem to fit well in this file and be the origin of the problems. There could be a single file that defines all monthly multipliers per use type (similar to the USE_TYPE_PROPERTIES.xlsx) to avoid adding too many files. This way the csv for schedules can have a more regular format.
But probably the impact is also big of this change and requires quite some work as well...

**Comment by shanshanhsieh** [comment]
thanks @martin-mosteiro  for sharing!
for future reference, i am deleting my previous false answer to avoid confusion : )

**Comment by martin-mosteiro** [comment]
> Another related point that I would like to add is that the schedules I have seen are all under 1, peaking at 0.9 or 0.95. Is there a reason for that?

Just noticed this question, I've noticed that as well. I'm not sure what's the reason, but that's actually the way the standards are written for both occupancy and appliances. What's worse, the monthly multiplier is less than 1 anyway (at least in the CH case, not sure about SG), so it's X W/m2 * say, 90% at time t * 80% on month m, the actual peak is 0.72*X.

Since the standard uses those values, I would say it's best to keep it that way, but it is very counterintuitive in my opinion.
