### ISSUE TITLE
Search locaiton in Create Scenario not working due to changes in Let's Encryption certificates

### ISSUE THREAD

**Issue by jimenofonseca** [architecture-building-systems/CityEnergyAnalyst#3048]
Not sure if I am the only one but when you create a new scenario it seems that searching a location on the map does not work. @reyery how is it at your end?

**Comment by shanshanhsieh** [comment]
i also got the same error just today.

**Comment by reyery** [comment]
This is a GUI problem, where the api request is getting a certificate error when trying to do the geocoding using openstreetmaps (https://nominatim.openstreetmap.org/). This is caused by recent changes in the Let's Encryption certificates (used for https)[[source](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)], and since Nominatim uses letsencrypt certificates, it kind of broke it. One way to solve it is to update Electron used by the GUI to the newest version (which should update the underlying node version with new ca certs).
