### ISSUE TITLE
Demand forecast tool only considers ARU for cooling when no ventilation system is selected

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#3124]
**Describe the bug**
It appears that the demand forecast tool is only running ARUs, **NOT AHUs and SCUs**!
For example, look at the operating temperatures for a building with cooling system `HVAC_COOLING_AS4` (3-for-2, i.e., AHU+ARU+SCU).
![image](https://user-images.githubusercontent.com/18548065/160794130-bd043193-9111-4595-b701-bfdeeb9b3a3c.png)

Okay, that's not great. But what about the space cooling demand?
![image](https://user-images.githubusercontent.com/18548065/160795164-3ec47676-bc0a-418d-a155-04a84c3296fc.png)
i.e., the entire load is being supplied by the ARU.

I've checked what would happen if I had an office building with `HVAC_COOLING_AS3` (central AC, i.e., AHU+ARU) with similar results: the entire cooling load was provided by the ARU.

@shanshanhsieh Can you think of a non-buggy reason for this to happen?

**To Reproduce**
1. Create a case study along with its input databases
2. Assign a cooling system that includes AHUs and/or SCUs (e.g. `HVAC_COOLING_AS3`, `HVAC_COOLING_AS4`)
3. Run the solar radiation, schedule maker, and demand forecast tools
4. Check the results for `Qcs_sys_kWh`, `Qcs_sys_scu_kWh`, `Qcs_sys_ahu_kWh`, `Qcs_sys_aru_kWh`

**Expected behaviour**
The load shouldn't be supplied entirely by the ARU.

**Comment by martin-mosteiro** [comment]
I know what you're thinking: "oh, I bet this is an issue that only shows up in Singaporean case studies!"
Well, check out this case study in Zurich (a large office building in the ETH campus with cooling system `HVAC_COOLING_AS3`):
![image](https://user-images.githubusercontent.com/18548065/160804920-88d61319-a2a4-484a-917e-6b351cbd2494.png)
So... yeah, there's an issue.

**Comment by shanshanhsieh** [comment]
Hi @martin-mosteiro ,
The reason why AHUs are not triggered is probably because `type_vent=HVAC_VENTILATION_AS0`
AHU is part of the mechanical system, therefore, will only be used if `m_ve_mech>0`
In the SG database, the commercial buildings (STANDARD3-5) are set with `HVAC_COOLING_AS3` and `HVAC_VENTILATION_AS0`. Please try again with this combination and check if the problem persists.
![image.png](https://images.zenhubusercontent.com/57b4452fe40e5714b16d75a2/979e217b-2947-41b7-9478-7ab605c65bd5)

**Comment by martin-mosteiro** [comment]
Hey @shanshanhsieh,

You're right, that's exactly the combination in the aforementioned cases, as I modified the assigned cooling systems but _not_ the ventilation systems.

Isn't that _really_ counterintuitive, though?
1-Central AC is a cooling system first and foremost, why should the choice of ventilation system override the operation of the cooling systems? (If anything, shouldn't the choice of central AC override the choice of ventilation system?)
2-Why is the AHU considered part of the ventilation system but the ARU isn't?
3-An AHU and window ventilation are not incompatible per se – Okay, maybe in Singapore you _really_ shouldn't have that combination, but even here I have seen buildings with central AC and operable windows.
4-Is there any real case in which a building might be cooled entirely by an ARU?

Anyway, I get why system operation is calculated this way in the CEA code, but it kind of sounds like the choice of cooling system should override the choice of ventilation system, rather than the opposite. This could be implemented similarly to how if you choose `HVAC_HEATING_AS0` and `HVAC_COOLING_AS0` but `Hs > 0` you get a flag and the value of `Hs` in the calculation is adjusted automatically.

@shanshanhsieh as the cooling system expert I'll defer to you to make the call, but if the answer to question 4 above is "no" and you agree on the change I suggested above, I'll go ahead and create a PR.

**Comment by shanshanhsieh** [comment]
1&3 I agree. Ideally, a central AC should always come with mechanical ventilation. We could do an input check to avoid `HVAC_COOLING_AS3/4 `+`HVAC_VENTILATION_AS0`. 
If I understand you correctly, please go ahead to implement the check!

2&4 I can see that the names are a bit confusing, but in the system definition of the CEA, AHU (Air Handling Unit) treats outdoor air (equivalent to OAU in the figure below), thus is triggered by the mechanical ventilation requirement, and ARU (Air-Recirculation Unit) only conditions the indoor air (equivalent to RAU in the figure below), therefore, it is not connected to the outdoor air.
![image (1)](https://user-images.githubusercontent.com/16998305/161261429-001ab044-85e4-4708-851a-d351e8d2de31.png)

Air-conditioning units for residential buildings are an example of only using ARU, because no mechanical ventilation is involved.

Let me know if anything is uncelar.

**Comment by martin-mosteiro** [comment]
@shanshanhsieh Thanks for the very didactic explanation! True, you told me about mini-split AC as ARU last time oredi.

I'll add a check to avoid cooling type 3/4 and ventilation type 0 as discussed
