### ISSUE TITLE
OSM: "Building Part" category seems to give a better representation of building geometries

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#3220]
Looking more into OSM, I also noticed some buildings are better represented by a category in OSM named "Building Part" rather than "Building". At least for the central region of Singapore (see below), "Building" tends to specify the whole plot areas, while "Building Part" seems to by quite accurate to describe the polygons of the high rise buildings.

From my experience, there is a tendency to over predict the energy consumption in those buildings with reasonable parameters, and I think a good portion is this simplification of towers to plot areas.

Does it make sense to consider "Building Parts" to evaluate the geometries instead?

PS: For this to be implemented, it would be good to see how consistent this pattern is across different regions (in Singapore and globally).  So far my insights are only coming from a specific area in the Singaporean CBD.

![image](https://user-images.githubusercontent.com/50981039/183796699-d508773f-594a-4530-b51d-65374a571962.png)

**Comment by martin-mosteiro** [comment]
The problem is, while the "building" vs. "building part" labeling might commonly be used to represent the building pedestal vs. tower in OSM in Singapore, this labeling might not be consistent elsewhere. Off the top of my head, I checked my old case study to see how these labels might be applied somewhere else:
![Screen Shot 2022-08-10 at 12 14 09](https://user-images.githubusercontent.com/18548065/183814730-93a9e3a5-bf59-4b67-a9ac-c1940a6d5496.png) ![Screen Shot 2022-08-10 at 12 14 42](https://user-images.githubusercontent.com/18548065/183814738-721d9d67-f3b8-4d16-aa0f-7fd77b120215.png)
Here, the "building part" label is actually labeling a part of the building that has _less_ floors, and if we just take the "Building part" information we're getting rid of most of the building! 
(For reference, here's what the actual building looks like:)
![Screen Shot 2022-08-10 at 12 15 45](https://user-images.githubusercontent.com/18548065/183814941-d5679cc5-b088-4c9d-b5d6-ac2cecd14290.png)

So given that there is no consistent application of the "building part" label in OSM, taking just the "building part" _instead of_ the "building" is not really an option. It might work for towers in Singapore, but maybe not elsewhere. Since "building" is the standard label for buildings in OSM, if we were to use one I think we should use "building".

From the look of it, though, ideally we should use both! i.e., these could be two different polygons in a shapefile with different building heights. The problem is we generally can't get the number of floors from OSM, so I'm not sure what would be a practical way to do this while ensuring we don't lose other information in the process. (e.g., if we force the surrounding polygon to have a different height than the main tower we might be losing valuable information in the hospital building I posted above).

**Comment by martin-mosteiro** [comment]
By the way, while it's true that demands appear to be overpredicted in Singapore, I've had cases in the past where heating demand was severely underpredicted in a European context. So any change should be tested in more than one context to make sure solving an issue in Singapore creates an issue in other climates.

**Comment by lguilhermers** [comment]
Good points, @martin-mosteiro. I don't think the building should be neglected as well. For most contexts, it will be the one that contains the useful information.
But considering that the 'building parts' tag also seem to contain more detailed information about building geometry (and sometimes also height/ floor). I wonder if we should always import **both**. This might add some extra work to delete and/or change heights, in part reduced by the recent PR that fixes overlaping geometries (#3208).

In the case that I showed, there is a tower and a podium, and this geometry could be replicated by impoting 'building' and 'building part' with overlap geometries set to on and then manually adjusting the podium height (not informed in OSM).
In your case, the building seems to have a difference of one floor which is why there is a building part that represents that. By doing the same process, we would also end up with the most accurate geometry.

I don't see any current drawback of importing both, other than you might end up with more overlaping geometries (which can be fixed by CEA itself now) and maybe require a bit more manual editing, with the advantage of being able to capture more detailed geometries and more data (sometimes level and height is only available in the 'building part').

**Comment by martin-mosteiro** [comment]
@lguilhermers Yes yes yes! That's exactly what I meant, both polygons should be imported. I wasn't aware of the overlapping geometries update, that should make it easier!

It will still be up to the user to figure out which part of the shapefile is a podium and which one is a tower, which is why I suggested we might even include a "possible podium" tag or similar when a building completely surrounds another. But I guess that's to be decided by whoever implements this :)

**Comment by martin-mosteiro** [comment]
Note: using building parts may discard useful information about a building.

Take, for example, Lau Pa Sat. Here's a selection of the information obtained from OSM for building (index 2) and building:part (all other indeces):
<img width="372" alt="Screen Shot 2022-08-26 at 12 26 58" src="https://user-images.githubusercontent.com/18548065/186822075-299e93f0-697d-4f1b-9819-d547b30460c2.png">
The building polygon has the correct building use type tag (yay!) but no height (ooh...)
The building parts have the correct building height (yay!) but no building use type tage (ooh...)

So if we include building parts, we might need to add a check to fill in this missing data.
