### ISSUE TITLE
Problem using project of older CEA-version 

### ISSUE THREAD

**Issue by Mar-Ges** [architecture-building-systems/CityEnergyAnalyst#3241]
**Problem**
I'm starting to work on a quarter which was already part of a further study. 
On of my colleges would like to give me his baseline-scenario out of an existing project.

Unfortunately CEA on my computer can't find all the databases:
- architecture, air-conditioning-systems and supply-systems are missing 
![image](https://user-images.githubusercontent.com/73158684/188400132-6006cdd7-4902-4d91-ae40-233fbd0d34a9.png)

- in the data I can find the dbfs 
![image](https://user-images.githubusercontent.com/73158684/188400264-7e2e4d9f-e8d9-4f73-8e69-0df4d84f0bb1.png)

**Formal information**
I'm using version 3.31.0
my college is using 3.22.0 
both on windows

**Comment by lguilhermers** [comment]
HI @Mar-Ges,

This is due to a change of structure in the CEA database. I believe it was implemented before 3.22, so these versions should already be compatible in this aspect. In case they aren't, you can try going into utilities > Data migrator.
Please create a copy of the scenario before running it as backup, as this is a irreversible operation.
Hopefully this works, otherwise feel free to reopen the issue.
