### ISSUE TITLE
We should merge typology.dbf to zone.shp's attribute table

### ISSUE THREAD

**Issue by shizhongming** [architecture-building-systems/CityEnergyAnalyst#3350]
During the on-going FCLG's Summer School, I observed that students tend to mismatch the contents in zone.shp and typology.dbf when dealing with large number of buildings.

An easy fix (not sure how easy actually, probably @reyery knows) would be merging typology.dbf into zone.shp's attribute table. By doing this, we also reduce the minimum required input for CEA down to one file only: zone.shp

What do you think?

**Comment by martin-mosteiro** [comment]
It's indeed an easy fix.
My opinion: conceptually, it makes more sense to have them separately (because one goes in the building _geometry_ bin and the other in the _typology_ bin) but I also think it's a bit counterintuitive that the typology and zone files are both created from OSM but go into different files and different directories. So I think it's ok.

**Comment by lguilhermers** [comment]
I agree with the points raised by Martin (pros and cons) and would add that generating a self-made geometry is probably more trivial since you worry about less information to fill than if they are unified. But this is not a major point and can easlity be accounted. Also, since the current way never bothered us too much, I feel it would probably become natural for the students once they have more experience as well. 

My suggestion would be to track if this is still pointed as a concern by the end of the period.

**Comment by shizhongming** [comment]
I understand why conceptually we had them separate in the first place. We, as power CEA users, we conceptually know well how CEA and we encounter less problems. What I have observed is from a group of students who were never exposed to CEA before. Based on this observation, merging the two will increase CEA's user friendliness especially for using user-defined geometries. 

This raise another thing worth discussing: should we switch our workflow from very much OSM-dependent to user-defined-input-dependent? At the end of the day, more users (e.g. urban designers, architects) will be using their own/ modified geometries rather than geometries from OSM. Hence, again, it would great the enhance the user friendliness from self-import use case.

**Comment by martin-mosteiro** [comment]
@shizhongming I agree it'd be great for there to be _some_ way to start a CEA case study from scratch using your own shapefile (or whatever format is feasible)!

**Comment by lguilhermers** [comment]
I agree, for now it feels like a "trick" to have own geometries into CEA. A more direct workflow for self-made to import geometries would be quite useful.

**Comment by shizhongming** [comment]
I will create another issue and initiate an Epic for this switch. :D
