### ISSUE TITLE
 Correspondence between graphic and table units 

### ISSUE THREAD

**Issue by montecinosmedel** [architecture-building-systems/CityEnergyAnalyst#3441]
**Description**

When reviewing the data in Excel and the data shown in the graph for final energy use (within the CEA programme), I get an inconsistency with the units. 

In the graph the electricity demand corresponds to **4.91 MWh/yr** (see picture below).
![Screenshot 2023-12-21 130215](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/144387468/9d6fe38b-bbb2-452b-9164-285cad521014)

When obtaining the total values in Excel of the **GRID_kWh** column for the Building B1014 , the result ist **4912073 kWh/yr** (see picture below).
![aaa](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/144387468/a5205af5-ee2a-4493-9de4-2e89446e4582)

**Expected behaviour**

If the value shown in Excel were in Wh,  would correspond to 4.91 MWh/yr, which would be in accordance with the graph provided by the software. Since the value in the Excel table is in kWh units, the result shown in the graph should be **4912.073 MWh/yr** instead of **4.91 MWh/yr.**

What are the correct units? The ones in the graph or the ones in the excel table?

Thank you in Advance

**Hardware:**
 - Windows 10 Pro

**Comment by ShiZhongming** [comment]
Hi @montecinosmedel 

Sorry for the late reply as we were on winter break during Christmas and New Year.

I just used a random test case in Zurich for energy demand simulation and I could not replicate your results. 
The individual energy demand file (e.g. B1000.csv)'s unit is GRID_kWh and it matches the Electricity demand in the plot using the unit GRID_MWh.

Will you share your CEA scenario folder so that we can take a look?

**Comment by montecinosmedel** [comment]
Hi [ShiZhongming](https://github.com/ShiZhongming),

the problem was in excel because the program did not read the comma separation correctly.

Thank you for your time
