### ISSUE TITLE
Different typology data for the same building

### ISSUE THREAD

**Issue by montecinosmedel** [architecture-building-systems/CityEnergyAnalyst#3462]
**Description**

By selecting a small surface volume, the typology of a building is defined as Standard04, Year 2000 (see picture below)

![02_jpg](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/144387468/54f66df2-3d7c-4e81-a9e1-5ebb2867baf7)

By selecting the same building but in a scenario with a larger volume of data, I obtain the following information: Standard01, Year 1907 (see picture below)

![01_](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/144387468/532b7ab7-6094-46c5-af86-8edb05819bd1)

I did not edit any data...

How could I fix this situation?

Thank you in advance

 - Windows 10
 - CEA version 3.34.2

**Comment by ShiZhongming** [comment]
Hi @montecinosmedel 

By fixing this situation, do you mean to have the two situations having the same Standards?

The current situation is actually an expected behaviour. When CEA is pulling data from OSM, sometimes the data might not be complete. CEA has to make an "educated guess" to complete the missing data. In your case of the two scenarios, when having different size of districts, it just happened that CEA datermine the missing data differently. 

Please note that CEA pulls data from OSM and completes the missing data to reduce the effort for our users' effort to get the simulations started. It is expected that users have perform a check to ensure the data reflects the reality to a satisfactory extent before executing any simulations.

Back to your case, we suggest you checked the CEA assumptions and correct them as per your need manually. We are sorry that we cannot provide a solution to completely reduced the effort from our users to do the check-and-correct first.

**Comment by montecinosmedel** [comment]
Hi @[ShiZhongming](https://github.com/ShiZhongming)

thank you for your reply.

Is there a way that I can automatically enter the data of the age of the constructions coming from another database?
I am thinking about the option that for example a city can make available to the users a cadastre of the age of the constructions...

**Comment by ShiZhongming** [comment]
@montecinosmedel 
The short answer is yes.
You can process the zone.shp outside from CEA Dashboard using ArcGIS Map for example, where you can spatially join building age data to the footprints.
https://desktop.arcgis.com/en/arcmap/latest/tools/analysis-toolbox/spatial-join.htm
Please pay attention to the column names of the processed shapfile's attribute table. They have to be exactly the same as before and case sensitive.
