### ISSUE TITLE
The simulation has been running without results

### ISSUE THREAD

**Issue by yameima** [architecture-building-systems/CityEnergyAnalyst#3526]
Hi, developers:
I have a problem when I simulate the building solar radiation. The simulation has been running without results. What is the reason? Is it because the computer performance is not enough. Does this software have the computer performance requirements?
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150877623/77b090b7-b9e7-4c60-b742-1adc03622967)
Thank you very much for taking the time to answer my question！

**Comment by yameima** [comment]
the version of my software is V.3.35.4

**Comment by reyery** [comment]
Hi @yameima, thanks for reporting this issue. 

When running the solar radiation script, do you see any CPU usage in the Windows Task Manager?

We do not impose any minimum requirements for CEA, since any modern machine with about 4 cores should be able to run it well. Having more cores would help to make to run a bit faster.
