### ISSUE TITLE
Bug? very high indoor temperatures 

### ISSUE THREAD

**Issue by anjaWill** [architecture-building-systems/CityEnergyAnalyst#3600]
**Describe the bug**
despite the 2015 weather file (data are fine) and a Northern Germany location, the indoor building temperatures are very high (above 100°C in Jan 1st, 1:00 am) 

**To Reproduce**
After wondering why there was no space heating demand in the project, I created a project containing solely the main building. Same result: no space heating due to extremely high indoor temperatures. German database, gas heating, window ventilation, multi-res with advanced refurbishment, no cooling. construction created by archetype mapper.

**Expected behaviour**
space heating demand and T_int between 10-15 °C in January

**Screenshots**
![grafik](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/150787078/7e690226-909a-40e7-a59c-453db9ce5561)

**Comment by ShiZhongming** [comment]
Hi @anjaWill 
Which `Construction Standard` did you use for the main building you mentioned?

**Comment by ShiZhongming** [comment]
Can you also share this scenario's inputs folder with me via email?

**Comment by ShiZhongming** [comment]
Hi @anjaWill 

Probably it is too late that I just figured out the problem here.
It seems that the weather file you are using has the sky temperaure_C in the range of 700+ while usually it should be ranging roughly between -20 to 40..
I have included a screenshot of your weather file here for your reference.
<img width="1023" alt="Screenshot 2024-06-11 at 23 17 02" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/16640327/87c93109-b21c-46b7-94a8-4ae4f090e030">
Issue #3603 is also caused by this issue...

Maybe you want to use another weather file..

Regards, Zhongming

**Comment by anjaWill** [comment]
Hi @ShiZhongming 
thanks for identifying the error. I used the official weather file by DWD - German Weather Database. Might this be caused by a "translation" error: German comma vs. english points?

**Comment by ShiZhongming** [comment]
Hi @anjaWill,

We took a closer look. It is CEA calculating this `sky temperature C`. 

Currently, CEA uses this parameter called `opaqskycvr_tenths` (i.e. opaque sky cover, in tenths.) from your weather file to calculate `sky temperature C`. However, `opaqskycvr_tenths` is missing in your weather file. When it is missing, it reverts 99, while actually N is supposed to be between 0-10. Hence, it casued the super high temeprature in your simulation. 

@reyery and I are updating CEA to handle epw data from weather files like yours which does not have `opaqskycvr_tenths`. This improvement will be reflected in the upcoming CEA release.

Thank you for spotting this. 

Regards, Zhongming
