### ISSUE TITLE
False diameter used for velocity calculation

### ISSUE THREAD

**Issue by KFSchlager** [architecture-building-systems/CityEnergyAnalyst#3652]
**Describe the bug**
The with thermal network (detailed) calculated velocity of the pipes does not match up the velocity it should have.
The tool seems to calculate the right diameters for the pipes, but with further calculation the pipe diameters get mixed up.
Therefore I don't know, if only the velocity is falsely calculated, or other parameters too.

**To Reproduce**
Create a cea project, run all steps to thermal network simulation part two
Run thermal network simulation part two with detailed model
Compare the maximum velocity from DH__velocity_edges_mpers.csv with the maximum massflow from DH__massflow_edges_kgs.csv and the to the pipes assigned diameters from DH__metadata_edges.csv

**Expected behaviour**
The results should fit together, but they don't

**Screenshots**
![grafik](https://github.com/user-attachments/assets/24cc9480-3b44-4a4e-9837-fefb22d31843)

**Hardware (please complete the following information):**
 - Windows 11
 - CEA v. 3.36.0

**Comment by ShiZhongming** [comment]
Hi @KFSchlager 

Thanks for raising the issue. I was able to reproduce the error. Apologies for the delayed reply.
The pipe diameters are calculated correctly, while the velocity is wrong as you described. This is because CEA:

Pipe diameter is primarily determined by the mass flow rate (massflow_edges_kgs) in the script.
The velocity is calculated as a consequence of the mass flow rate and pipe diameter but does not directly influence the diameter selection.
When calculating the velocity, the columns of the DataFrame storing the pipe properties were somehow messed up...

I have fixed this with #3664

Let me know if it works!

Thanks, Zhongming
