### ISSUE TITLE
Develop test case for testing the thermal and hydraulic losses

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#536]
Develop a test case to test the thermal_network_matrix.py file. This will be further useful in future to test the hydraulic and thermal losses for network optimization. 

Develop two/three network configurations for the 9 building case study

**Comment by martin-mosteiro** [comment]
Great idea! The network shapefiles are something that needs to be incorporated into the reference cases, anyway, so it obviously makes sense to include them in testing as well.

**Comment by shanshanhsieh** [comment]
@martin-mosteiro  shall I include you in this issue, then?  : ) 
Since it will require two parts:
1. Prepare the shape files of three testing networks for reference-case-open
2. Simulate those three testing networks in simulink

**Comment by shanshanhsieh** [comment]
Note for preparing `network-nodes.shp` and `network-edges.shp` on ArcMap:

1. `network-nodes` add following columns in the attribute table:

- Building Names (join from `zone.shp`)

- Plant: specify which buildings are plants (if yes, value = 1, otherwise 0) 

- Qh: specify which buildings are consumers (if yes, value = 1, otherwise 0)



2. `network-edges` add following columns in the attribute table:

- Shape_Leng: Calculate Geometry, length

**Note**
1. Spatial References of `cea-reference-open`: 

- Projection:

 CH1903_LV03 (automatically include global reference: GCS_CH1903)
2. Make sure the x,y coordinates read from geopandas of edges and nodes are the same. (to check: read x, y coordinates to the attribute table)

**Comment by shanshanhsieh** [comment]
@BhargavaKrishnaSreepathi  This issue is ready to be reviewed!
To test the three networks, please go to branch `i412` and run the reference case in `cea/examples/reference-case-open`, there is a readme guide on how to switch between three network configurations.
To verify the result with simulink model, please access the model via https://github.com/shanshanhsieh/network.
