### ISSUE TITLE
Update installer to suppress anaconda prompt shortcut

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#605]
The installer (used for the planner's edition of the CEA) currently creates an "Anaconda Prompt" shortcut in the Start Menu as part of the installation of miniconda.

I think it would be good to remove that shortcut after installation, as miniconda is installed in a standalone fashion and the console is not meant to be used. Actually, it is slightly broken due to the way it is set up.

Removing the shortcut needs to be done with caution, though, as the user might have a previous installation of Anaconda / Miniconda and we don't want to overwrite that. Maybe a strategy would be to rename the existing shortcut if it exists before installing Miniconda and then renaming it back after the installation and deletion of the bogus shortcut?

@JIMENOFONSECA what do you think the priority for this should be?

**Comment by JIMENOFONSECA** [comment]
I would give it priority 3 as it does not necessarily affects functionality. I wonder if this is something to consider after some user raises some discomfort with this, but not before.

Best, Jimeno

On 19 Apr 2017, at 16:26, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


The installer (used for the planner's edition of the CEA) currently creates an "Anaconda Prompt" shortcut in the Start Menu as part of the installation of miniconda.

I think it would be good to remove that shortcut after installation, as miniconda is installed in a standalone fashion and the console is not meant to be used. Actually, it is slightly broken due to the way it is set up.

Removing the shortcut needs to be done with caution, though, as the user might have a previous installation of Anaconda / Miniconda and we don't want to overwrite that. Maybe a strategy would be to rename the existing shortcut if it exists before installing Miniconda and then renaming it back after the installation and deletion of the bogus shortcut?

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what do you think the priority for this should be?

**Comment by daren-thomas** [comment]
also, maybe using pyinstaller instead of the current conda solution could be used!

**Comment by daren-thomas** [comment]
Closing, as we are now using a new method and the issue is not relevant anymore.
