### ISSUE TITLE
Cooling systems T1 and T2 not considered in emission system calculation

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#734]
Cooling systems T1 (cooling ceiling) and T2 (mini split AC) are not considered in:

`sensible_loads.calc_temperatures_emission_systems()`

-> have to be added

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA and @shanshanhsieh is this straightforward? Can I just use the same calculation as for the centralized AC (i.e. `cooling_system = T3`) ?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle not really, both models need to be created in the tool. I think I put them there as a potential expansion back in 2015 but the models were not fully developed. This is an issue of technologies for cooling in buildings that needs to be addressed.

This means that a model to calculate mass flow rate, and temperatures in the secondary loop of a mini-split unit and a ceiling cooling will be needed.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA OK. So this is a slightly bigger work. But isn't the mini-split not directly supplied by electricity? Are we considering connecting mini-splits to a district-cooling source?

**Comment by JIMENOFONSECA** [comment]
Just to cross-check, shanshan, would you like to explore this? :-). Otherwise we can pass it.

We still will need a model for the minisplit electricity consumption based on outdoor temperature of exhaust.

By creating it, we can also compute how much heat is released. A step forward to do outdoor climate studies with cea!!

Best, Jimeno

On 14 Jul 2017, at 16:17, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/jimenofonseca> OK. So this is a slightly bigger work. But isn't the mini-split not directly supplied by electricity? Are we considering connecting mini-splits to a district-cooling source?

**Comment by shanshanhsieh** [comment]
For the chill panel, the model to calculate temperature and mass flow in the secondary is necessary. This goes to the first priority. 
For the mini-split unit, the model for electricity consumption and exhaust temperature will be a great addition, but not as pressing as the chill panel. Therefore, this also goes to priority 1 but will happen later...
What do you think, @gabriel-happle & @JIMENOFONSECA ?

**Comment by JIMENOFONSECA** [comment]
I agree with shanshan. I wonder nonetheless if the mini-split will be neccessary to 1. run ecocampus. 2. compare any solution to the status quo (i.e., most residential buildings and hawkers in singapore use just min-split or fans).


________________________________
