### ISSUE TITLE
Create online manual of solar energy potential tool

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#814]

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  The manual is ready, please take a look and link it to the website. Thanks!

https://docs.google.com/presentation/d/1aLwicIC2RLbwXnq57B29v7ixdY8y-O80Po2uDYtRIiA/edit#slide=id.g208c017e98_0_94

**Comment by JIMENOFONSECA** [comment]
thanks!, I added the link to the website, btw, Is the title of the tool renewable energy potential?

On 21 Dec 2017, 2:01 PM +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> The manual is ready, please take a look and link it to the website. Thanks!

https://docs.google.com/presentation/d/1aLwicIC2RLbwXnq57B29v7ixdY8y-O80Po2uDYtRIiA/edit#slide=id.g208c017e98_0_94

**Comment by shanshanhsieh** [comment]
The tools are under the "Dynamic Supply Systems" tab at the moment, I can see the naming is a bit confusing...
we could do...
1. Move the three solar technologies to "Renewable Energy Assessment", the same tab as "Urban solar radiation"
2. option 1 + make a separate tab for "Urban solar radiation" since it is used for both demand and supply calculations 
3. or change "Dynamic Supply Systems" to "Renewable Energy Potential" or "Energy Supply Technologies". 

let me know what you think!

**Comment by daren-thomas** [comment]
@shanshanhsieh I too think the categories are a bit hard to navigate. Maybe we can come up with a better plan?
