### ISSUE TITLE
What is 'void_deck'?

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#992]
Three days ago, the input 'PFloor' was removed and replaced by 'void_deck' (#972). What is this? Can't find any documentation on this... @JIMENOFONSECA could you please clarify?

Thanks!

**Comment by JIMENOFONSECA** [comment]
HI martin, you can find the meaning in the tutorial of input databases of cea.

It replaces PFloor and indicates the percentage of floors that have a void deck. Like in a multistory parking lot.

It is just more simple than before. The master branch runs with the new inputs smoothly. Let me know if you find anymore problems

**Comment by martin-mosteiro** [comment]
Thanks for the answer, Jimeno. I agree PFloor was unnecessarily complicated, just wanted to know what 'void_deck' meant since it wasn't documented. Which tutorial do you mean by the way? [The one linked in our website](https://docs.google.com/presentation/d/14cgSAhNGnjTDLx_rco9mWU9FFLk0s50FBd_ud9AK7pU/edit) still shows PFloor and no mention of 'void_deck'.

**Comment by JIMENOFONSECA** [comment]
You are right, i changed the zone architecture but not the zone occupancy sorry..

Best,
Jimeno

On 26 Jan 2018, 19:56 +0800, martin-mosteiro <notifications@github.com>, wrote:

Thanks for the answer, Jimeno. I agree PFloor was unnecessarily complicated, just wanted to know what 'void_deck' meant since it wasn't documented. Which tutorial do you mean by the way? The one linked in our website<https://docs.google.com/presentation/d/14cgSAhNGnjTDLx_rco9mWU9FFLk0s50FBd_ud9AK7pU/edit> still shows PFloor and no mention of 'void_deck'.
