### ISSUE TITLE
thermal_network_matrix does not run for DH

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#997]
When simulating DH for reference-case-open, the thermal loss calculation is stuck at timestep 384.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh weird. I run it two days ago, it was ok :-)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA did you run through all 8760 timesteps?
cuz we replicated this error in mine, Lenny, and Bhargav's computers
i suspect that some temperature requirements was not correct... because the error happened at the substation calculation when temperatures from the primary side (network) is lower than the secondary side (building)

**Comment by JIMENOFONSECA** [comment]
Mmmm, probably that should not happen right?

On 29 Jan 2018, 18:48 +0800, Shanshan Hsieh <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/jimenofonseca> did you run through all 8760 timesteps?
cuz we replicated this error in mine, Lenny, and Bhargav's computers
i suspect that some temperature requirements was not correct... because the error happened at the substation calculation when temperatures from the primary side (network) is lower than the secondary side (building)
